### ISSUE TITLE
media recorder plugin

### ISSUE THREAD

**Issue by entonbiba** [wavesurfer-js/wavesurfer.js#1030]
Create a media recorder plugin or add a recording feature to current microphone plugin.

**To do list**
- create parameters (automatic record, audio type, max length etc)
- create getRecorded method to return array of recorded blob
- create downloadRecorded method to return a downloadable blob for .mp3 and .wav
- support Chrome, Firefox, Opera, Edge is currently under construction, Safari not supported
- create recording sample

#263 #272 #392 #754

**Comment by thijstriemstra** [comment]
I wouldn't want to add it to the microphone plugin but create a new plugin instead that uses the microphone plugin.

Note that there's already something similar in a 3rd-party plugin (that I maintain): https://github.com/collab-project/videojs-record

**Comment by entonbiba** [comment]
@thijstriemstra yea it will be a plugin, nice I'll check it out.

**Comment by ZachMoreno** [comment]
👍
I need this for my MVP & would love to contribute to this effort.
Just to be clear, the intention of this new wavesurfer.js plugin is to 
 1. record audio stream
 2. draw the audio stream as it is recorded ([example](https://youtu.be/qMaVhqSsPcE?t=2m32s))
 3. save the recorded stream as a blob/file
correct?

**Comment by ZachMoreno** [comment]
@thijstriemstra can you please explain a bit how videojs-record is extending wavesurfer with the [`liveMode` property](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L935)?

**Comment by thijstriemstra** [comment]
@ZachMoreno take a look at videojs-wavesurfer first..

**Comment by ZachMoreno** [comment]
@thijstriemstra thanks!

**Comment by entonbiba** [comment]
@ZachMoreno yes, exactly what DAW software do when recording input audio. It would eventually support live audio but I'm still working on that to see what kind of all browser support there is as well as making sure it doesn't crash the browser with all the rendering.

**Comment by sascharissling** [comment]
Hello. Is there some way to do this now? :-)

**Comment by nilesh121196** [comment]
check this to record and play audio by microphone plugin:
https://github.com/katspaugh/wavesurfer.js/issues/1515#issuecomment-590705075
