### ISSUE TITLE
Draw on pixel boundaries for even barWidth values

### ISSUE THREAD

**Issue by iainhallam** [wavesurfer-js/wavesurfer.js#1059]
Wavesurfer.js version(s): 1.3.2
Browser version(s): Firefox 52
Code needed to reproduce the issue:

    var wavesurfer = WaveSurfer.create({
    	barWidth: 2,
    	container: '#waveform',
    	cursorWidth: 0,
    	height: 32,
    	interact: false,
    	normalize: true,
    	pixelRatio: 1,
    	waveColor: 'orange',
    });
    wavesurfer.load('audio.wav');

Result:

![waveform-antialiased](https://cloud.githubusercontent.com/assets/282030/24758722/1e6d302e-1adb-11e7-9bb1-d9acfec4889c.png)

This waveform is looking good, but when I zoom in on a screenshot of it, I can see that each bar isn't actually separated from its neighbours fully - they have what looks like an antialiased edge on the left of each. It looks as though each bar ends on a multiple of three pixels (barWidth 2 plus a single pixel space) so I'm not sure what's causing the canvas to have to do what looks like interpolation.

Is there a way to get a clean edge to each bar so there are only two colours (the waveColor and the background) appearing in the rendered canvas?

**Comment by entonbiba** [comment]
@iainhallam can you try with the latest versions?

**Comment by iainhallam** [comment]
I've just tried on 1.4.0 and 2.0.0-beta01, but the result is identical. Still antialiased on the left edge of each bar, including the first. Interestingly, I've just noticed that the final edge on the right looks as though there's only the antialiased edge, not the bar itself - just as in the image above.

**Comment by iainhallam** [comment]
Checking the code, I see that a half pixel is always being added:

https://github.com/katspaugh/wavesurfer.js/blob/d2a1f38f1202187f42d4927977fe1af6c92d15a7/src/drawer.multicanvas.js#L270

The comment above it suggests "A half-pixel offset makes lines crisp" but that's only true for odd widths. Since I'm using an even number for barWidth, the extra 0.5 is pushing the rectangle off the pixel boundary, so it should only be applied if barWidth is odd.

**Comment by thijstriemstra** [comment]
@iainhallam so you're saying a `barWidth: 2` will look crap, whereas `barWidth: 3` is fine? I can't spot the difference using master branch (3.0.0). Can you attach a screenshot showing the difference or something? Because the fix you describe should be easy to implement.
