### ISSUE TITLE
Show and play only a given audio sub-segment

### ISSUE THREAD

**Issue by alexcasalboni** [wavesurfer-js/wavesurfer.js#112]
Hi, is there any way of limiting the plugin (both drawer and player) to a specific sub-segment of the audio file? (i.e. from 00:10s to 00:30s).

I know this could be done by cutting the file on the server, but in my case I'm using a streaming service (which of course serves the whole song) and I'm not really supposed to pre-process all the files on my server (I don't even think it'd be legal).

In the master branch an ajax call is used to retrieve the file, therefore it wouldn't be very efficient (it should be only a matter of skipping some samples, though). Not sure about the other branches.

Any possibility for this feature to be introduced soon? How complex do you think it would be?

Thank you,
Alex

**Comment by evitolins** [comment]
A zoom parameter would be okay, but explicit start and end parameters to crop a audio segment would be ideal.  Any movement on this lately?

**Comment by peterj35** [comment]
I'm reviving an ancient issue but any workarounds or solutions on cropping an audio segment?
