### ISSUE TITLE
seekTo's .progress call makes cursors not appear immediately.

### ISSUE THREAD

**Issue by agamemnus** [wavesurfer-js/wavesurfer.js#1124]
For WebAudio:

1) On click, the code hits the` seekTo` function.
2) seekTo does `this.drawer.progress(this.backend.getPlayedPercents())` to set the cursor progress in the drawer.
3) `this.backend.getPlayedPercents()` uses the duration to get the return value.
The duration is 0 because audio didn't load yet,  since it only loads on an "interaction" (a click), I guess for optimization reasons.
4) The cursor is not set to the right position until the audio loads.

So, the situation is somewhat frustrating if I am trying to pre-load peaks and have everything work quickly. Is there any issue with replacing
````
this.drawer.progress(this.backend.getPlayedPercents());
````
with
````
this.drawer.progress(progress);
````
?

**Comment by thijstriemstra** [comment]
Please illustrate this with code or video/image footage, not sure what you mean..

**Comment by agamemnus** [comment]
That's too much work..

When I have peaks pre-loaded, the cursor doesn't show up when I click on the wave until the audio data is finished loading.

**Comment by agamemnus** [comment]
@entonbiba I think it's also a bug.

**Comment by agamemnus** [comment]
Actually, it looks like there is more than one issue here. I fixed it, but probably made it even more dodgy.
