### ISSUE TITLE
Get the actual pxPerSec

### ISSUE THREAD

**Issue by dimidd** [wavesurfer-js/wavesurfer.js#1150]
Hey,

I've written a function that zooms-in and out, by increasing/decreasing the current `minPxPerSec`.   The default value is 20, so I expected `wavesurfer.zoom(20)` to have no effect, however it actually zooms out. Is there way to get the actual `pxPerSec` rather than `minPxPerSec`?

**Comment by thijstriemstra** [comment]
@dimidd can you show some example code?

**Comment by yairopro** [comment]
Hi @thijstriemstra 
Is there a way to get the current pxPerSec ?

**Comment by aburai** [comment]
have a look at https://github.com/katspaugh/wavesurfer.js/blob/8ba3328102da9746ce1fd390c0801f01edaaf612/src/plugin/timeline.js#L365 -374
Hope that helps

**Comment by yairopro** [comment]
Thanks !

**Comment by Johnrobmiller** [comment]
> have a look at
> 
> https://github.com/katspaugh/wavesurfer.js/blob/8ba3328102da9746ce1fd390c0801f01edaaf612/src/plugin/timeline.js#L365
> 
> -374
> Hope that helps

what is in this source code that is helping to solve the OPs issue? `pixelRatio` is not a valid prop we can pass into wavesurfer
