### ISSUE TITLE
Regions plugin "Generic events - out" doesn't fires.

### ISSUE THREAD

**Issue by nazarposhta** [wavesurfer-js/wavesurfer.js#1189]
Generic events
in - When playback enters the region. - that works fine. 
out - When playback leaves the region. - that doesn't.

`region_info.on('in',() => { console.log('start') }); // awesome`
`region_info.on('out',() => { console.log('stop') }); // sucks`

Any ideas?

**Comment by mspae** [comment]
Can't reproduce. This works fine for me

```javascript
    // Init
    wavesurfer = WaveSurfer.create({
        container: document.querySelector('#waveform'),
        waveColor: '#A8DBA8',
        progressColor: '#3B8686',
        backend: 'MediaElement',
        plugins: [
            WaveSurfer.regions.create({
                regions: [
                    {
                        start: 1,
                        end: 3,
                        color: 'hsla(400, 100%, 30%, 0.5)'
                    }, {
                        start: 5,
                        end: 7,
                        color: 'hsla(200, 50%, 70%, 0.4)'
                    }
                ],
                dragSelection: {
                    slop: 5
                }
            })
        ]
    });

    wavesurfer.on('region-created', function (region) {
        region.on('in', function(e) {
          console.log('in ', region.id);
        });
        region.on('out', function(e) {
          console.log('out ', region.id);
        });
    });

    // Load audio from URL
    wavesurfer.load('../media/demo.wav');
```

**Comment by jlts713** [comment]
I encounter the same problem that sometimes the region 'out' event doesn't fire when audio region finishes playing. It happened when I set the region to be between two decimal numbers, like
start = 165.69
end = 169.44

**Comment by jlts713** [comment]
I believe this happens because the plugin use

    this.end <= Math.round(time * 100) / 100)

as condition to fire out event.
It would sometimes round the actually end time to be a bit lower than the specified end time which then cause this issue.

ps. sorry but somehow my github don't let me insert code or use markdown

**Comment by thijstriemstra** [comment]
thanks for the feedback @jlts713. The code you're talking about is still present in the master branch (soon to become 3.0.0), and I can see how this `Math.round` can be an issue. Question is; why is it there, who put it there?

**Comment by thijstriemstra** [comment]
> Question is; why is it there, who put it there?

It's pull request #574 that introduced part of this change, fixing #425.

**Comment by PaulLerner** [comment]
Hello, do you have any hints on how to fix this issue ? 
I'm having the same problem in gecko : https://github.com/gong-io/gecko/issues/27 (we closed the issue because we found some trick but it's not really satisfying)


> I encounter the same problem that sometimes the region 'out' event doesn't fire when audio region finishes playing. It happened when I set the region to be between two decimal numbers, like
> start = 165.69
> end = 169.44
> I believe this happens because the plugin use
> 
> ```
> this.end <= Math.round(time * 100) / 100)
> ```
> 
> as condition to fire out event.
> It would sometimes round the actually end time to be a bit lower than the specified end time which then cause this issue.
> 
> ps. sorry but somehow my github don't let me insert code or use markdown

I'm not sure this is the cause of the bug, `Math.round(169.44 * 100) / 100` gives `169.44`

Bests,

**Comment by Bug-Reaper** [comment]
I am also experiencing the original issue. Events are running, code is running, console.log is silent for no reason.
