### ISSUE TITLE
Cloned wavesurfer script on NPM

### ISSUE THREAD

**Issue by mspae** [wavesurfer-js/wavesurfer.js#1195]
On NPM there is a package called  `wavesurfer` which is a clone of `wavesurfer.js`  – It is currently at version 1.3.4. (I took a quick look into the code to make sure it wasn't malicious – it appears to just be a simple clone, no manipulation was performed)

I propose we write to the author and kindly ask him to replace the package with a README pointing to `wavesurfer.js` and [deprecate](https://docs.npmjs.com/cli/deprecate) the package so people reference the maintained, official version.

**Comment by katspaugh** [comment]
Oh. I'll write to them. Thanks!

**Comment by thijstriemstra** [comment]
any news @katspaugh?

**Comment by katspaugh** [comment]
Nope, no response. I'll ping @disrupt again.

**Comment by thijstriemstra** [comment]
Thanks. For all we know it might even contain malicious code.

**Comment by katspaugh** [comment]
The owner has just responded – he meant well and is working on deprecating the package.

**Comment by thijstriemstra** [comment]
I suppose we're talking about this one: https://www.npmjs.com/package/wavesurfer

That sucks.

**Comment by thijstriemstra** [comment]
Any way we can contact npm to let them know this is an old package and should be alias of wavesurfer.js?

**Comment by katspaugh** [comment]
That package is now deprecated :)
