### ISSUE TITLE
Waves generated from audiowaveform output peaks, doesn't match output without it

### ISSUE THREAD

**Issue by marwan-nwh** [wavesurfer-js/wavesurfer.js#1218]
**Wavesurfer.js version**: 2.0.0-beta02
**Browser version**: Chrome - Version 61.0.3163.91 (64-bit)

When loading the file without passing peaks, the output looks like this:
![screenshot from 2017-10-04 17-38-19](https://user-images.githubusercontent.com/1739939/31184862-dc32d716-a92a-11e7-96a6-519f24ffe5eb.png)

When passing the peaks generated by the audiowaveform command provided in the FAQ, and setting `normalize` to true, I get:
![screenshot from 2017-10-04 17-40-22](https://user-images.githubusercontent.com/1739939/31184966-1d8e8dcc-a92b-11e7-83d8-d847ede7b0b9.png)

How could they don't match? What should I do to get the right waves?

Also, If I understood correctly, the `exportPCM` method exports the peaks generated by wavesurfer. If you took it's output, and pass it to `load`, you won't get the same waves also.

**Comment by mspae** [comment]
@mrwnmonm exportPCM supports an accuracy and length parameter. Have you tried playing around with that? https://wavesurfer-js.org/doc/class/src/wavesurfer.js~WaveSurfer.html#instance-method-exportPCM

**Comment by mrwnmonm** [comment]
It is not obvious what those do.

**Comment by mrwnmonm** [comment]
@mspae It is not obvious what those do.

**Comment by mspae** [comment]
True, the documentation could be better.

The length determines how many peak values (value pair of minimum and maximum modulation) should be in the exported PCM data.

The accuracy is used to determine how much the values should be rounded.
