### ISSUE TITLE
FR: Prevent HTML Audio Tag Injection (lazyload option)

### ISSUE THREAD

**Issue by X-Raym** [wavesurfer-js/wavesurfer.js#1237]
Hi,

This is a follow-up a the issue discussed on the [Bug: Browsers don't respect setting preload to "none" in wavesurfer.load()](https://github.com/katspaugh/wavesurfer.js/issues/973#issuecomment-340260055) issue.

## Context

This issue concerns using MediaElement backend and Cached Peaks.

## Problem

Some browsers ignore the preload=none attribute of audio tags.
This means that in some cases, audio files are loaded even if not needed.

## Proposition

Only inject audio HTML tags when needed (aka, after a custom event).
For this, we can imagine having a `lazyload` wavesurfer init option attribute, to init the object.
Initializing the object also require knowing its length before hand. (attribute integration proposition by @mspae : https://github.com/katspaugh/wavesurfer.js/commit/1025d7263e32f087a3404012dbf0301e5f95b383 )
This will not be a problem with cached data (the length can be added in the cache file).

This will increase wavesurfer performance and some browser/OS (like Safari+MacOS) a lot ! :)
Thanks for taking a look !

**Comment by mspae** [comment]
@X-Raym I've opened a PR on the duration parameter.

**Comment by thijstriemstra** [comment]
@X-Raym PR was merged and released, closing issue.

**Comment by X-Raym** [comment]
@thijstriemstra Thanks, but has the `lazyload` attribute been integrated or only the `duration` ? As far as I remember, we needed both for this FR, and @mspae pull request was just for `duration`. Correct me if I'm wrong.

@mspae Do we need both attribute for this FR ?

**Comment by thijstriemstra** [comment]
I see. Can you make a pull request?

**Comment by X-Raym** [comment]
@thijstriemstra I personnaly can't, it has become a bit out of my league :S Maybe @mspae had ideas about how to implement it to finalize this FR ?

**Comment by thijstriemstra** [comment]
>  it has become a bit out of my league

That sounds like a problem with the library, can you elaborate?

**Comment by X-Raym** [comment]
@thijstriemstra What I meant is that I don't know how to implement this `lazyload` option, wavesurfer.js is a pretty complex script.

**Comment by X-Raym** [comment]
@katspaugh how has this been solved?

**Comment by katspaugh** [comment]
Please feel free to reopen this if this is still an issue. Browsers might've gotten better since 2017.
