### ISSUE TITLE
Is there a way to get a wavesurfer object by id?

### ISSUE THREAD

**Issue by everruler12-secondary** [wavesurfer-js/wavesurfer.js#1269]
For example:
`WaveSurfer.getObjectbyId('#waveform').play();`

**Comment by GitHubRakeshSharma** [comment]
Can you specify what you want to do?

**Comment by eiennosihaisya** [comment]
I want to access one of many wavesurfer objects that have already been dynamically created on a page by its container id (similar to [videojs](http://docs.videojs.com/tutorial-player-workflows.html#accessing-a-player-that-has-already-been-created-on-a-page)), without using a global array to store the wavesurfer objects.

**Comment by GitHubRakeshSharma** [comment]
Maybe this will help... although it's not exactly what you want..
[https://github.com/katspaugh/wavesurfer.js/issues/284](url)

**Comment by thijstriemstra** [comment]
maybe @mspae has an idea.
