### ISSUE TITLE
split Wave Point plugin is missing

### ISSUE THREAD

**Issue by rowild** [wavesurfer-js/wavesurfer.js#1286]
Hi, guy,

since you mention that heavy testing by many people is needed, I try to do my 2 cents... this is what I found so far:

For the plugins
- mediasession
- split Wave Point
no javascripts are generated on "npm run start:plugins" (console error)

- stretcher
throws an error:
```
app.js:9 Uncaught TypeError: wavesurfer.init is not a function  at HTMLDocument.<anonymous> (app.js:9)
```

- plugin-system
The "cursor" plugin doesn't do anything. I would expect that the cursor appears and disappears, when the respective check-box is (de)activated - but nothing happens. (No messages in the console either.)

I did my best to research before posting - sorry, if I mention things that are already filed.
No code examples provided, since these overservations derive from just testing the given scripts.

My env: 
Chrome 63, macOS 10.12.6, node 6.9.5, wavesurfer 2.0.1

**Comment by thijstriemstra** [comment]
Thanks for the report, I'll look into it.

**Comment by thijstriemstra** [comment]
Yea looks like there are many files missing, and some merge got screwed up at some point :(

**Comment by thijstriemstra** [comment]
> mediasession

Restored.

> split Wave Point

I tried to restore it but have no idea what this plugin is supposed to do etc, so maybe someone else can take a look at this..

> stretcher

fixed.

> plugin-system

fixed.

**Comment by toolowner** [comment]
@thijstriemstra Files for the Split Wave Point plugin still in #1048 
It is used for rendering data points following timeline, you can check the demo on http://www.jrweth.com/wavesurfer2/example/split-wave-point-plot/

I have been looking for something similar to #1255 that @DrLongGhost hasn't finished it yet. This one can also help to solve #269.

I really miss the Split Wave Point :cry:

**Comment by thijstriemstra** [comment]
@toolowner can you open a pull request with the missing files?

**Comment by toolowner** [comment]
Yes, I could, but the problem is that the plugin was written in es5, it doesn't appear compatible with version 2.

**Comment by thijstriemstra** [comment]
rewriting it shouldn't be too hard? how many lines is it

**Comment by toolowner** [comment]
The https://github.com/katspaugh/wavesurfer.js/blob/es5/src/drawer.split-wave-point-plot.js has more than 350 lines of code.

This is the place where it's called https://github.com/katspaugh/wavesurfer.js/blob/es5/example/split-wave-point-plot/app.js

**Comment by toolowner** [comment]
> rewriting it shouldn't be too hard?

@thijstriemstra I will do it. The rewrite will similar to the timeline and spectrogram plugin.

I don't have much experience on canvas nor the webaudio, so I hope you don't mind if I may ask some silly questions.

**Comment by Guarmanda** [comment]
Hello, we need this plugin too but the example on the website is still not working. I will try to make the old code working today but may abandon in some hours because my student project deadline is really soon.
