### ISSUE TITLE
Save wavesurfer state and preload on reload

### ISSUE THREAD

**Issue by oxmanroman** [wavesurfer-js/wavesurfer.js#1316]
### Wavesurfer.js version(s):
2.0.2

### Browser version(s):
Google Chrome
Version 63.0.3239.132 (Official Build) (64-bit)

### Problem
Hey there! I have a popup where I load an audio using the wavesurfer, the audio is about 20 minutes long so it takes some time for it to fully load.

I'm trying to achieve that when the wavesurfer finishes loading for the first time it saves the state so if you close the popup and open it back again it will just use the saved data.

I read all the documentation, issues and the code but I'm still not being able to achieve this even though it seems simple.

I suppose the code should be something like this, but actually the method "preload" doesn't exist and I don't find the way to **preload the OfflineAudioContext**

Any ideas?

```javascript
this.waveSurfer = WaveSurfer.create({
	container: $waveForm,
	waveColor: 'purple',
	renderer: 'MultiCanvas',
	height: 80
});

this.waveSurfer.on('ready', () => {
	window.savedWavesurfer = this.waveSurfer.WebAudio.getOfflineAudioContext();
});

if (window.savedWavesurfer) {
	this.waveSurfer.preload(window.savedWavesurfer);
} else {
	this.waveSurfer.load('//example.com/audio.mp3');
}
```

**Comment by thijstriemstra** [comment]
I think you probably want to save the 'peaks data' and load that the 2nd time..

**Comment by oxmanroman** [comment]
Thanks for the quick response!

Actually it was the first thing I tried, but when I asked for the peak after the ready event fired, it was returning an empty array.

This was my code:
```
this.waveSurfer.on('ready', () => {
	window.savedWavesurfer = this.waveSurfer.MediaElement.getPeaks();
});
```

Would it help if I make a jsFiddle?

**Comment by thijstriemstra** [comment]
what about the `wave-ready` event?

**Comment by oxmanroman** [comment]
That event doesn't trigger as I'm using webaudio. I read in the documentation that:

`waveform-ready` – Fires after the waveform is drawn when using the MediaElement backend. If you're using the WebAudio backend, you can use `ready`.

**Comment by thijstriemstra** [comment]
It could be the same issue as #1311. I don't use peaks data, and not sure what the issue is, maybe you can take a look.

**Comment by oxmanroman** [comment]
I saw that same issue because of this but actually upgrading didn't solve my problem.

Sorry I took some time to answer, I created a simple [codepen](https://codepen.io/oxmanroman/pen/wywzRo?editors=1010#0) to show the problem.

Here it goes, thanks a lot!

**Comment by the1the** [comment]
Did you manage to fix it?

**Comment by oxmanroman** [comment]
Hey there! Thanks for the follow up. Finally I solved by keeping the popup alive all the time but hide when the user closes it. That way I don't need to be deleting and creating again the wavesurfer.

**Comment by meteorplus** [comment]
this is still a big issue!!

**Comment by meteorplus** [comment]
you must give all three parameters or it will return null

var length = 300;
var start = 0;
var end = 300;

wavesurfer.backend.getPeaks(length, start, end);

**Comment by entonbiba** [comment]
@oxmanroman why don't you use window.sessionStorage instead and just load it from there? Even better use window.localStorage so when the user closes and opens the browser again it remembers.
