### ISSUE TITLE
How to get current value of the height of bars? 

### ISSUE THREAD

**Issue by nkli** [wavesurfer-js/wavesurfer.js#1324]
something like this.
![image](https://user-images.githubusercontent.com/8384584/36082900-8a51f89e-0fe8-11e8-91fa-c3b79ef7dcb4.png)

![image](https://user-images.githubusercontent.com/8384584/36082945-f289ac36-0fe8-11e8-9454-5469e6063999.png)

current value is undefined.

**Comment by thijstriemstra** [comment]
@nkli what is current value in this screenshot?

**Comment by nkli** [comment]
The value of the wave column when the current time passes.

**Comment by katspaugh** [comment]
The peaks are always numbers (floats). It looks like you're transforming or outputting them wrong.

<img width="255" alt="screen shot 2018-04-23 at 12 12 32" src="https://user-images.githubusercontent.com/381895/39120752-aafe2110-46ef-11e8-9b8b-520398ce89f2.png">
