### ISSUE TITLE
Tiled Renderer

### ISSUE THREAD

**Issue by jamiefaye** [wavesurfer-js/wavesurfer.js#1332]
I have started working on a 'tiled renderer' that can zoom down to the sample level without needing an absurd number of canvas objects.

The idea is to juggle a limited amount of canvases inside the wrapper element based on the scroll position. If the time to optimistically fill a canvas starts bogging down the animation loop, I may turn the drawWave/drawBars/drawLine stuff to use a generator function that images a chunk at a time.

I will let everyone know if it actually works!

**Comment by thijstriemstra** [comment]
sounds great, let us know how it goes.

**Comment by jamiefaye** [comment]
I have the tile renderer most of the way working. You can find the current state of that over on my Downrush github project. At the moment, Downrush does not use Webpack, so it is a definite hack. https://github.com/jamiefaye/downrush/blob/master/DR/waverly/jffRenderer.js. After I get Webpack going I will update (and ponder doing a pull request).

**Comment by jamiefaye** [comment]
I made a PR for the tiled renderer. I don't expect it to be accepted right away, if ever. It does let you zoom down to the sample level while supporting relatively long songs.
