### ISSUE TITLE
Memory leak when opening files in playlist example

### ISSUE THREAD

**Issue by g-serg** [wavesurfer-js/wavesurfer.js#1347]
### Wavesurfer.js version(s):
2.0.5

### Browser version(s):
Chrome 64.0.3282.140 (Official Build) (64-bit)

### Code needed to reproduce the issue:

1. git clone https://github.com/katspaugh/wavesurfer.js.git

2. npm install

3. npm run build

3. npm run start

4. open http://localhost:8080/example/playlist/

5. open Chrome Task Manager

5. see column "Memory" (screenshot-1)
Memory footprint = 38k
Memory = 26k

![1](https://user-images.githubusercontent.com/15379875/37101143-e7ede8aa-2235-11e8-8070-e73a1cd1bf56.png)

6. switch sounds for the list 50 times

7. see column "Memory" (screenshot-2)
Memory footprint = 523k
Memory = 509k

![2](https://user-images.githubusercontent.com/15379875/37101144-e8128de0-2235-11e8-9c3d-aa149dc1484e.png)

**Comment by thijstriemstra** [comment]
@g-serg this is happening to playlist example only I assume?

**Comment by g-serg** [comment]
Memory leaks out for each new call
`wavesurfer.load(url)`

**Comment by thijstriemstra** [comment]
@g-serg what operating system? can you reproduce it in Firefox?

**Comment by g-serg** [comment]
> what operating system?

Windows 7 Ultimate sp1

> can you reproduce it in Firefox?

Checked into the firefox. Leaks does not reproduce, everything is OK
