### ISSUE TITLE
Browser crashes

### ISSUE THREAD

**Issue by 213zhaoqi** [wavesurfer-js/wavesurfer.js#1348]
If the audio is too large, the browser will crash.
![image](https://user-images.githubusercontent.com/23122895/37196828-3c327858-23b3-11e8-9081-2a7c3144b05e.png)
audio size is 775MB,audio length is 70 minutes, format is wav
Is this problem related to computer configuration or browser?

**Comment by thijstriemstra** [comment]
It's a known browser issue.

**Comment by 213zhaoqi** [comment]
Is there any way to solve it?restricting specific computer configurations or browser restrictions?
my current solution is to cut too long audio into several small pieces of audio,
but I don't think this is a good solution.
so can you give me some suggestions for solving it?
thank you very much.

**Comment by thijstriemstra** [comment]
What version of wavesurfer are you using?

**Comment by katspaugh** [comment]
In 2018, maybe we can look at this issue again. A quick google search yielded this interesting gist: https://gist.github.com/revolunet/e620e2c532b7144c62768a36b8b96da2

**Comment by entonbiba** [comment]
@213zhaoqi you can get the wav data json file from this api I created and use backend: "MediaElement" while showing the full waveform.

I'll be increasing the upload size soon, it's currently set to 20 MB as I'm waiting for users to test it. #1183 
https://waveform.al
