### ISSUE TITLE
Record audio context output?

### ISSUE THREAD

**Issue by heyaphra** [wavesurfer-js/wavesurfer.js#1355]
This might be a more general WebAudio question, but I have not been able to find answers anywhere and I'm hoping to glean some knowledge from those more experienced.

I am using multiple WaveSurfers with the region plugin to load samples in a digital instrument. Is there a way to record and save sounds being played in real time within a single AudioContext? So far I have only been able to capture external input from the microphone.

Edit: I was thinking of using the MediaElement fallback and the captureStream() API, however the MediaElement seems to throw an error unfortunately, reading that it cannot querySelector of undefined.

Many thanks!

**Comment by GitHubRakeshSharma** [comment]
There are several Solutions to this using OfflineAudioContexts. Just have a look there

**Comment by thijstriemstra** [comment]
> however the MediaElement seems to throw an error unfortunately, 

What error?

**Comment by bloom510** [comment]
MediaElement fall back is leaving the following error when set at initialization:
Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at t.value (wavesurfer.min.js:6)
    at t.value (wavesurfer.min.js:6)
    at wavesurfer.min.js:6
    at wavesurfer.min.js:6
    at OfflineAudioContext.<anonymous> (wavesurfer.min.js:6)``

Here's a quick update: I'm able to record by creating a buffer source, connecting it to the AudioContext destination,  and connecting it to a MediaStreamDestination. But I can only do this for each individual WaveSurfer, and when I try to do this with the global AudioContext the WaveSurfers are latching on to, it returns no sound into the stream. Would be grateful for any pointers for recording all global context outputs.
     ```
 //buffer source node passed to media stream
       this.bufferSource = this.wavesurfer.backend.ac.createBufferSource();
       this.bufferSource.buffer = this.wavesurfer.backend.buffer;
       this.bufferSource.connect(this.wavesurfer.backend.ac.destination);
```

**Comment by thijstriemstra** [comment]
I use it in conjunction with RecordRTC.js in the https://github.com/collab-project/videojs-record plugin to record audio, see https://collab-project.github.io/videojs-record/examples/audio-only.html. Maybe these projects can provide some pointers.

**Comment by bloom510** [comment]
I figured out that I needed to merge each WaveSurfer buffer, but this is only a preliminary step in the right direction. I now have a new question: Is there a way to get realtime PCM data of waveform regions as they're played using the exportPCM() method? I am aiming to get PCM data of samples played in real time, and merging each buffer into one.

**Comment by GitHubRakeshSharma** [comment]
You can always get the PCM data via XMLHTTPReq. Configure your response to be of type ArrayBuffer. Then you can calculate the byte range you need.

**Comment by mattbbc** [comment]
@spidercatnat Did you ever figure this out?
