### ISSUE TITLE
Same song in two containers?

### ISSUE THREAD

**Issue by MrHimiko** [wavesurfer-js/wavesurfer.js#1369]
Is there a posiblity to use one song in two different containers?

       var wavesurfer = WaveSurfer.create({
	    **container: '#waveform' AND '#waveformMobile',  <<<< THIS**
	    waveColor: '#bcbcbc',
	    progressColor: 'grey',
	    height: 60,
	    barWidth: 2,
	    maxCanvasWidth: 220
	});

I tried doing it with class and giving that name to two classes and doesnt work.. 
Thanks

**Comment by thijstriemstra** [comment]
@MrHimiko you can create 2 players. I would preload the audio somehow and once that's done launch 2 players?

**Comment by kirilkirkov** [comment]
@MrHimiko Do you find solution here? I want to create one player with two waves. One in home page playlist one in footer when click play on some of them? :) 
@thijstriemstra 
![screenshot from 2018-10-22 14-16-14](https://user-images.githubusercontent.com/3421328/47289810-23e21600-d605-11e8-8c5a-5249f50bd74f.png)
