### ISSUE TITLE
Immediate Playback using WebAudio Backend

### ISSUE THREAD

**Issue by lorenzfischer** [wavesurfer-js/wavesurfer.js#1382]
### Wavesurfer.js version(s):
2.0.5

### Browser version(s):
Chrome Mac 66.0.3359.181 (Official Build) (64-bit)

### Description of the Issue:
When loading a large audio file (20mb+) using the default `WebAudio` backend, the playback can only begin after the whole audio file has been downloaded. When using the `MediaElement` backend, the playback is immediate, however, the timing information returned by `wavesurfer.getCurrentTime()` is imprecise, for long audio files (45min +) the offset is up to a few seconds. Four our purposes, an application that synchronizes text with the audio being played back, we need immediate playback, but precise timing information. 

**How can we achieve this? Any help would be greatly appreciated!**

### What we have tried:
* we have precomputed the peaks files and load them with `wavesurfer.load('audioFiles/' + this.props.recordId, peaksData);`. This does not change the problem that we have to wait until the whole file has finished downloading until the playback can begin.
* we tried to correct the offsets by reading the timing information directly out of `wavesurfer.backend.media.currentTime` in case `wavesurfer.backend.params.backend=='MediaElement'`. This did not work, consistently. I.e. sometimes the timings were close to the true values, most of the times, they were off quite a bit.
* loading a small version of the audio initially, only to replace it with the full version of the audio file by calling `wavesurfer.load(url_to_large_file)` immediately after calling `wavesurfer.load(url_to_small_file)`. This did not work, as the second call to `wavesurfer.load()` aborts the playback of the small file.
* same as above, but this time by downloading the audio using ajax, before trying to load it with `wavesurfer.loadBlob()`. Sadly, loadBlob() did not read the audio data we provided and resulted in the error message: `Uncaught (in promise) DOMException: Unable to decode audio data` (code below)

```
         loadInBackground(jsroutes.controllers.SpeechFileController.getAudioFile(this.props.callId))
            .done( (data, result, response) => {
                //console.log(this.state.wavesurfer);
                let blob = new ArrayBuffer(data);
                this.state.wavesurfer.loadArrayBuffer(blob);
            })
            .fail( (response) => {
                console.log("problem loading audio file:", response);
            })
```

What we're looking to try next:
* try to down sample the mp3 we need to load, with the side effect of having lower quality audio in our application.

**Comment by TrevorHinesley** [comment]
Is the `wavesurfer.getCurrentTime()` returning the wrong time, or is the playhead on the waveform at the wrong spot? I'm building something that needs to work with long files (up to a couple hours) as well, so both of these things are really important.

In other words, is the time being returned by `wavesurfer.getCurrentTime()` actually changing at a rate that's not consistent with the specified playback rate, or is the waveform visualization just not lining up with what you're hearing?
