### ISSUE TITLE
jwplayer integration

### ISSUE THREAD

**Issue by lauradP** [wavesurfer-js/wavesurfer.js#1391]
Hi, 
is there any chance of integrating wavesurfer (along with videojs-wavesurfer plugin) with jwplayer?

Thanks,
Laura

**Comment by Asile984** [comment]
Hi,

I'm interested in JwPlayer integration too.
I'd like to use wavesurfer to show the waveform referred to the audio track of a video played in JWPlayer.
Is there a way to synchronize audio track and video?

Thanks a lot,
Asile

**Comment by thijstriemstra** [comment]
@Asile984 you can use a `video` element instead of `audio` to achieve that.
