### ISSUE TITLE
Accuracy of saved waveform

### ISSUE THREAD

**Issue by peerfischer** [wavesurfer-js/wavesurfer.js#1405]
Hello,

I'm saving the peaks as JSON - 

```javascript

wavesurfer.on('waveform-ready', function () {
            container.children('.loader').css('width', '0%');
            container.css('background-image', 'none');

            // cache Waveform
            var length = 500;
            var start = 0;
            var end = 500;

            // save Peaks if not exist
            if (!peaks) {

              // save Peaks
              // savePeaks(fileId, wavesurfer.backend.getPeaks(length, start, end));

              // PCM
              var pcmData = wavesurfer.exportPCM(length, 4000, true, start);
              savePeaks(fileId, JSON.parse(pcmData));

            }

          });
```

Unfortunately the saved waveform is not as accurate as the one which is generated on the fly -
look here:

https://imgur.com/a/RyBVtsS

How ca this be fixed ? There seems to be no parameter ?

### Wavesurfer.js version(s):
wavesurfer.js 2.0.5

### Browser version(s):
all

**Comment by awenger63** [comment]
Hi @peerfischer , 
the code in ExportPCM contain this line : 
`accuracy = accuracy || 10000`
`var arr = [].map.call(peaks, function (val) {
                return Math.round(val * accuracy) / accuracy;
            });`
You must more increase your accuracy value, peaks sometime contain value with a lot of decimal. 

Or perhaps make a new PR to no apply it when it's egal 0 (div 0 is not tested) ?
I hope this can help you

**Comment by peerfischer** [comment]
Hello, thanks for thisn hint ! Unfortunately I can set the accurany parameter to any value - it doesnt change anything. I tried values from 10000 - 200000 ?

**Comment by awenger63** [comment]
OK but peaks value look like 0.24094337224960327
with 200000 you have 0.240945
No great difference, but if all value are similar you lots some accurancy. Please, try with 100000000000000000 ! and tell us

**Comment by peerfischer** [comment]
Hello,

even this setting seems to change nothing - the saved waveform is much less accurate and differs from the inital one. Peal values in JSON seem to be correct like "-0.06634521484375" - perhaps there are some values missing?

**Comment by peerfischer** [comment]
I count round about 480 peak values for a track of 1 minute...

**Comment by awenger63** [comment]
Yes perhaps, use the same length to check. See on 'drawBuffer' function witch width is use.

**Comment by pmichaelis** [comment]
wavesurfer.on('waveform-ready', function () {

        var length = 500;
        var start = 0;
        var end = 500;

        var nominalWidth = Math.round(wavesurfer.getDuration() * wavesurfer.params.minPxPerSec * wavesurfer.params.pixelRatio);

        var pcmData = [wavesurfer.exportPCM(nominalWidth,](url) 100000000000000000, true, start);
        savePeaks(fileId, JSON.parse(pcmData));

    });


If your save the peaks with the setup from the drawbuffer function ("nominalWidth"), the cached Waveform doesn't fit into the canvas. It is longer than the waveform on the initial loading.

If I save with a fixed lenght value of 500, the cached Waveform fits in, but looks different from the initial loading.

![image](https://user-images.githubusercontent.com/5164671/42308665-8bb90f88-8036-11e8-8d45-a8600d33f9ab.png)

Is it possible to adjust the settings in order that the waveforms look the same?

**Comment by awenger63** [comment]
@pmichaelis , @peerfischer 
You have right, ExportPCM don't get the same peaks of the load process without peaks.

To have the same wave, with the same peaks, call the getPeaks function on the backend like this 

`var pcmData = '[' + wavesurfer.backend.getPeaks(500, 0, 500) + ']';`

It's seem to work for me.
Could you test it ?

**Comment by pmichaelis** [comment]
Hey, thanks for the quick reply. 
I was testing with getPeaks before, but couldn't optimize. The save mechanism seems to work, but still there a huge visual differences:

![image](https://user-images.githubusercontent.com/5164671/42460889-6090ce4c-839f-11e8-92f2-cbb82d1c687d.png)

**Comment by awenger63** [comment]
@pmichaelis , can you post your code create wave part with your parameters ?

**Comment by pmichaelis** [comment]
Hey, thanks!

This is the way I am saving the waveform. I inserted the "getPeaks Advice" form you, yesterday.

// wavesurfer waveform ready
wavesurfer.on('waveform-ready', function () {
    container.children('.loader').css('width', '0%');
    container.css('background-image', 'none');

    // cache Waveform
    var length = 500;
    var start = 0;
    var end = 500;

    var nominalWidth = Math.round(wavesurfer.getDuration() * wavesurfer.params.minPxPerSec * wavesurfer.params.pixelRatio);

    // save Peaks if not exist
    if (!peaks) {

        // PCM
        // exportPCM(length, accuracy, noWindow, start)
        // var pcmData = wavesurfer.exportPCM(length, 100000000000000000, true, start);
        var pcmData = '[' + wavesurfer.backend.getPeaks(500, 0, 500) + ']';
        savePeaks(fileId, JSON.parse(pcmData));

    }

});

**Comment by awenger63** [comment]
Yes, but the `wavesurfer = WaveSurfer.create( ......)`

**Comment by pmichaelis** [comment]
Ah, ok,

    wavesurfer = WaveSurfer.create({
        container: '#' + dataId,
        waveColor: '#3aa3d9',
        progressColor: '#3aa3d9',
        hideScrollbar: true,
        backend: 'MediaElement',
        fillParent: true,
        scrollParent: false
    });

**Comment by awenger63** [comment]
Sorry, I don't have any more idea. Can you check if your lenght = your dataId container.width = end ?

**Comment by pmichaelis** [comment]
Ok, thanks for your help so far. I'll check on that. I think this might be a good hint.

**Comment by awenger63** [comment]
It's not an accuracy issue, but it's a number of peaks issue that you need to resolve the size for your visual difference.
If you really want the same visual aspect, you need to have same width and same number of peaks (813 in your case I suppose). Otherwise, I thinks you need to use pixelRatio to drawn all peaks generate on the render wave picture. 
It seem difficult to have always same visual aspect on responsive screen where width can change ! The only way can be to have a screenshot, than it's look like a wavesurfer but it's not a wavesurfer ....
I hope you'll can find a solution.

**Comment by webaschtl** [comment]
Hmm, having the same problem – in the year 2020 ;-)

![image](https://user-images.githubusercontent.com/1423232/76709170-cf10d500-66fc-11ea-8230-cf2ddffb1e8a.png)

Therefore _exportPCM_ still works not as it should be?!
Or do you found a solution, @peerfischer?

Thanks a lot – two years after...

**Comment by Pkmmte** [comment]
Year 2021 here. Still looking for a solution...

**Comment by jgentes** [comment]
I was able to address this by adjusting the length parameter.

If you use `scrollParent: true`, the length of the array likely needs to be much larger than `1024`.

This worked for me: 
```js
const pcm = await wavesurfer.exportPCM(wavesurfer.drawer.width, 10000, true, 0)
```
