### ISSUE TITLE
Loading frequencies data into spectrogram plugin

### ISSUE THREAD

**Issue by cameron-henkel** [wavesurfer-js/wavesurfer.js#1407]
The spectrogram plugin has a frequenciesDataUrl parameter that seems to be used by loadFrequenciesData(url) to pull frequency data from a JSON file and draw to canvas. Is there any documentation on how to use this parameter or what format it expects the data to be in? Generating spectrograms when loaded can take upwards of 10 seconds for a simple 2 minute mp3 and being able to preprocess and load that data would really help speed up my application. Is there a recommended 3rd party utility to do this?

**Comment by Stoyvo** [comment]
@cameron-henkel  have you had any luck with this?

**Comment by thijstriemstra** [comment]
Can you log the frequency data after loading audio file to figure out the data format?

**Comment by cameron-henkel** [comment]
@Stoyvo I never got it working, and ended up manually saving the spectrograms as images and then messing with HTML formatting to place them beneath the wavesurfer player for my project. I did attempt to log the data but that was taking too long for my project's time-frame.

**Comment by oaeide** [comment]
I too am curious about this...

**Comment by thijstriemstra** [comment]
cc @shershey

**Comment by Iquebal** [comment]
Hi,

Spectrogram fails to load long data approx. 10 min mp3 file. Spectrogram become unresponsive. It's okay for 2, 3 minutes duration.

---
Thanks,
Iquebal

**Comment by thijstriemstra** [comment]
@Iquebal what version of wavesurfer.js?

**Comment by Iquebal** [comment]
Hi,

I am using wavesurfer.js 4.4.0.

**Comment by Iquebal** [comment]
Hi Thijstriemstr,

The issue has been resolved but the problem is on first time spectrogram is not loading and when I replay video its working properly can you please guide us .

Thanks& regards
Iquebal

**Comment by Iquebal** [comment]
Hi,

I am using spectrogram plugin 4.4.0

**Comment by thijstriemstra** [comment]
> The issue has been resolved but the problem is on first time spectrogram is not loading and when I replay video its working properly can you please guide us .

You should open a new ticket and post code.
