### ISSUE TITLE
Get last peak in region

### ISSUE THREAD

**Issue by swampthang** [wavesurfer-js/wavesurfer.js#1427]
### Wavesurfer.js version(s):
2.0.6

### Browser version(s):
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

### Code needed to reproduce the issue:
Not a bug, might be a feature request.
(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:
I'm using the Regions plugin and want to know if there is a way to find the last tallest peak in a region. Given this waveform screenshot, is there a way to figure this out? I couldn't find any in-depth documents on getPeaks(). Are the parameters in samples or seconds?

![screen shot 2018-08-16 at 4 34 48 pm](https://user-images.githubusercontent.com/428757/44236457-ad431b00-a172-11e8-8cd7-c3a96cd77890.png)

Was thinking it would be in seconds but thinking maybe not. I ran this on the above example...
```
backend.getPeaks(4.63636363636364, 28.36363636363636, 33);
```
and got this...
![screen shot 2018-08-16 at 4 42 49 pm](https://user-images.githubusercontent.com/428757/44236695-791c2a00-a173-11e8-8ee7-6396b0b56487.png)

Not sure what I'm looking at there. Appreciate any help understanding this or referring me to documentation that explains it. Thanks for a wonderful library!

**Comment by swampthang** [comment]
Just found this.
https://wavesurfer-js.org/doc/class/src/mediaelement.js~MediaElement.html#instance-method-getPeaks
Looks like it is samples. The question I have is how to find the location in seconds of the highest peak.

**Comment by swampthang** [comment]
It seems length (the first parameter) is referring to pixel width but the start and end params are samples. So, I'm using this but it doesn't seem to accurately represent what I'm seeing. Can someone please explain what is going on? Here's my code...
```
let start = ws.regions.list[dir].start;
let end = ws.regions.list[dir].end;
let pxs = ws.params.minPxPerSec;
let peaks = ws.backend.getPeaks((end-start)*pxs,start*pxs,end*pxs);
```
This is the rendered waveform with the region having been dragged and resized...
![screen shot 2018-08-17 at 9 48 37 am](https://user-images.githubusercontent.com/428757/44272980-d8c21600-a203-11e8-9950-06348d9afa68.png)
Below is the resulting array. The first 2 array items are 178.313xx and after the 2nd item, it jumps to 7019.68xx and increments from there with each item being == 0.
Can anyone tell me what this represents and what is wrong with my code? 

![screen shot 2018-08-17 at 9 55 58 am](https://user-images.githubusercontent.com/428757/44273144-39e9e980-a204-11e8-9273-972b8c370bec.png)

**Comment by swampthang** [comment]
One of the things that I didn't think about is that the waveform is zoomed and scrolling is enabled. I'm using this code now but still getting similar results, just different values.
```
let start = 29.25; // seconds
let end = 30; // seconds
let pxs = ws.params.minPxPerSec; // 120
let pxRt = ws.params.pixelRatio; // 1
let wd = ws.drawer.width; // gets the full width of the drawer inside the scrollable div - 3927px

let startSample = start*pxs; // 3510
let endSample = end*pxs; // 3600
let peaks = ws.backend.getPeaks(wd,startSample,endSample);
console.log(peaks);
```
Getting the following (can't fit it all on in the screenshot) - again, can anyone explain what these array values are? Thanks...
![screen shot 2018-08-17 at 12 58 04 pm](https://user-images.githubusercontent.com/428757/44281392-3dd63580-a21d-11e8-8f1c-15442c809150.png)

**Comment by thijstriemstra** [comment]
> Just found this.
https://wavesurfer-js.org/doc/class/src/mediaelement.js~MediaElement.html#instance-method-getPeaks

@katspaugh never saw these pages, is it outdated?

**Comment by katspaugh** [comment]
These docs are supposed to be up to date. They are [generated](https://github.com/katspaugh/wavesurfer.js/blob/master/.travis.yml#L19) on each build, added in #992.
