### ISSUE TITLE
Progress background color

### ISSUE THREAD

**Issue by ghost** [wavesurfer-js/wavesurfer.js#1444]
Hello,

I found out this library doesn't have an option to change background color of progressed portion.
It allows you change color of progressed waveform's bars.. but not its background color.
Is there any way to change background color of progressed portion of a track? 
This feature is very important!

Thanks,

**Comment by thijstriemstra** [comment]
@jamesharvey2 can you add a screenshot of what you exactly mean, to clarify?

**Comment by jamesharvey2** [comment]
@thijstriemstra 

Thanks for your attention.

Please check this example waveform player.

http://nulloy.com/files/screen_2.png

This waveform player changes background color of waveform along with color of waveform as track progresses. 
Its background has changed into blue along with the waveform.

But wavesurfer.js doesn't allow you to change background color of a player. It allows you to change color of waveform but not its background.

Is there any way you guys can add background color option for progressed portion of track? 

Thanks,

**Comment by maragonov** [comment]
How use backgtound-image??

**Comment by tae100k** [comment]
Having same problem!

**Comment by tae100k** [comment]
I just realized that you can change progress background color by CSS
```
  * > wave {
    background-color: ${purple_10};
  }
  ```
  just do this!
