### ISSUE TITLE
Accuracy issue when playing a WaveSurfer region

### ISSUE THREAD

**Issue by virtualflo** [wavesurfer-js/wavesurfer.js#1453]
# Accuracy issue when playing a WaveSurfer region

Hi,

I'm having accuracy issues when attempting to _play the wave during a specific duration_

I'm editing a webapp designed to edit subtitles for videos. I'm using React/Redux with Wavesurfer and `regions` to display audio regions on a canvas on which the waveform is drawn. The wave is rendered via a React Component whose props exclusively come from Redux state and actions.
I'm trying to implement a feature allowing the user to play the wave on a region's duration, _i.e._ from a `region.start` time to a `region.end` time.

To do so, I am basically setting the wave's current time to the starting time, then playing the wave while setting a timeout duration equal to the region's duration, before pausing the wave.

The problem is, it seems the wave does not pause systematically at the exact time I want. Assuming I want to play the part corresponding to the moment a video's protagonist says `Hello World` from the sentence `Hello World what's up`, I'm going to hear `Hello Worl...` of `Hello World wh...` from time to time when playing this part repeatedly.

All of this is summarized in the JS function below :

```js
import hrtime from 'browser-process-hrtime';
import NanoTimer from 'nanotimer';
import {
  setTime,
  play,
  pause,
  updateTranscript,
} from '../actions';

// [...]

function playRange(start, duration, activeCueId, resetTime) {
  return (dispatch, getState) => {
    // [...]
    // Here I am setting the start time into Redux Store,
    // which in turns sets the current time of the wave
    // this wave being rendered by a React Component taking
    // the redux store `start` attribute as a prop
    dispatch(setTime(start));

    window.playRangeTimer = new NanoTimer();

    // Here I'm setting the wave's playing attribute to true via the redux store
    dispatch(play());

    // Last but not least,
    // I'm setting a timeout with a duration equal to the region's duration
    // before pausing the wave via an action dispatch to the Redux Store - again
    const countDown = (duration * 1000).toFixed(2) + 'm';
    window.playRangeTimer.setTimeout(
      () => {
        dispatch(pause());
        dispatch(setActiveCue(cue));
        dispatch(setTime(Number(parseFloat(start + duration).toFixed(2))));
        dispatch(setTime(resetTime));
      },
      '',
      countDown,
    );

    return window.playRangeTimer;
  };
}
```

### Resources
- Frontend: React.js / Redux
- Wavesurfer.js version(s): Wavesurfer 2.0.5 and react-wavesurfer 0.8.6.
- Browser: Chrome Version 68.0.3440.106 (64 bits)

### Notes
- I've been trying to reduce the level of inaccuracy on multiple levels : 
  - I've made sure the computation of the `start` and `end` time return accurate values when adding float numbers to one another, by rounding the result to the 2nd decimal
  - I've replaced the classic `setTimeout`, which seems to [present accuracy issues](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Notes),  with a [supposedly more accurate timer](https://github.com/Krb686/nanotimer)
- Is dispatching a Redux action a possible cause of delay in the code execution?
- Would the browser's performance be an issue as well?
- Would the video's FPS impact the accuracy as well ? And by extension, would the [browser be an issue](https://stackoverflow.com/a/28455790/6334047) on that matter? 
- Possibly related to https://github.com/katspaugh/wavesurfer.js/issues/379 ?

**Comment by thijstriemstra** [comment]
> Wavesurfer.js version(s): Wavesurfer 2.0.5

why not use latest (2.0.6) or try master.

**Comment by virtualflo** [comment]
thanks @thijstriemstra we will give a try with 2.0.6

**Comment by virtualflo** [comment]
We tried to update wavesurfer with the 2.0.6 versin but didn't solve our problem. We don't know what to try next :-/ Any advice ?

**Comment by thijstriemstra** [comment]
> I've replaced the classic setTimeout, which seems to present accuracy issues, with a supposedly more accurate timer

@virtualflo, what about #1007?

or #1281?

**Comment by virtualflo** [comment]
@thijstriemstra thank you for your help.
We didn't have the time to solve this problem for the last weeks but we should make some test this week.
For information we are using the Region plugin.

**Comment by thijstriemstra** [comment]
some accuracy adjustments to regions plugin will be included in v3.1.0

**Comment by virtualflo** [comment]
@thijstriemstra great news! Thanks for the update. When do you plan to deploy the v3.1.0?

**Comment by thijstriemstra** [comment]
@virtualflo see #1751

**Comment by cazdlt** [comment]
Hello, I am having a similar issue. Has anything been found on this?

**Comment by cazdlt** [comment]
I am guessing this might be related to the following lines on wavesurfer.js/src/plugin/regions/region.js

I am not sure why time is being rounded to tens of a second. This is causing issues when working with audio at 1s or 2s length.

![imagen](https://user-images.githubusercontent.com/18340047/107129273-4bbb1d80-6892-11eb-9c54-3c3775adaaea.png)
