### ISSUE TITLE
Pre-rendering peaks with on the server

### ISSUE THREAD

**Issue by IrosTheBeggar** [wavesurfer-js/wavesurfer.js#1466]
I'm working on a soundcloud like app where the user will see a playlist full of waveforms.  I want to render all the peak data on the server to avoid having the user load all the songs at once just to display the waveforms.

I looked through the docs and the issues, and I saw several libraries that might help, but they all had lots of dependencies or didn't work on windows (which unfortunately is a requirement for this app).  Is there a pure NodeJS solution for rendering peaks server side?

**Comment by SalvadorDuran** [comment]
I'm using exportPCM with electron. Something like this:

```
    let Player = WaveSurfer.create({
      container: document.createElement('div'),
      preload: true
    })
    let buffer = fs.readFileSync(filename)
    let blob = new window.Blob([new Uint8Array(buffer)])
    Player.loadBlob(blob)
    Player.on('ready', () => {
      let pcm = Player.exportPCM(1024, 10000, true)
      // Do something with pcm
    }
```

**Comment by IrosTheBeggar** [comment]
@SalvadorDuran 

Is it possible to run electron on a headless server?
