### ISSUE TITLE
Save audio edited by wavesurfer equalizer example

### ISSUE THREAD

**Issue by romegab** [wavesurfer-js/wavesurfer.js#1514]
I've looked through the documentation as well as the issues, and can't see anywhere that talks about saving an audio edited by wavesurfer equalizer.

Is there currently a built-in way to do this?

What I'm looking for in the end is to:

load an wav
edit it with the equalizer
press a Save button and save the already edited wav file.

**Comment by wishazehra** [comment]
Hey did you ever solve this?

**Comment by erik-iglikov** [comment]
Same here, is there a solution to that?
