### ISSUE TITLE
record microphone example

### ISSUE THREAD

**Issue by davidtorroija** [wavesurfer-js/wavesurfer.js#1515]
Hey, please I just need a quick and basic working example to record microphone and save to file or buffer, but to show in the screen and play the recorded audio, the examples about this in wavesurfer does not show loading the recorded audio. Thanks!

**Comment by thijstriemstra** [comment]
See #1030

**Comment by nilesh121196** [comment]
Hi, Please check code snippet file.
check above mentioned ticket and just modify code there.

`
'use strict';

var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
var wavesurfer, context, processor;

// Init & load
document.addEventListener('DOMContentLoaded', function() {
    var micBtn = document.querySelector('#micBtn');

    micBtn.onclick = function() {
        if (wavesurfer === undefined) {
            if (isSafari) {
                // Safari 11 or newer automatically suspends new AudioContext's that aren't
                // created in response to a user-gesture, like a click or tap, so create one
                // here (inc. the script processor)
                var AudioContext =
                    window.AudioContext || window.webkitAudioContext;
                context = new AudioContext();
                processor = context.createScriptProcessor(1024, 1, 1);
            }

            // Init wavesurfer
            wavesurfer = WaveSurfer.create({
                container: '#waveform',
                waveColor: 'black',
                interact: false,
                cursorWidth: 0,
                audioContext: context || null,
                audioScriptProcessor: processor || null,
                plugins: [
                    WaveSurfer.microphone.create({
                        bufferSize: 4096,
                        numberOfInputChannels: 1,
                        numberOfOutputChannels: 1,
                        constraints: {
                            video: false,
                            audio: true
                        }
                    })
                ]
            });
            const mediaRecorder;
            const audioChunks = [];
            
            wavesurfer.microphone.on('deviceReady', function(stream) {
                console.info('Device ready!');

                mediaRecorder = new MediaRecorder(stream);
                mediaRecorder.start();
                mediaRecorder.addEventListener('dataavailable', event=>{
                    audioChunks.push(event.data);              
                })

                mediaRecorder.addEventListener("stop", () => {
                    const audioBlob = new Blob(audioChunks);
                    const audioUrl = URL.createObjectURL(audioBlob);
                    const audio = new Audio(audioUrl);
                    audio.play();
                });
            });
            wavesurfer.microphone.on('deviceError', function(code) {
                console.warn('Device error: ' + code);
            });
            wavesurfer.on('error', function(e) {
                console.warn(e);
            });
            wavesurfer.microphone.start();
        } else {
            // start/stop mic on button click
            if (wavesurfer.microphone.active) {
                wavesurfer.microphone.stop();
                mediaRecorder.stop()
            } else {
                wavesurfer.microphone.start();
            }
        }
    };
});

`

**Comment by vinikatyal** [comment]
@nilesh121196 do u have a full working example?

**Comment by usbme** [comment]
Would also like a full working version
