### ISSUE TITLE
Matching zoom level with pre-generated peaks.

### ISSUE THREAD

**Issue by TheFrankman** [wavesurfer-js/wavesurfer.js#1520]
Hello There, 

First of all, thanks for wavesurfer.

I'm having a slight issue with pregenerated peaks. I like the default zoom level and display when loading a waveform without pre-generated peaks. However, when passing a peaks.json file into the player, I'm struggling to match the zoom and pixels per second measurement.

To generate the peaks I am using bbc's audiowaveform as suggested in the docs. I am passing the the parameters `--pixels-per-second 10 -b 8` I have played around with these values but can't even get close.

Without pre-generated peaks : 
![screenshot 2018-12-03 at 09 55 49](https://user-images.githubusercontent.com/1402017/49366673-cea82280-f6e1-11e8-8227-091df255d53d.png)

With pre-generated peaks : 
![screenshot 2018-12-03 at 09 56 11](https://user-images.githubusercontent.com/1402017/49366660-c5b75100-f6e1-11e8-9ef6-21983cf140b5.png)

### Wavesurfer.js version(s):
^2.0.5

### Browser version(s):
Chrome latest

### Code needed to reproduce the issue:
Generate waveform : 

```
audiowaveform -i /input/path/file.mp3 -o /output/path/file.json --pixels-per-second 10 -b 8"; 
```
init the player with pregenerated peaks if exists, otherwise continue as usual
```
let playerConfig = {
                    container: '#waveform-'+self.item.id,
                    waveColor: '#ba5248',
                    progressColor: '#bd2718',
                    normalize: true,
                    plugins: [
                        TimelinePlugin.create({
                            container: '#waveform-timeline'
                        })
                    ]
                }

                this.player = WaveSurfer.create(playerConfig);

                let waveformData = null;

                if (this.item.storage.waveform_path) {
                    let waveformResponse = await this.getJsonFromFile(this.item.storage.waveform_path);
                    if (waveformResponse) {
                        waveformData = waveformResponse;
                    }
                } else {
                    toastr.info("A waveform has not yet been created for this file. It may take longer to load.")
                }

                // If we have waveform data load it from here.
                if (waveformData) {
                    this.player.load(this.filePath, waveformData);
                    this.player.fireEvent('ready');
                    // Force player to present as ready
                    this.player.stop();
                } else {
                    this.player.load(this.filePath);
                }
```

**Comment by rafbc** [comment]
+1

**Comment by thijstriemstra** [comment]
You need to normalize the JSON peaks (between 0 and 1), using this Python script for example:

```console
python scale-peaks.py /path/file.json
```

```python
import json
import sys

if( len(sys.argv) < 2 ):
    print("Usage: python scale-json.py file.json")
    exit()

filename = sys.argv[1]

with open(filename, "r") as f:
    file_content = f.read()


json_content = json.loads(file_content)
data = json_content["data"]

max_val = float(max(data))
new_data = []
for x in data:
    new_data.append(x/max_val)

json_content["data"] = new_data
file_content = json.dumps(json_content)

with open(filename, "w") as f:
    f.write(file_content)
```

I also use `--pixels-per-second 20`. Does this help @TheFrankman

**Comment by TheFrankman** [comment]
@thijstriemstra 

Thanks for replying to this, and sorry it took me so long to get back. Sadly this makes no difference.

I have done what you have suggested above but in PHP 

```
$fileData = json_decode(file_get_contents($filePath));

$peaks = $fileData->data;

$maxPeak = max($peaks);

$newPeaks = [];

foreach ($peaks as $peak) {
    $newPeaks[] = $peak/$maxPeak;
}

$fileData->data = $newPeaks;

$json = json_encode($fileData);

file_put_contents($filePath, $json);
```

This is what it looks like if wavesurfer generates it as normal
![image](https://user-images.githubusercontent.com/1402017/56300100-390bad80-612d-11e9-95b2-e8416b5a3486.png)

This is what it looks like with normalised peaks at 20 pixels a second 
![image](https://user-images.githubusercontent.com/1402017/56300154-5476b880-612d-11e9-8970-d35e64addf5a.png)

Any thoughts ?

**Comment by thijstriemstra** [comment]
yea, the peaks need to be between -1 and 1.

**Comment by TheFrankman** [comment]
@thijstriemstra - so the peeks are all between -1 and 1 but still comes out nothing like how wavesurfer generates it if you don't pre-load the peaks. Seems the level of accuracy is the issue... I'm not sure.

**Comment by aburai** [comment]
@TheFrankman  I have the same problem when i start to use pre-generated peaks, it doesn't fit to the peaks generated by wavesurfer. But then i use audacity as reference for my peaks and it seems to fit to audiowaveform peaks. Maybe you can compare with audacity too and you feel better. ;)

**Comment by alexthegoodman** [comment]
@thijstriemstra and others concerned, I am not sure if my solution will work for you, but I am displaying my waveforms with a certain degree of post-processing. Because of this, generating the initial JSON with a pixels-per-second of a whopping 10000 has done the trick.

This may not be an accurate waveform, but it is visually appealing for my use-case.

**Comment by thijstriemstra** [comment]
> Because of this, generating the initial JSON with a pixels-per-second of a whopping 10000 has done the trick.

Good to hear. Have you tried such a high nr @TheFrankman?
