### ISSUE TITLE
Soundtouch with Equalizer

### ISSUE THREAD

**Issue by desafinadude** [wavesurfer-js/wavesurfer.js#1537]
Hi

I've successfully managed to implement both the soundtouch stretcher and the example equalizer, but, at the moment only have one or the other working, not both. For my project I would really need both to work together.

It seems the setFilter() method is cancelling eachother out. 

How can I chain the two?

Thanks in advance

D

**Comment by Martin-Alvarado-Void** [comment]
Hi, i dont know if this would answer your question but i had a similar issue, if you or others still have this issue then a little explenation:
i had the Equalizer node:
`
let EQ =[{},{},...];
let equalizerNode = EQ.map( function(band){...};
`
since its an array of essentially different nodes it does not play well with other filters unless you concatenate them all together before passing them with .setFilter():
`
let nonEQ = [stretcher, <MORE NODES>];
let filterNodes = equalizerNode.concat(nonEQ);
Wavesurfer.backend.setFilters( filterNodes );
`
So to avoid them cancelling out or overriding each other you must pass them all together just once with the setFilters() function instead of many setFilter() .

Hope you already got this and it helps others too.

**Comment by marizuccara** [comment]
I have a similar issue when i use filters to control volume of both channels, the panner filter and stretcher. Controls of channels volumes and panner works fine, but when i click on one of the stretcher controls, it works, but the other two filters don't work anymore. I tried different approaches, like disconnecting all filters, then connecting them again and setting them with stretcher node, but nothing. And when i print in the console wavesurfer.backend, it prints the filters with the value that they should assume, but nothing!

`   ........
    const splitter = wavesurfer.backend.ac.createChannelSplitter(2);
    const merger = wavesurfer.backend.ac.createChannelMerger(2);
    const leftGain = wavesurfer.backend.ac.createGain();
    const rightGain = wavesurfer.backend.ac.createGain();

    splitter.connect(leftGain, 0);
    leftGain.gain.value = 0.3;

    splitter.connect(rightGain, 1);
    rightGain.gain.value = 0.6;

    leftGain.connect(merger, 0, 0);
    rightGain.connect(merger, 0, 1);

    merger.connect(wavesurfer.panner);

    let sliderLeftVolume = document.querySelector('#sliderLeft');
    let sliderRightVolume = document.querySelector('[data-action="rightVolume"]');

    sliderRightVolume.addEventListener('input', function() {
        rightGain.gain.value = Number(sliderRightVolume.value);
    });

    sliderLeftVolume.addEventListener('input', function() {
        leftGain.gain.value = Number(sliderLeftVolume.value);
    });


    wavesurfer.backend.setFilters([splitter, leftGain, rightGain, merger, wavesurfer.panner]);

   ................
    wavesurfer.on('play', function() {
            //stretcher
            seekingPos = ~~(wavesurfer.backend.getPlayedPercents() * length);
            st.tempo = wavesurfer.getPlaybackRate();

            if (st.tempo === 1 ) {

            }
            else {
                if (!soundtouchNode) {
                    let filter = new window.soundtouch.SimpleFilter(source, st);
                    soundtouchNode = window.soundtouch.getWebAudioNode(
                        wavesurfer.backend.ac,
                        filter
                    );

                }
                wavesurfer.backend.disconnectFilters();

                const splitter = wavesurfer.backend.ac.createChannelSplitter(2);
                const merger = wavesurfer.backend.ac.createChannelMerger(2);
                const leftGain = wavesurfer.backend.ac.createGain();
                const rightGain = wavesurfer.backend.ac.createGain();

                splitter.connect(leftGain, 0);
                leftGain.gain.value = 0.3;

                splitter.connect(rightGain, 1);
                rightGain.gain.value = 0.6;

                leftGain.connect(merger, 0, 0);
                rightGain.connect(merger, 0, 1);

                merger.connect(wavesurfer.panner);

                wavesurfer.panner.connect(soundtouchNode);
                soundtouchNode.connect(wavesurfer.backend.ac.destination);

                wavesurfer.backend.setFilters([splitter, leftGain, rightGain, merger, wavesurfer.panner, soundtouchNode]);

            }
        }); `

And this is what print  when i click on one of volume controls after the stretcher node is setted. The value of gain changes even if there are no effects.

![image](https://user-images.githubusercontent.com/44341274/58863478-30f2d780-86b3-11e9-8730-93222c732b25.png)
