### ISSUE TITLE
when load peaks from server, brower memory up to height

### ISSUE THREAD

**Issue by 15838028035** [wavesurfer-js/wavesurfer.js#1551]
hi, 
when load peaks from server, brower memory up to height,

pcm files about 30M, peaks about 100,000 in array,

is there anyway to slove it ?

@katspaugh

**Comment by ThoughtZer** [comment]
@15838028035 Are you using the peaks json passed from the server to the front end? I also encountered a problem with excessive memory usage.
But I am generating  from the front end.

**Comment by lida1984** [comment]
> @15838028035 Are you using the peaks json passed from the server to the front end? I also encountered a problem with excessive memory usage.
> But I am generating from the front end.

How can I get the peaks array ? Do you know ?  Can you tell me ?

**Comment by aburai** [comment]
see https://wavesurfer-js.org/faq/ How to generate waveform data on the server?
