### ISSUE TITLE
Possible dead code in getPeaks

### ISSUE THREAD

**Issue by gartenfeld** [wavesurfer-js/wavesurfer.js#1643]
https://github.com/katspaugh/wavesurfer.js/blob/b154dc4e4c152a7890e1f284972f7f8a6a3dbd93/src/webaudio.js#L397-L410

With [Line 397](https://github.com/katspaugh/wavesurfer.js/blob/b154dc4e4c152a7890e1f284972f7f8a6a3dbd93/src/webaudio.js#L397) above, the second block is not making much sense, since `setLength` doesn't change the `buffer`.

**Comment by thijstriemstra** [comment]
You're right. There's an https://eslint.org/docs/rules/no-unreachable eslint rule, and after enabling it, there are no errors detected even though it should, bleh.

```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index 6ac9bc4..f7e329a 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -28,6 +28,7 @@ module.exports = {
         ],
         eqeqeq: 'off',
         'no-console': 'off',
-        'no-unused-vars': 'off'
+        'no-unused-vars': 'off',
+        'no-unreachable': 2
     }
 };
```

**Comment by aburai** [comment]
the linter do not know, if the implementation of `setLength()` in runtime, change the buffer or not
for me it is valid code, but in my code i would add a comment for clarification

**Comment by thijstriemstra** [comment]
> it is valid code

it is, but it breaks stuff. Need to figure out when/where/why.
