### ISSUE TITLE
Create an ESM package for easy use in rollup etc

### ISSUE THREAD

**Issue by PaulKinlan** [wavesurfer-js/wavesurfer.js#1650]
I'm trying to integrate this module into my build process that is rollup based, and I can't import it as a node dependency because the `dist` output is not ES module compatible (I believe I could Babelify it, but there's no need for me to add all this heavy weight code).

It would be neat if you had an esm build alongside (what looks like a UMD focused output). Right now all of your code looks to be built with ES Modules already so I think you can get away with providing an attribute to your package for `module` 'https://github.com/rollup/rollup/wiki/pkg.module' and bundling the ES Module code into a new output called wavesurfer.mjs (or something similar).

**Comment by thijstriemstra** [comment]
@PaulKinlan PRs are welcome!
