### ISSUE TITLE
Spectrogram labels when scrolling

### ISSUE THREAD

**Issue by Brabudu** [wavesurfer-js/wavesurfer.js#1666]
It would be useful to be able to choose, in case of scrolling, if the labels of the spectrogram should move with the spectrogram or be fixed (css position: fixed).
Thank you

**Comment by thijstriemstra** [comment]
@Brabudu if you have a fix for this, please open a pull request!

**Comment by KerryTucker** [comment]
when fix this it goes away from spectrogram position fixed is not working

**Comment by Iquebal** [comment]
When fix the position fixed/sticky label position sticky/fixed is not working.

---
Thanks,
Iquebal

**Comment by musicog** [comment]
@Brabudu You ask for the possibility to choose between fixed and absolute, but to me the current 'fixed' behaviour just seems like a bug - I can't think of a use-case where this would be the intended behaviour. I've submitted PR #2558 that would just always make it absolute. 

Do you have a use-case in mind where 'fixed' would still be required?

For others finding this issue: a temporary work-around before the PR is merged can be achieved with the following CSS:

```
spectrogram .spec-labels {
  position:absolute !important;
}
```
