### ISSUE TITLE
Discussion: Canvas as required parameter

### ISSUE THREAD

**Issue by chrisparton1991** [wavesurfer-js/wavesurfer.js#1695]
I'm omitting the usual checklist as this isn't a bug, just a topic for discussion.

**Topic**
The Wavesurfer documentation states that the only required parameter for a Wavesurfer instance is a container DOM element.

**Background info**
For my project, I'm considering implementing a [PIXI.js](https://www.pixijs.com) Wavesurfer renderer, which will render the waveform into an existing WebGL context.

If I end up going down this route, it means my renderer won't have any concept of a container DOM element, and will technically violate the API.

**Question**
My renderer will be pretty application-specific so I won't try to get it merged into the main repo, but it does raise the question of whether the `container` property should be mandatory/optional on a per-renderer basis?

Totally happy if the answer is "your use case is too specific to be worth considering" :)

**Comment by thijstriemstra** [comment]
> the container property should be mandatory/optional on a per-renderer basis

No, I can see it being optional in some cases.
