### ISSUE TITLE
Toggle Autocenter

### ISSUE THREAD

**Issue by killia15** [wavesurfer-js/wavesurfer.js#1706]
Hello! Thanks for creating such a great library. I've been using it for annotating audio files (similar to the example on the site). One of the initial things that I noticed is that autocentering isn't desirable when playing a region where the user picks a section, loops it and comments on it, as shown in the attached image.

I'd like to have it where I could toggle off the autocenter if I'm simply clicking on a region to play it and have it on otherwise.

My question is - is this already possible? If not, what would be the best way to tackle this? Can I extend the regions plugin or perhaps the main module itself? I'd be happy to take a crack at it myself with a bit of guidance!

![image](https://user-images.githubusercontent.com/30830235/62089703-fb441800-b237-11e9-94b7-37dd59ecf70a.png)

**Comment by thijstriemstra** [comment]
sounds like a good idea. also related to pull request #1702. @killia15 maybe you can take a look at that pull request to check how autoCenter works (and is being improved), and then go through the regions plugin and see where autoCenter is used there?

**Comment by killia15** [comment]
It looks like the regions plugin doesn't make use of autoCenter. It looks like Drawer takes care of it. Is it possible to change the params without reinitializing it? For example could I access the drawer from the wavesurfer instance and set it to false and then true?

**Comment by killia15** [comment]
Then perhaps we could add a method to enable / disable autocentering without exposing the internal api.

**Comment by thijstriemstra** [comment]
sure, looking forward to a PR and we can discuss your approach there.

**Comment by killia15** [comment]
I was able to get my desired use case working by setting `this.waveSurferInstance.drawer.params.autoCenter = false;` on region-play and then re-enabling it afterwards.

Do you think that it would be desirable to add a configuration option to the regions that would disable autocentering if a region was played (not a region enter but rather a user actually clicking on a region to play it)?

Alternatively, we could also add enableAutoCenter() and disableAutoCenter() methods.

**Comment by killia15** [comment]
This could be a specialized use case, in which case I wouldn't want to add unnecessary methods, but if you think that it would be useful, I'd be happy to submit a PR on top of #1702 .

**Comment by thijstriemstra** [comment]
> Do you think that it would be desirable to add a configuration option to the regions that would disable autocentering if a region was played (not a region enter but rather a user actually clicking on a region to play it)?

Yes 👍 

> Alternatively, we could also add enableAutoCenter() and disableAutoCenter() methods.

because there are more options for autoCenter in the future (see #1702), maybe a new method that accepts the other autoCenter related options as well? not just one/two that simply enable/disable a single parameter.

**Comment by killia15** [comment]
Yeah I think that would be good. A method like `configureAutoCenter` or something similar that could take an object and update the params. Should be simple considering that the drawer wouldn't need to be reinitialized or anything.
