### ISSUE TITLE
Region start and end value wrongly updated

### ISSUE THREAD

**Issue by ghost** [wavesurfer-js/wavesurfer.js#1712]
Hi all,

   I used wavesurfer region for audio file for trimming the region. Its start and end value was wrongly updating when we set the minimum and maximum length and also end value was updating over the maximum value so when I play the audio it was playing wrong because of start and end value was wrong 

```
WaveSurferRegions.create({
    regions: [
        {
            start: 0,
            end: 30,
            minLength :30,
            maxLength: 60,
            loop:true,
            color: 'hsla(400, 100%, 30%, 0.5)'
        }
    ]
})
```

By viewable my region start and end value was **0** to **60** but it gives **`0.09152029514079274`** to **`117.3353256160868`** when it was after dragged

![Untitled](https://user-images.githubusercontent.com/42537872/62270834-a3cec380-b454-11e9-8801-91c95b001538.png)

Kindly do reply if anyone knows...?

@katspaugh

**Comment by aburai** [comment]
i can reproduce it with v3. i set a maxLength of 60, resize it to max and get end value 67
the end value depends on where i release the handle

**Comment by Ramya-22** [comment]
Thank you @aburai .

**Comment by thijstriemstra** [comment]
@Ramya-22 can you try 3.2.0?

**Comment by fozzle** [comment]
Seems to still be an issue in 4.2.0
