### ISSUE TITLE
Question: best practices way to play multiple regions in succession?

### ISSUE THREAD

**Issue by lionel-lints** [wavesurfer-js/wavesurfer.js#1717]
I have written a react component to play all regions in succession, however I have the sinking feeling like this isn't going to produce the most consistent results over time. Is there a preferred way to use the Regions plugin to play a set of regions in succession?

I have read through the documentation, looked through the previous issues, and taken a look at the source code, but I am not clear about the ideal way to identify a set of regions to play and play them in a specific order etc.

## Wavesurfer.js version(s):
3.0.0

### Browser and operating system version(s):
Chrome Version 75.0.3770.142 on OSX 10.14.5

### Code needed to reproduce the issue:
This react component code works as is, however it feels like an anti-pattern, as I am feeling like I am fighting the api here. I am wondering if there is some cleaner approach I have totally missed? Or any other ideas are also appreciated!
```
class WaveSurfer extends Component {
  componentDidMount() {
    const aud = document.querySelector('#song');

    this.wavesurfer = WaveSurfer.create({
      barWidth: 1,
      cursorWidth: 1,
      container: '#waveform',
      backend: 'MediaElement',
      height: 100,
      progressColor: '#4a74a5',
      responsive: true,
      waveColor: '#ccc',
      cursorColor: '#4a74a5',
      plugins: [
        RegionsPlugin.create({
          regions: [
            {
              start: 1,
              end: 3
            },
            {
              start: 5,
              end: 7
            }
          ],
          dragSelection: {
            slop: 2
          }
        })
      ]
    });
    this.wavesurfer.load(aud);
  }

  playSelections = () => {
    const wavesurfer = this.wavesurfer
    const playlist = Object.values(wavesurfer.regions.list)
    playlist.sort((a, b) => (a.start > b.start) ? 1 : -1)

    wavesurfer.on('pause', () => {
      if(playlist.length > 1){
        playlist.shift()
        wavesurfer.play(playlist[0].start, playlist[0].end)
      } else if (playlist.length === 1) {
        wavesurfer.stop()
      }
    })

    this.wavesurfer.play(playlist[0].start, playlist[0].end);
  }

  render() {
    return (
      <div>
        <button onClick={this.playSelections}>Play Selections</button>
        <div
          style={{ border: '1px solid grey', width: '90vw', height: '10vh'}}
          id="waveform"
        />
        <audio
          id="song"
          src="https://reelcrafter-east.s3.amazonaws.com/aux/test.m4a"
        />
      </div>
    );
  }
}
```

Any thoughts/ideas much appreciated here, thanks!

**Comment by aburai** [comment]
Currently i did it the same way, but i am not happy with the solution because i can't pause a playlist.
I think about adding a new event like `region-pause` for better handling.

I would add an option to regions create for the event type to fire because otherwise it will be a breaking change.

Other ideas?

**Comment by lionel-lints** [comment]
@aburai thanks for the reply, I have had problems with the 'region-out' event, as it seems to fire multiple times for me when the audio is jumping from one region to another. Can you share your code that is working?

Thanks again!

PS here is my recent playSelection method that seems to be working, using the `audioprocess` event... I still think it's not really an ideal solution, so yeah any and all ideas are appreciated!
```
  playSelections = () => {
    const waveSurfer = this.wavesurfer
    const playlist = Object.values(waveSurfer.regions.list)
    playlist.sort((a, b) => (a.start > b.start ? 1 : -1))

    let curr = playlist.shift()

    waveSurfer.on('audioprocess', time => {
      if (time > curr.end && playlist.length > 0) {
        curr = playlist.shift()
        curr.play()
      } else if (time > curr.end && playlist.length === 0) {
        waveSurfer.stop()
      }
    })

    waveSurfer.play(curr.start)
  }
```
