### ISSUE TITLE
Multi Color Bars

### ISSUE THREAD

**Issue by alisajidcs** [wavesurfer-js/wavesurfer.js#1722]
Hy, I want to give color to each and bar saperately. Is there anyway to do so in current package?

If no please guide me how can I access canvas object so that I can override selected bars myself.

The scenario I am in right now is that I want to give colors based on emotions. Like if audio was angry for 1st 10 seconds then color should be red and if next 20 seconds is a happy voice then I want to give may be yellow or green color.

Thanks

**Comment by thijstriemstra** [comment]
> Is there anyway to do so in current package?

not yet.

> how can I access canvas object 

@alisajidcs use the `wavesurfer.drawer.canvases` array to access the canvas(es).

if you come up with something we can re-use, happy to review any pull requests.

**Comment by thijstriemstra** [comment]
cc @kubk

**Comment by kubk** [comment]
Hi @alisajidcs , you can hook into `setFillStyles` to override bar colors separately: https://github.com/katspaugh/wavesurfer.js/blob/9f1ed9064ea86e736cc9d4051ffe0a2bfb4d74b3/src/drawer.canvasentry.js#L141

This method is called for each bar. Let me know if you need more details.
