### ISSUE TITLE
Load peaks dynamically

### ISSUE THREAD

**Issue by jgraniero** [wavesurfer-js/wavesurfer.js#1730]
I want to allow users to interact with wavesurfer (play audio, select regions, etc.) before the peak data comes down from our servers.

The issue I'm having is that loading the peak data is done via `wavesurfer.load()`, which has some undesirable side effects in my case.  ready events fire again, playback will reset to the beginning even if in progress.  I can restore playback position, but that's not an ideal experience either if the audio is playing when the peaks load.

I realize I can probably just set peaks to the private `peaks` instance variable on the `MediaElement` class, but I've been hesitant to do this as `peaks` is private and I imagine updates to wavesurfer.js could wind up breaking my code.

Am I missing how this is supposed to be done?  If not, would you be open to a feature request for this, or too narrow a use case?

**Comment by thijstriemstra** [comment]
> If not, would you be open to a feature request for this, or too narrow a use case?

Yes, if you have an improvement for wavesurfer.js, please open a PR and we can take a look.

**Comment by aburai** [comment]
i use `wavesurfer.backend.setPeaks(peaks, duration)`
