### ISSUE TITLE
region updateRender: the startLimited value has floating precision losted problem

### ISSUE THREAD

**Issue by lisashen** [wavesurfer-js/wavesurfer.js#1737]
### Wavesurfer.js version(s):
3.0.0

### Browser and operating system version(s):
chrome 76.0.3809, windows 10

### Code needed to reproduce the issue:
```
updateRender() {
        const dur = this.wavesurfer.getDuration();
        const width = this.getWidth();

        var startLimited = this.start;
        var endLimited = this.end;
        if (startLimited < 0) {
            startLimited = 0;
            endLimited = endLimited - startLimited; // 
        }
        if (endLimited > dur) {
            endLimited = dur;
            startLimited = dur - (endLimited - startLimited);
        }
...
    }
```

When endLimited > dur, after setting endLimited to dur, startLimited = dur - (endLimited - startLimited)  -> startLimited = dur - (dur - startLimited). I dont know why this is necessary. And this will cause floating precision losted.

**Comment by thijstriemstra** [comment]
@lisashen can you make a pull request with a fix?

**Comment by thijstriemstra** [comment]
@lisashen still an issue with v3.2.0?
