### ISSUE TITLE
Plugin elan-wave-segment.js is missing

### ISSUE THREAD

**Issue by Honghe** [wavesurfer-js/wavesurfer.js#1745]
### Wavesurfer.js version(s):
3.0.0

### Browser and operating system version(s):
Chrome 77

### Use behaviour needed to reproduce the issue:
Run example `example/elan-wave-segment`

![image](https://user-images.githubusercontent.com/1092722/65034029-d25b1c00-d978-11e9-89f7-34aa218c0b8d.png)

**Comment by thijstriemstra** [comment]
This was closed as completed but it obviously isn't. Looks like the decision is made to abandon the effort, so fyi, see #1756
