### ISSUE TITLE
Strange behaviour when executing seekAndCenter(1) twice

### ISSUE THREAD

**Issue by lauradP** [wavesurfer-js/wavesurfer.js#1747]
Hello everybody,
I'm facing a strange issue with the seekAndCenter function. I have this javascript function:

  $scope.mySeekAndCenter = function (par) {
                console.log("initial duration: " + $scope.wavesurfer.getDuration());
                $scope.wavesurfer.seekTo(par);
                console.log("new position: " + $scope.wavesurfer.getDuration());
                console.log("new duration: " + $scope.wavesurfer.getDuration());
   }

and I'm playing a file lasting 225.684 s (duration confirmed by ffprobe). 

If I run mySeekAndCenter(1) the player position correctly goes to the end of the file. The duration calculated after executing seekAndCenter is still correct. Console log prints
_initial duration: 225.684
new position: 225.684
new duration: 225.684_

If I suddently run mySeekAndCenter(1) again (without doing anything else in the while) the duration has changed to 225.98316.
initial duration: 225.98316
new position: 225.98316
new duration: 225.98316

Have anyone experienced duration changes while the player is running? I first calculate the duration when the 'ready' event is fired by the player and it matches the one calculated before executing the seekAndCenter function for the first time (225.684 s).

The same behaviuor is exeprienced by using the seekTo function.

Can anyone help me?

Thanks, 
Laura

**Comment by thijstriemstra** [comment]
what browser/operating system, version of wavesurfer.js?

**Comment by lauradP** [comment]
Hi!
I'm using wavesurfer version 3.0.
The test browser is Google Chrome running on Windows 10.

Laura

**Comment by lauradP** [comment]
Hi!
Are there any updates about this issue?

**Comment by lauradP** [comment]
Seems related to https://github.com/katspaugh/wavesurfer.js/issues/1485

**Comment by lauradP** [comment]
Today I made some more tests. The problem seems related to preloaded peaks. My mp3 files are generated from a wave file using the following ffmpeg parameters: -acodec libmp3lame -ab 64k -ar 32k.
Preloaded peaks are generated using audiowaveform with the following parameters: --pixels-per-second 25 -b 16.
