### ISSUE TITLE
How autoplay a playlist?

### ISSUE THREAD

**Issue by kaibrune** [wavesurfer-js/wavesurfer.js#1752]
### Browser and operating system version(s):
Chrome, Windows

### Code needed to reproduce the issue:

```
    wavesurfer.on('finish', function() {
        setCurrentSong((currentTrack + 1) % links.length);
        wavesurfer.play();

    });
```

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:

So if I want to autoplay a playlist. So when the first song finished, it should start the next song. At the moment it starts the next song but there is no sound an the console shows:

```
webaudio.js:677 Uncaught DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
    at t.value (https://unpkg.com/wavesurfer.js@3.0.0/dist/wavesurfer.min.js:1:13939)
    at ScriptProcessorNode.scriptNode.onaudioprocess (https://unpkg.com/wavesurfer.js@3.0.0/dist/wavesurfer.min.js:1:9407)
```
I use the exact same code from the playlist example.

**Comment by thijstriemstra** [comment]
ping @entonbiba

**Comment by entonbiba** [comment]
@kaibrune Does the following exist in your code? I'm not able to replicate it with the example link below:
https://wavesurfer-js.org/example/playlist/index.html

```
var setCurrentSong = function(index) {
        links[currentTrack].classList.remove('active');
        currentTrack = index;
        links[currentTrack].classList.add('active');
        wavesurfer.load(links[currentTrack].href);
    };
```
