### ISSUE TITLE
Can i show some message on the bar of waveform

### ISSUE THREAD

**Issue by gocubetech** [wavesurfer-js/wavesurfer.js#1755]

**Comment by thijstriemstra** [comment]
can you be more specific, add a screenshot?

**Comment by gocubetech** [comment]
![bar message](https://user-images.githubusercontent.com/46589776/65958314-b7a2a000-e46c-11e9-9330-5c44c67ebee1.png)

Something like this ,At a particular bar show that message

**Comment by interactionsolutions** [comment]
This is exactly what I want to do to... Is there any update ?

**Comment by thijstriemstra** [comment]
@interactionsolutions and @gocubetech the waveform is drawn on a canvas element. you can draw on this canvas element anything you want. 

```javascript
var cnv = wavesurfer.drawer.canvases[0].wave;
var ws_ctx = wavesurfer.drawer.canvases[0].waveCtx;
ws_ctx.font = "30px Arial";
ws_ctx.fillStyle = "red";
ws_ctx.textAlign = "center";
ws_ctx.fillText("Hello World", cnv.width/2, cnv.height/2); 
```

**Comment by interactionsolutions** [comment]
Hi, 

Is it possible to write the text at a specific place on the waveform.
In the function below I can pause a file playing but also want to leave a note at the exact place where i paused.
```
  function pausefornote(questionnum,questionId){ 
    wavesurfer.pause(); 
    var stoppedat = wavesurfer.getCurrentTime(); 
    console.log(" Paused to get input for "+questionId+" at "+stoppedat); 
   $("#"+questionId+"_eventtime").text(stoppedat % 60); 
   sessionStorage.setItem("qid"+questionnum,stoppedat); 
   var cnv = wavesurfer.drawer.canvases[0].wave; 
   var ws_ctx = wavesurfer.drawer.canvases[0].waveCtx; 
   ws_ctx.font = "20px Arial"; 
   ws_ctx.fillStyle = "yellow"; 
    **ws_ctx.textAlign = stoppedat;**          <-- I tried this but it didnt work.
   ws_ctx.fillText("Tagged", cnv.width/2, cnv.height/2); 
  }
'''
![image](https://user-images.githubusercontent.com/59672204/73234104-8183eb80-41d4-11ea-98e8-fdf1babdc551.png)

**Comment by thijstriemstra** [comment]
Try `wavesurfer.drawer.lastPos` for the position of the playhead. It is marked as private but seems like a useful piece of data that could be exposed by a public method.

**Comment by thijstriemstra** [comment]
ps. would be cool to have an example like this, want to make one and open a pull request for it?

**Comment by interactionsolutions** [comment]
I have it working to a point.
```
   var cnv = wavesurfer.drawer.canvases[0].wave;
   var ws_ctx = wavesurfer.drawer.canvases[0].waveCtx;
   const img = new Image();
   img.src = "images/note.png";

   var lastpos = wavesurfer.drawer.lastPos;
   console.log("lastpos"+lastpos);
  // wavesurfer.seekAndCenter(stoppedat);
  //  ws_ctx.fillText("!", wavesurfer.drawer.lastPos, cnv.height/2);
    img.onload = () =>{
      ws_ctx.drawImage(img,wavesurfer.drawer.lastPos, cnv.height/2,2, 20);
    }  // ws_ctx.fillText("Tagged", cnv.width/2, cnv.height/2);
```
note.png is simply a red mark I place on the waveform. On a sterio waveformit appears between the two conversations.
I now create a region for that particular part of speech.
The next challenge is to get the region to show up on page load. -- I'll open another discussion on that !.
would I be correct in thinking you would need to create another canvas, over the top of the waveform and write the notation to that ?  If i could work out how to identify the coordinates of the upper part of the waveform canvas I might be able to write to it.
Still a bit of a learning experience.

**Comment by thijstriemstra** [comment]
can you add screenshot?

**Comment by interactionsolutions** [comment]
HI Thijs,

      Here is a screen shot of what I have working so far.
Second screen shot is with the small red vertical bar, under the region. 

I have not been able to work out how to get it anywhere else on the canvas. On a mono recording it appears to be centered on the center line of the audio.

 

BTW… Love your work with this library.

**Comment by thijstriemstra** [comment]
>  Here is a screen shot

doesn't seem to be included.

**Comment by interactionsolutions** [comment]
HI Thijs,

                     Sorry about that… 

Here is the screen shot.

And here is the second which was included in the last email. It’s a bit hard to see but there is a small vertical red line which is the lastposition value.

 



 

Regards

Alan McIntosh

**Comment by thijstriemstra** [comment]
Apparently it's not possible to share images on github using email.

**Comment by Mladja** [comment]
First of all, thank you for this awesome library. I was managed to do a lot of cool stuff with it. 

My question that I have is it possible to draw some elements beneath waveform but based on the time segment that I'm running on waveform? 
I have some speech that starts from { time: 0ms } and ends on { time: 1233ms } and etc. 
Basically something like a commercial that is running in the background. 
Any ideas on how can I achieve this? 

![Screenshot 2021-11-03 at 22 20 47](https://user-images.githubusercontent.com/7488636/140194544-c83596ea-5ad5-4ec1-8d25-9a7a60ae0fe5.png)
