### ISSUE TITLE
How to draw waveform using range URI params

### ISSUE THREAD

**Issue by ghost** [wavesurfer-js/wavesurfer.js#1766]
Hi @aburai ,

I want to draw waveform using start and end value in the original audio source.

It's possible ?

cc - @katspaugh

**Comment by thijstriemstra** [comment]
Not sure what you mean..

**Comment by katspaugh** [comment]
I guess @Ramya-22 means the [range URI params](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery#Specifying_playback_range).

**Comment by Ramya-22** [comment]
@katspaugh Thanks for your time, 

I need an update of the above you mentioned range URI params. 


```
<div id="waveform"></div>

var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    barWidth: 0.5,
    barHeight: 2,
    barGap : 2,
    height:35,
    start : 16,
    end : 30
});
wavesurfer .load(https://wavesurfer-js.org/example/media/demo.wav);
```
REF - 
![2019-10-11_15-46-36](https://user-images.githubusercontent.com/42537872/66644317-48803500-ec3e-11e9-8e76-446fc9a2285b.png)


Thanks in advance.

**Comment by peterj35** [comment]
Any updates on how you made this work for you @Ramya-22 ?
