### ISSUE TITLE
Better waveform accuracy with less data?

### ISSUE THREAD

**Issue by osheroff** [wavesurfer-js/wavesurfer.js#1799]
<img width="1048" alt="Screenshot 2019-11-06 09 15 26" src="https://user-images.githubusercontent.com/260084/68321163-11067c00-0076-11ea-9aa2-635505897d43.png">

I'm using `audiowaveform` to generate waveform graphs, but I'm curious as to why I'm losing so much waveform resolution when I generate a waveform of about the size I want (5k).  In the attached screenshot, the first waveform is one drawn with directly from the mp3 file.  Each subsequent file represents a different `-z` parameter to audiowaveform; version 256 is 256 "samples-per-pixel", etc. 

My question here is, why does wavesurfer seem to lose so much resolution at 4096 samples per pixel?  This still includes about 5k samples, far more than the number of lines shown on the graph.  I'm happy to poke into code if someone could point me in the correct place.

**Comment by aburai** [comment]
If you have more than one peak per pixel, you can use different approaches to draw that
- use the first peak
- use the last peak
- use the average of all peaks
- use the lowest peak
- use the highest peak

i have currently no time to check which approach wavesurfer currently use, but i mean first peak

in my custom renderer i have tried all approaches and i go currently with average
