### ISSUE TITLE
creating more than one regions freezes Firefox / function of having only one region needed

### ISSUE THREAD

**Issue by liujinliang01** [wavesurfer-js/wavesurfer.js#1803]
Hi,

As always, I am grateful to the great minds and hearts behind this very promising wavesurfer.js tool.

After quite some struggle, I am finally very close to what I really need - when a user drags to create a region, all other regions are cleared leaving only the most recently created one and the player starts looping the region right away endlessly until Pause is clicked or until another region is created. When another region is created, the previous region will be cleared and only the most recenlty created region will loop. etc.. Whenever a new region is created, the user doesn't have to clear the previous region to clear it manually. 

In other words, how to create a region the creation of which will automatically trigger a clearance of all previous regions? Or, is there an option to have only one region in action at a time?

Not only that, I have found a glitch: If I forget to clear the current region before creating another one, two regions appear and the playing gets stuck and then alas! Firefox freezes. which slows down the whole computer. I have to kill Firefox using Windows Task Manager and relaunch it. This is very annoying to the users. 

My environment: Win10 prof. / Firefox 70.0.1 32 bit / wavesurfer.js 3.2.0 / regions plugin for 3.2.0.
 
Any help is greatly appreciated.
best regards
Jim

**Comment by thijstriemstra** [comment]
can you create an example to reproduces this crash @liujinliang01?

**Comment by liujinliang01** [comment]
Hi Thijs,
I have created a codepen instance: https://codepen.io/liujinliang01/pen/VwwxQmg
Thank you very much for your kind support.
best regards
Jim







At 2019-11-10 20:52:57, "Thijs Triemstra" <notifications@github.com> wrote:


can you create an example to reproduces this crash @liujinliang01?
