### ISSUE TITLE
mp3 files longer than 20 minutes produce error: The given encoding is not supported.

### ISSUE THREAD

**Issue by liujinliang01** [wavesurfer-js/wavesurfer.js#1808]
I have a few mp3 files that are all of the following properties:
```
bitrate: 128 kb/s
Stream #0:0: 
Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
```
Durations of the files vary between 10-30 minutes. 

Those that are longer than 18 minutes give the following error:
```
	decodeAudioData buffer is passed  content of unknown type
	EncodingError: The given encoding is not supported.
```
But files of shorter durations are OK.

My environment:
Win10 Prof.
Browser: Firefox 70.0.1 32bit

Any help is greatly appreciated.

**Comment by liujinliang01** [comment]
I have 8GB of memory and less than 60% is used at peak time; 
CPU is 2.5GHz x 2, peak use of which is 100% momentarily and then immediately drops to less 40%.

**Comment by thijstriemstra** [comment]
Can you try and use the `MediaElement` backend instead?

**Comment by liujinliang01** [comment]
Thank you Thijs for your response.


I don't know how to  use the MediaElement backend. 


I have looked at this page: https://wavesurfer-js.org/api/class/src/mediaelement.js~MediaElement.html
But I don't know how to test whether my mp3 files longer than 20 min (or thereabout) can play.


Could you please give me some instructions with examples?


Thank you in advance.
best regards
Jim 






At 2019-11-24 03:31:18, "Thijs Triemstra" <notifications@github.com> wrote:


Can you try and use the MediaElement backend instead?

**Comment by thijstriemstra** [comment]
> Could you please give me some instructions with examples?

try this example: https://github.com/katspaugh/wavesurfer.js/tree/master/example/audio-element
