### ISSUE TITLE
Move Regions by groups

### ISSUE THREAD

**Issue by vlalentin** [wavesurfer-js/wavesurfer.js#1814]
Hi all and thank you for your work, it's really nice!

I use your script since few month for a personnal project and I would like move regions by groups.
Have you any idea to do that? I saw [this theard](https://github.com/katspaugh/wavesurfer.js/issues/463) but this allows to identify by group, but not to move.

Second question: How I can select many regions with mouse?

Thank you!

Edit: I use the wavesurfer.js 2

**Comment by thijstriemstra** [comment]
> Edit: I use the wavesurfer.js 2

why not use latest 3.x version?

**Comment by vlalentin** [comment]
> > Edit: I use the wavesurfer.js 2
> 
> why not use latest 3.x version?

Hello. I use the code on the website https://wavesurfer-js.org/v2/ and it’s the version 2. I don’t see version 3 on it.

**Comment by thijstriemstra** [comment]
try `npm install wavesurfer.js` for the latest.

**Comment by vlalentin** [comment]
Ok thank you. I will try with this version. 
I have avanced a litle on my problem. Now, I can add "groupe name" on regions. If I move one, the others are reloaded with the new parameters. I would like to improve this code with jquery selectable (select with mouse on the div #waveform). It's works but I have a conflict beetween codes **[1]** and **[1]**. When I activate the code **[2]**, **[1]** stop (on Google Chrome) or require two or three clics to reload the timing **[1]** (Firefox). I think the problem comes from #waveform (DOM element) because it is used by both. How could I solve this probleme or create priorites? Thank you!

**[1]** Function to get the timing when I click on the wave.
```
wavesurfer.on('seek', function (position) {
    var currentTime = position * wavesurfer.getDuration();
    $('#waveformcounter').text(currentTime);
});
```

**[2]** Function to select many regions at the same time:
```
$( "#waveform" ).selectable({
    stop: function(event) {
      var result = $( "#subtitle" ).empty();
      $( ".ui-selected", this ).each(function() {
        var index = $( "#waveform region" ).index( this );
        if(index > 0)
        	result.append( ( index + 1 ) + ' ');
      });
    }});
```
