### ISSUE TITLE
timeline plugin: fuzzy/unclear/low resolution on some devices

### ISSUE THREAD

**Issue by mustafa0x** [wavesurfer-js/wavesurfer.js#1822]
On my laptop it's fuzzy, while it's fine on my phone.

![tl1](https://user-images.githubusercontent.com/1473102/70373650-8a51f280-18f2-11ea-80a7-5d465c97658c.png)
![tl2](https://user-images.githubusercontent.com/1473102/70373651-8a51f280-18f2-11ea-991e-c4436856f2a1.png)

The timeline for [peaks.js](https://github.com/bbc/peaks.js) and [waveform-playlist](https://github.com/naomiaro/waveform-playlist) don't suffer from this problem.

![tl4](https://user-images.githubusercontent.com/1473102/70373670-ca18da00-18f2-11ea-9eae-2d4da70487b0.png)
![tl3](https://user-images.githubusercontent.com/1473102/70373671-ca18da00-18f2-11ea-9dde-ad06e003a1c9.png)

**Comment by thijstriemstra** [comment]
what kind of laptop? what version of wavesurfer.js?

**Comment by mustafa0x** [comment]
Laptop: A (non-retina) MacBook running High Sierra, and a Windows 10 laptop.
Version: 3.2.0.

**Comment by thijstriemstra** [comment]
There's something about an extra pixel in the plugin: https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/timeline.js#L336

can you adjust that and see if the issue is there. `pixelRatio` is being used in the plugin so it should take resolution in consideration..

**Comment by mustafa0x** [comment]
Yes, that does improve it (I actually made that change before I made the PR, but forgot to mention that!), but it it's still not as sharp as the other two tools mentioned.

I'll do more looking when I get a chance.
