### ISSUE TITLE
Setting the bar height after creation

### ISSUE THREAD

**Issue by KonigRob** [wavesurfer-js/wavesurfer.js#1830]
Hi,

I know that the bar height can be set when creating a new Waveform object, but you can't adjust the height of the bars afterward.  

 I was wondering if it was it's possible to implement a new function, setBarHeight()?

It might work similar to the zoom() function, just with adjusting the bar heights then redrawing the waveform?

**Comment by thijstriemstra** [comment]
use `wavesurer.setHeight(height)` to set the height of the waveform. If it uses bars, those will be set as well.

**Comment by RobTallGuy** [comment]
https://wfplayer.js.org/

Here's an example of what I was more meaning.  If you drag the Wave Scale range input at the bottom of the options given, it'll increase or decreaes the bar heights without changing the height of the canvas that holds it.

**Comment by thijstriemstra** [comment]
> I was wondering if it was it's possible to implement a new function, setBarHeight()?

pull requests are welcome.
