### ISSUE TITLE
abort controller is not defined 

### ISSUE THREAD

**Issue by shaktis110** [wavesurfer-js/wavesurfer.js#1832]
i have successfully managed to import wavesurfer.js in my ionic project but calling
 wavesurfer.load(url)  it gives error in console abort controller is not defined . i have saw the wavesurfer.js file and it has a object containing  return value of new abort controller . may be abort controller return undefined .
help me out thanks ....

**Comment by thijstriemstra** [comment]
can you paste the complete error message @shaktis110? What browser? what operating system?

**Comment by thijstriemstra** [comment]
Looks like you should use https://www.npmjs.com/package/abortcontroller-polyfill. Let us know how that goes.

**Comment by martinratinaud** [comment]
@shaktis110 I @thijstriemstra I think the best in this is https://polyfill.io/v3/url-builder/

Just tested

**Comment by thijstriemstra** [comment]
thanks for feedback.

> Just tested

With ionic?

**Comment by martinratinaud** [comment]
No just opened https://wavesurfer-js.org/example/playlist/index.html in Edge and can't play it

**Comment by martinratinaud** [comment]
@thijstriemstra no in 360chrome a chinese browser

**Comment by thijstriemstra** [comment]
is this feedback related to AbortController?

**Comment by martinratinaud** [comment]
I'm not sure what you mean
I had the `abort controller is not defined problem` and solved it using https://polyfill.io/v3/url-builder/
Just by putting the corresponding script in the <head> of my website.

It is basically the same as the polyfill you mentioned on npm but it supports a widest variety of polyfill and is well maintained

Hope it's clearer now

Thanks

**Comment by thijstriemstra** [comment]
@martinratinaud was that the only polyfill you needed for Edge, the AbortController one?

**Comment by martinratinaud** [comment]
For this problem yes
But for my website, I used the whole one with the feature toggle `Have every polyfill wrapped in a feature detect, which will only execute the polyfill if the native API is not present.`

**Comment by shaktis110** [comment]
First of all thanks for responding.. 
One thing I observed is that when I comment out the abort controller initiations it works fine. 
Is there any problem with that i know abort controller is for terminating the fetch call may be.... 
And second the waveform ui not showing up in device . After hours of dubug i came to the point that if the width of #waveform container is less then 15% then it show up but the size is very small nd also cover 15% width of screen. If I set width 100% then the canvas made from the wavesurfer contain width more then 1000 pixel. Which is obviously beyond the screen of any phone display. Will this be a issue why it not showing the waveform??

**Comment by shaktis110** [comment]
@Martinratinaud thanks for polyfill solution but i have tested this after installing polyfill package from npm in my ionic package... Anyway can you help me out with the waveform not show problem in native device. It also not  showing up when I tested it with stackblitz. Just to confirm my set up is right or not...

**Comment by shaktis110** [comment]
@martinratinaud platform is Android.
I am working with ionic framework.
