### ISSUE TITLE
Is there a way to set the duration of a "blank" waveform?

### ISSUE THREAD

**Issue by DawsonSeibold** [wavesurfer-js/wavesurfer.js#1836]
Hello,

In an application I'm working, users will sometimes use a blank (flatline) waveform as a way to visually indicate when events will happen if they choose to not use an audio file. 

The issue I'm running into is how to let the user decide how long the blank waveform will be. Is there any way to render a blank waveform with a set duration?

I was thinking I could possibly load a pre-rendered waveform into wavesurfer, however, after some messing around, it doesn't seem like that approach will work. 

Thanks in advance.

**Comment by thijstriemstra** [comment]
you can generate waveform peaks data with a 'blank waveform' and load that data.

> I was thinking I could possibly load a pre-rendered waveform into wavesurfer, however, after some messing around, it doesn't seem like that approach will work.

why not?

**Comment by DawsonSeibold** [comment]
> you can generate waveform peaks data with a 'blank waveform' and load that data.
> 
> > I was thinking I could possibly load a pre-rendered waveform into wavesurfer, however, after some messing around, it doesn't seem like that approach will work.
> 
> why not?

I have been following https://wavesurfer-js.org/faq/ (How to generate waveform data on the server?)

Here is my code for creating the wavesurfer object and the timeline once the waveform is created.
```
wavesurfer = WaveSurfer.create({container: '#waveform',
	cursorWidth: 2,
	height: 100,
	barHeight: 1,
	pixelRatio: window.devicePixelRatio || screen.deviceXDPI / screen.logicalXDPI,
	responsive: true
});

wavesurfer.on('ready', function () {
        timeline = Object.create(WaveSurfer.Timeline);
	timeline.init({
		wavesurfer: wavesurfer,
		container: '#waveform-timeline',
		responsive : true
	});
});
```

When loading a .mp3 file the waveform loads correctly. I can move the playhead around, the timeline is generated and it has the correct duration. 

<img width="1175" alt="Screen Shot 2020-01-01 at 1 33 39 PM" src="https://user-images.githubusercontent.com/9518504/71646059-97b68e80-2c9e-11ea-80ff-1cd3c28bc27a.png">

```
wavesurfer.load('Albany_2014.mp3');
```

However, when I convert a .mp3 file that is just silence using the audiowaveform program and try to load that using the method the faq suggests the waveform doesn't load properly. You can faintly see a flat line, however, you can not click and move the playhead and the timeline does not get generated. 

<img width="1174" alt="Screen Shot 2020-01-01 at 1 25 40 PM" src="https://user-images.githubusercontent.com/9518504/71646075-fa0f8f00-2c9e-11ea-8abe-c831ed012d30.png">

```
fetch('./silence.json').then(response => {
          if (!response.ok) { throw new Error("HTTP error " + response.status); }
          return response.json();
}).then(peaks => {
          console.log('loaded peaks! sample_rate: ' + peaks.sample_rate);

          wavesurfer.load('mediaElement', peaks.data);
}).catch((e) => {
          console.error('error', e);
});
```

I tried to use the same method to load an actual audio file and it doesn't quite work either. It looks like it shows the correct peaks for the first 100 or so pixels then stops. You also can't click and move the playhead and the timeline is not generated.

<img width="1172" alt="Screen Shot 2020-01-01 at 1 38 59 PM" src="https://user-images.githubusercontent.com/9518504/71646091-77d39a80-2c9f-11ea-8c83-2552bc25bd83.png">

```
fetch('./albany.json').then(response => {
          if (!response.ok) { throw new Error("HTTP error " + response.status); }
          return response.json();
}).then(peaks => {
          console.log('loaded peaks! sample_rate: ' + peaks.sample_rate);

          wavesurfer.load('mediaElement', peaks.data);
}).catch((e) => {
          console.error('error', e);
});
```

Is there something I'm missing?

**Comment by entonbiba** [comment]
@DawsonSeibold try adding `barWidth: 1, barMinHeight: 1,` see if that fixes it for you.

**Comment by marizuccara** [comment]
Hi, what is returned in peaks.data? The data peaks seems to be valid?
