### ISSUE TITLE
Can't play flac file on firefox

### ISSUE THREAD

**Issue by martinratinaud** [wavesurfer-js/wavesurfer.js#1849]
Wavesurfer.js version(s): **3.3.0**
Browser and operating system version(s): **Firefox 72.0.1** on **Mac OS Mojave**

Hi all

here is a pen to reproduce the fact that I can't use wavesurfer.js to play a flac file with Firefox 72.0.1 (I have only this version installed)

https://codepen.io/martinratinaud/pen/dyPKEmY

It is working well with Chrome.

I have seen this Bug https://github.com/katspaugh/wavesurfer.js/issues/816 but I'm not sure I understand what should be done to fix this as it is working well with a standard html5 audio tag

Thanks for your help

**Comment by thijstriemstra** [comment]
try `backend: MediaElement` option

**Comment by martinratinaud** [comment]
@thijstriemstra I've tried with `backend: 'MediaElementWebAudio'` as described here http://wavesurfer-js.org/example/mediaelement-webaudio/index.html and with `backend: 'MediaElement'` as you suggested

Both of them lead to the same error in firefox `Error decoding audiobuffer`

And in chrome, it odes not even show the waveform anymore

What is this supposed to be doing?

Is there some other manipulation to make (you can edit the pen if you know what to do)

Thanks a lot for your help
```

```

as explained

**Comment by thijstriemstra** [comment]
check https://bugzilla.mozilla.org/show_bug.cgi?id=1495648. can you run `ffprobe` on the flac file (part of ffmpeg) and paste the output here?

**Comment by martinratinaud** [comment]
Sure

```
ffprobe version 4.1.3 Copyright (c) 2007-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flac, from 'original.flac':
  Metadata:
    TITLE           : Game Over
    ALBUM           : 18...
    ARTIST          : G.E.M. 邓紫棋
  Duration: 00:03:11.97, start: 0.000000, bitrate: 1090 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```

**Comment by thijstriemstra** [comment]
there's metadata in it but not sure if it's the unsupported idv3. try a different flac file (use ffprobe to make sure it has no metadata) and see if that works. you can also try using ffmpeg to strip out the metadata and see if that works.

**Comment by martinratinaud** [comment]
I've removed the metadata with 
```
ffmpeg -y -i original.flac  -map_metadata -1 -codec copy original-nometadata.flac
```
Then `ffprobe` gives me this output
```
ffprobe version 4.1.3 Copyright (c) 2007-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flac, from 'original-nometadata.flac':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:03:11.97, start: 0.000000, bitrate: 1090 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
````

And the file does not work in the exact same way -> I've updated the pen.

Do you have any other idea.
I feel this should be addressed as a bug, what do you think @thijstriemstra 
?

**Comment by thijstriemstra** [comment]
> I feel this should be addressed as a bug, 

I see `EncodingError: The given encoding is not supported.` in Firefox 72 on Ubuntu 18, an error that is not coming from wavesurfer.js but the browser itself. There's not much we can do about that.. I would open a ticket in Firefox bugtracker instead.

**Comment by thijstriemstra** [comment]
Also see http://hpr.dogphilosophy.net/test/. Try downloading the flac they use there (it plays here) and test it with wavesurfer.js

**Comment by thijstriemstra** [comment]
Tested `flac.flac` with wavesurfer.js 3.3.1 and it seems to work fine. So it's something specific with your flac file.

**Comment by martinratinaud** [comment]
I tested with `flac.flac`and it works
Result of `ffprobe` here

```
ffprobe version 4.1.3 Copyright (c) 2007-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flac, from 'flac.flac':
  Metadata:
    GENRE           : speech
    ALBUM           : HTML5 Audio Format Support Test
    track           : 7
    TITLE           : FLAC
    DATE            : 2017
    COMMENTS        : FLAC file for https://hpr.dogphilosophy.net/test (version 2, updated to reflect FLAC's near ubiquitous support now)
    ARTIST          : Ivan "Epicanis" Privaci (pseud.)
  Duration: 00:00:36.44, start: 0.000000, bitrate: 1346 kb/s
    Stream #0:0: Audio: flac, 48000 Hz, stereo, s32 (24 bit)
```

So There is something in the flac file that make it fail to load in wavesurfer but that is still playable by a standard html5 tag

I'm not sure this issue should be closed because the flac file I uploaded first should work as it is playable by a standard html5 tag, don't you think ?

**Comment by thijstriemstra** [comment]
>  flac file I uploaded first should work

Like I mentioned before, the browser throws an error `EncodingError: The given encoding is not supported.` which is not a wavesurfer.js issue but a browser issue. I think. I am not sure where wavesurfer.js can be improved if there's an encoding error..

**Comment by martinratinaud** [comment]
@thijstriemstra I'm a bit sceptic.

How would you explain that the html5 tag works then, because I don't exactly know how wavesurfer.js works.

Thanks

**Comment by thijstriemstra** [comment]
the `WebAudio` backend uses WebAudio, whereas the `MediaElement` backend uses 'html5 tag'. Wavesurfer shouldn't do anything to the file (other than drawing the waveform) when using the MediaElement backend.

**Comment by martinratinaud** [comment]
Well then I do not know what we can do and maybe it's the file that has a problem.

So feel free to close it. For my use case on https://www.edityouraudio.com/ I will convert the file to mp3 to make it work

Thanks for your help
