### ISSUE TITLE
question: is it possible to display waveform in multiline mode? 

### ISSUE THREAD

**Issue by ApayRus** [wavesurfer-js/wavesurfer.js#1852]
Hi! Thanks for great player! 
I use it with 'regions' plugin for visualise audio books, with captions. 

Here is 6 minute, first chapter of book Great Expectations by Charles Dickens. 
![youtube channel art](https://user-images.githubusercontent.com/1222611/73078308-faccc700-3ed2-11ea-894f-24a9d2ce7ced.png)
Yesterday I did collage from many of lines 'waveform' (cropped from screenshots), and today I  have a question: is there a way to display in this way whole file? Not one line (with scrolling or not), but many of lines? 
I hope I can contribute this work, if it's not too hard :)

**Comment by thijstriemstra** [comment]
i don't think it's possible yet, pull requests are welcome!

**Comment by dy** [comment]
It's possible with [wavearea](https://dy.github.io/wavearea/?src=https://upload.wikimedia.org/wikipedia/commons/c/cf/Caja_de_m%C3%BAsica_(PianoConcerto5_Beethoven).ogg), you can check that out.
