### ISSUE TITLE
Needs two clicks to play in Safari 13.0.5 with preloaded peaks.

### ISSUE THREAD

**Issue by octave** [wavesurfer-js/wavesurfer.js#1866]
### Code needed to reproduce the issue:

```
var wavesurfer = WaveSurfer.create({
    container: waveformElement,
    barWidth: 1,
    barGap: 2
  });

wavesurfer.load(url, peaks.data);

playPauseButton.click(function(e) {
   wavesurfer.playPause();
});
```

### Use behaviour needed to reproduce the issue:

In Safari, when clicking the play/pause button the first time, it loads the file but doesn't start to play. It works only when pressing a second time.

I tried to use the `backend: 'MediaElement` instead for Safari, but even with `preload='none'` file is being downloaded on page load. I need to have the file loaded on click and not earlier as I have a lot of instances in the page.

Seems to be an AudioContext issue with Safari, but the `wavesurfer.playPause();` on click should take care of this.

It works fine in Chrome and Firefox.

**Comment by octave** [comment]
@thijstriemstra thanks for updating the issue. Is there any workaround in the meantime?

**Comment by thijstriemstra** [comment]
create the `audioContext` when the user presses a btn, and pass that to wavesurfer.js at startup using the audioContext option.

**Comment by octave** [comment]
@thijstriemstra my instances of wavesurfer.js are rendered at page load to display waveforms. So I can't pass an audioContext if the instance is already created correct?

What I'm wondering is when clicking the play/pause button the first time that calls `wavesurfer.playPause();` wavesurfer.js is creating the audioContext and so should make it work.

I did a quick demo that create an audioContext and play a file on click and it works fine in Safari: https://codepen.io/octavez/pen/RwPKyqM

So that looks like it's an issue with wavesurfer.js more than Safari.

**Comment by matt3224** [comment]
I also ran into this today in Safari 13.1 and wavesurfer 3.3.1
