### ISSUE TITLE
The regions plugin in the mobile version blocks first click outside (bug)

### ISSUE THREAD

**Issue by deniro21** [wavesurfer-js/wavesurfer.js#1878]
### Wavesurfer.js version(s):
Last (https://unpkg.com/wavesurfer.js)

### Browser and operating system version(s):
Chrome 80.0.3987.132 64bit Windows 7
Chrome on Android

### Code needed to reproduce the issue:
Only official example: https://wavesurfer-js.org/plugins/regions.html

### Use behaviour needed to reproduce the issue:
The essence of the bug: after resizing a region in the mobile version, any next click outside the wave window is blocked. And only the second click works fine. You can play the bug as follows. You need to open an example of a region using the link https://wavesurfer-js.org/plugins/regions.html through the Chrome DevTools mobile version simulator (do not forget to refresh the page after turning on the mobile display). After that, move the border of the region and try to click on the "Play" button. The first press will not work. The second will work. 

I checked this bug both in chrome on a PC and in a mobile phone on Android.

This can be fixed using an automatic hidden click to any place. The following code works for me:

```
    wavesurfer.on('region-update-end', function (current) {
        $("body").click();
    });
```
P.S. Great extension guys. Thank you very much! :)

**Comment by Reached** [comment]
I ran into this today as well, it's a big issue actually.. Anyone have an idea for a solution? :)
