### ISSUE TITLE
Can I use wavesurfer only for drawing?

### ISSUE THREAD

**Issue by roballsopp** [wavesurfer-js/wavesurfer.js#1894]
I'd like to simply draw the waveforms of the audio in videos that I load into an html5 video tag. This works pretty well for the first video using the `MediaElement` backend, but when I programmatically change the video loaded in my video tag wavesurfer doesn't behave so well. It doesn't automatically redraw the waveform to correspond to the audio in the newly loaded video like I'd expect, and if I try to call `wavesurfer.load()` or `wavesurfer.backend.loadElt()` inside a `loadedmetadata` event handler an infinite loop occurs, I'm guessing because wavesurfer is actually refetching/reloading the video, which fires the `loadedmetadata` event again...

It seems like wavesurfer wants to be the one to control loading and playing using the `<video>` tag, but I'd like it to be the other way around, where all the loading/playing/interacting occurs through the video element and its controls, and wavesurfer simply follows along, drawing the waveforms as they come, and does nothing else.

I see there is a separate 'drawer' class I might be able to use to perhaps accomplish what I want, but its not obvious from the documentation exactly how I'd do this, or if its even something I should really attempt with wavesurfer. Is there a way to accomplish what I'm after with wavesurfer?

**Comment by lauradP** [comment]
Hi, Did you find a solution for this use case?

**Comment by roballsopp** [comment]
@lauradP I didn't. I didn't explore this much further after my initial investigation resulted in this question. Would still be very interested in a solution though. The waveform drawing in this library looks and work really well, and it would be fantastic to have lightweight access to just the drawing functionality.

**Comment by entonbiba** [comment]
You may load the peaks with an empty audio file, let me get the sample I commented

**Comment by entonbiba** [comment]
#2058
