### ISSUE TITLE
remove the cookie banner on website

### ISSUE THREAD

**Issue by Pomax** [wavesurfer-js/wavesurfer.js#1904]
GDPR requires a cookie banner if you use cookies to uniquely identify individuals - i.e. you can tie sessions over time to unique individuals. If you don't do that, and you absolutely shouldn't because your site in no way warrants that, the cookie banner serves no purpose other than to be a nuisance.

**Comment by thijstriemstra** [comment]
sounds good. feel free to open a pull request (against gh-pages branch).

**Comment by Pomax** [comment]
I have 177 repos to maintain, so I'm going to leave it at "filing an issue so that the folks who actually maintain wavesurfer can triage and either close or roadmap it" =)

**Comment by entonbiba** [comment]
@Pomax from what I can tell any cookie you see on the demo site are set by cloudflare dns service automatically and not the actual code of wavesurfer library.
![image](https://user-images.githubusercontent.com/5193884/79270023-62a80380-7e6b-11ea-8e73-66b05625bd06.png)

You may go here to view cloudflare cookie policy: https://www.cloudflare.com/cookie-policy/
