### ISSUE TITLE
feature request: spectrogram plugin `height` property

### ISSUE THREAD

**Issue by Pomax** [wavesurfer-js/wavesurfer.js#1905]
Right now the spectrogram plugin does not have any way to indicate the dimensions it needs to fit in, and it would be super useful if it did, in order to present users with an Izotope RX style "waveform overlaid on the spectrum analysis" view of the audio they're working with.

**Comment by thijstriemstra** [comment]
> Izotope RX style "waveform overlaid on the spectrum analysis" view

:100:
