### ISSUE TITLE
getVolume() with WebAudio giving confusing async results

### ISSUE THREAD

**Issue by delewis13** [wavesurfer-js/wavesurfer.js#1911]
### Wavesurfer.js version(s):

v3.3.2

### Browser and operating system version(s):

Chrome, MacOS Mojave

### Issue description:

Seems as though when using the default backend, setVolume() is async in nature?
In the below codesandbox, the following happens:
(1) Volume is initially 1
(2) Volume is set to 0.5
(3) Song is played
(4) Volume is logged out. Console indicates volume = 1 [despite having just set it to 0.5]
(5) Volume is logged out again after a setTimeout. Console indicates volume=0.5

Note that this issue does not occur when using the MediaElement backend

### Code needed to reproduce the issue:

See codesandbox @ https://codesandbox.io/s/wavesurfer-qgsj6

**Comment by aburai** [comment]
Seems your codesandbox example is not public, i get 403 Forbidden.

**Comment by delewis13** [comment]
> Seems your codesandbox example is not public, i get 403 Forbidden.

Hmm, that's odd - its definitely on public and I can access in incognito mode on chrome. I've updated the link to remove some query string parameters, though they shouldn't have any effect. Can you please try once more?

**Comment by aburai** [comment]
it works now, maybe i find time today to have a closer look

**Comment by entonbiba** [comment]
@delewis13 do the following:

```
newWaveSurfer.on("ready", () => {
      newWaveSurfer.setVolume(0.5);
      setLoading(false);
    });
```

**Comment by entonbiba** [comment]
![image](https://user-images.githubusercontent.com/5193884/79278582-f7196280-7e79-11ea-8346-1d8b695273d8.png)

**Comment by delewis13** [comment]
> @delewis13 do the following:
> 
> ```
> newWaveSurfer.on("ready", () => {
>       newWaveSurfer.setVolume(0.5);
>       setLoading(false);
>     });
> ```

Hey and thanks for taking a look at this :)

Unfortunately I don't think that workaround can be used for my usecase :(

Reason is, every time I click play, I need to perform a fade in. To do so, I drop volume to 0 when play is clicked, then fade in from there. The on-ready solution is only a one-time thing, so while it work will for my first fade in, if I then pause and play again, it doesn't have an effect.

Any other ideas?

Also, I'm interested as to why the setVolume is not performed in a sync manner as it seems it should from the docs? And if it isn't sync, why cannot I not supply a callback?

**Comment by aburai** [comment]
the webaudio backend uses [AudioParam.setValueAtTime()](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/setValueAtTime) for setVolume
getVolume returns AudioParam.value
i have no idea why it took some time until the value is updated
