### ISSUE TITLE
Need to map silence on the given waveform 

### ISSUE THREAD

**Issue by artinegi1607** [wavesurfer-js/wavesurfer.js#1912]
Hi, I want to detect silence and also want to label it with "silence" on a waveform. 
I tried to achieve this using wavesurfer.backend.getPeaks(). But it is returning me [ ] every time.
The idea was to get the values and test values on the basis of some thresholds.

Why wavesurfer.backend.getPeaks() is empty all the time?
Is there a better to do this?  If yes, please suggest.

**Comment by thijstriemstra** [comment]
> Why wavesurfer.backend.getPeaks() is empty all the time?

How are you using this, can you show an example?

**Comment by artinegi1607** [comment]
my query is now resolved. I am getting the array now. Actually, I was trying to get the Peaks before wavesurfer was loaded in an asynchronous way. 

Now the challenge is how to map the data with seconds so that I can plot a region over a waveform. Can you help me with this?
