### ISSUE TITLE
How to export WaveSurfer js region as audio file?

### ISSUE THREAD

**Issue by yo-png** [wavesurfer-js/wavesurfer.js#1920]
Hi🖐!

I'm using WaveSurfer js for my project where we can edit an audio. For that i use the region plugin.

When the users clicks the button finish, I want to export the result in a audio file (mp3/wav)

To get the peaks of the audio where the user selected his audio, I do:

var json = wavesurfer.backend.getPeaks(960,  wavesurfer.regions.list["wavesurfer_j99v7ophop8"].start, wavesurfer.regions.list["wavesurfer_j99v7ophop8"].end)
This works but i want to export it as an audio file and not a json file.

Thanks in advance

**Comment by marizuccara** [comment]
You could try using external tools as ffmpeg

**Comment by bilalcorbacioglu** [comment]
I'm using FFmpeg for this ->

ffmpeg -y -i ${orjinalAudioPath} -ss ${region.start} -to ${region.end} ${exportPath}

**Comment by EngrZaks** [comment]
The illustration of the use of FFmpeg by @bilalcorbacioglu looks like a command line usage. I'm wondering how this could be used on the web front end  as the documentation didn't help either

**Comment by UchihaYuki** [comment]
Any news?
