### ISSUE TITLE
Any skins for wavesurfer out there?

### ISSUE THREAD

**Issue by wrybread** [wavesurfer-js/wavesurfer.js#1930]
I was wondering if there are any skins for wavesurfer out there? I'm trying to build out a nice looking interface similar to this:

http://www.radiovalencia.fm/podcasts/?episode=665&show=mikl-em

That uses an offshoot of wavesurfer called Zoomsounds:

https://codecanyon.net/item/zoomsounds-neat-html5-audio-player/4525354

It looks really nice, but doesn't have nearly the functionality of wavesurfer. 

Before I go trying to re-invent the wheel, I was wondering if there are some skinned examples of wavesurfer that anyone knows of?

**Comment by thijstriemstra** [comment]
I created videojs-wavesurfer to add an interface to wavesurfer.js: https://collab-project.github.io/videojs-wavesurfer/demo/index.html

The waveform can be configured to look like the example you linked. Question is, do you need "all of that" UI.

**Comment by thijstriemstra** [comment]
A realtime "color-scheme-switcher" example for wavesurfer.js would be nice as well..
