### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by Dispelda** [wavesurfer-js/wavesurfer.js#1941]
#Window is not defined

HI, everyone

I'm trying to use wavesurfer on my nodejs applications. 
and i have this error:

```
ReferenceError: window is not defined
```

**Comment by thijstriemstra** [comment]
Maybe this pull request will fix this for you, can you give it a try?  #1938

**Comment by luokunman** [comment]
> 也许这个拉取请求会为你解决这个问题，你可以试一试吗？ #1938

I tried, but I still failed
