### ISSUE TITLE
Change cursor time to only seconds and play delay animate

### ISSUE THREAD

**Issue by adamiusz** [wavesurfer-js/wavesurfer.js#1945]
How I can round the time shown in cursor time to whole seconds?

>                             customShowTimeStyle: {
>                                     'background-color': '#456789',
>                                     color: '#fff',
>                                     padding: '2px',
>                                     'font-size': '10px',
>                             }    

           
Second question. Is it possible to delay when I click on waveform for 0.3 seconds before progressColor jumps to where I clicked and animate this?

Very thank for help.

>                               var file =  jQuery("#waveform"); 
>                               jQuery("body").on("click", file, function() {     
>                                     Spectrum.play();
>                               });

**Comment by thijstriemstra** [comment]
Use the `formatTimeCallback` option to override default method, see https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/cursor.js#L307

>  Is it possible to delay when I click on waveform for 0.3 seconds before progressColor jumps to where I clicked and animate this?

There is no code implemented for this.

**Comment by adamiusz** [comment]
What I must give as a value if i want only minutes and seconds?

I Google this plugin, but i can't use this.

**Comment by adamiusz** [comment]
I have question. How stop wavesurfer if I know only container name, because i dont know how i can make unique `var spectrum_name` ??


```
            var spectrum_name = WaveSurfer.create({
                container: file,
                height: 40,
                barHeight:2,
                waveColor: '#ffffff',
            });
```

**Comment by thijstriemstra** [comment]
I don't know what `Spectrum` is. Always paste complete examples that reproduce the issue.

**Comment by adamiusz** [comment]
Spectrum is istance wavesurfer
