### ISSUE TITLE
Black bars showing when moving regions

### ISSUE THREAD

**Issue by jsbroks** [wavesurfer-js/wavesurfer.js#1981]
### Wavesurfer.js version(s):

Whatever the docs page is using

### Browser and operating system version(s):

Chrome/Ubuntu

### Code needed to reproduce the issue:

http://wavesurfer-js.org/example/annotation/index.html

![image](https://user-images.githubusercontent.com/24920936/85486206-31992d00-b598-11ea-9bc0-11db704af440.png)

### Use behaviour needed to reproduce the issue:

Moving a region to the left cause the bars not to be cleared.

**Comment by sundayz** [comment]
maybe the canvas isn't being cleared properly every frame. Need someone who can test on ubuntu to fix this though
