### ISSUE TITLE
Show Wavebar automatically when the website loads.

### ISSUE THREAD

**Issue by Mathias79** [wavesurfer-js/wavesurfer.js#1991]
Hello,

on my website I offer my songs for download.

When I load my website, I would like the graphics (called "Wavebar"?) To be loaded **automatically for every song I offer there, without it being played.**

Here on the developer page (with the examples) the wavebars are displayed immediately:
https://wavesurfer-js.org/examples/

For me the Wavebar is only loaded after I have pressed the play button.

Is this possible?

Greetings
Mathias

**Comment by marizuccara** [comment]
Hi, maybe related with this? 
https://github.com/katspaugh/wavesurfer.js/issues/1924

**Comment by Mathias79** [comment]
Thank you! :-)
