### ISSUE TITLE
cursor.js Not found error in Plugin system example

### ISSUE THREAD

**Issue by marizuccara** [wavesurfer-js/wavesurfer.js#1993]
### Wavesurfer.js version(s):
4.0.1

### Code needed to reproduce the issue:
Going to example section of `plugin system`, it not works, because 404 error of `cursor.js` in `CursorCustomPlugin`. Locally in localhost works instead.

![image](https://user-images.githubusercontent.com/44341274/86530375-9027aa80-beb8-11ea-987c-0e3c3ab1ceeb.png)

**Comment by thijstriemstra** [comment]
is this related to #1992 or is it a different issue @marizuccara?

**Comment by marizuccara** [comment]
Different issue. The example at public wavesurfer.js address not works because it gives this error, but locally in localhost it find the file. So I don't know if there are necessary other configurations? Maybe it's necessary to import the `cursor.js` file in different way...
