### ISSUE TITLE
timeout load

### ISSUE THREAD

**Issue by adamiusz** [wavesurfer-js/wavesurfer.js#2010]
Is it possible to set the time until the wavesurfer tries to load the file?

Sometimes waveform won't load, but goes to play the file, and how do I fix it?

**Comment by thijstriemstra** [comment]
> set the time until the wavesurfer tries to load the file?

set what time? a timeout for the loading process?

**Comment by adamiusz** [comment]
Yes, because sometime waveform won't load but can play file and can fix it?

**Comment by sundayz** [comment]
Maybe for 5.0 we should look at converting methods like `load`, `destroy`, etc to use Promises instead. If load was async it would be easy to add timeout.

**Comment by thijstriemstra** [comment]
>  If load was async it would be easy to add timeout.

Sounds really good. Just a monumental task ;)

**Comment by sundayz** [comment]
Well in theory you can create a new Promise inside load and only resolve() it when the fetch request completes but I'm sure there will be complications somehow
