### ISSUE TITLE
How to implement wavesurfer on recordrtc?

### ISSUE THREAD

**Issue by dineshmaths1** [wavesurfer-js/wavesurfer.js#2022]
i am doing voice record using recordrtc . here how to use wavesurfer?

**Comment by thijstriemstra** [comment]
Take a look at videojs-record: https://collab-project.github.io/videojs-record/demo/audio-only.html

**Comment by dineshmaths1** [comment]
> Take a look at videojs-record: https://collab-project.github.io/videojs-record/demo/audio-only.html
> 
> It uses videojs-wavesurfer: https://collab-project.github.io/videojs-wavesurfer/demo/live.html

Safair browser is not supporting

**Comment by escobar5** [comment]
You can use wave-surfer's [microphone plugin](https://wavesurfer-js.org/plugins/microphone.html), and then initialize RecordRTC with the stream from the plugin, like this:

```
function initRecording() {

        var wavesurfer = WaveSurfer.create({
            container: $divParent,
            plugins: [
                WaveSurfer.microphone.create()
            ]
        });

        wavesurfer.microphone.on('deviceReady', function (stream) {
            var recorder = RecordRTC(stream, {
                type: 'audio',
                timeSlice: 1000,
            });
        });

        wavesurfer.microphone.start();
}
```

**Comment by DavidPetrasek** [comment]
Microphone plugin is now obsolete, how to do it with the new Record plugin?
