### ISSUE TITLE
Waveform is not always in sync with Audio when using `MediaElement` backend

### ISSUE THREAD

**Issue by iampava** [wavesurfer-js/wavesurfer.js#2028]
### Use behaviour needed to reproduce the issue:

1. Open the CodePen link
2. Wait for both waveforms to visibly load
3. Click **SEEK to 0.49** button
4. Play both tracks
5. Notice how everything is ok (when the gap begins, the sound is also silent)
6. Refresh page
7. Click **SEEK to 0.495** button
8. Play both tracks
9. **[BUG]** Notice how the tracks keep playing even though there's a gap there

What's weird is that swapping the `MediaElement` backend with the default one fixes the issue ;-?

**Comment by thijstriemstra** [comment]
> BUG] Notice how the tracks keep playing even though there's a gap there

The tracks don't keep playing when I test with Firefox 78 on Ubuntu 20.04.

**Comment by sundayz** [comment]
MediaElement is less accurate than WebAudio. You should use it if you need to support browsers without WebAudio.

See differences here:
https://github.com/katspaugh/wavesurfer.js/issues/676

There is also the MediaElementWebAudio backend which lets you play the track right away without waiting for it to be fully processed which could take a few seconds.
