### ISSUE TITLE
wavesurfer: true seamless loop as a basic function for the loaded audio file?

### ISSUE THREAD

**Issue by LuisTardiph** [wavesurfer-js/wavesurfer.js#2035]
Hi there,

I'm using wavesurfer version 3.3.3, the following codepen-examples were written and tested on Chrome Browser (Version 84.0.4147.105).
My issue:
I'm trying to play a soundfile, which I prepared local with my audiosoftware as a true seamless audiowaveform, in a real seamless loop in an online Web Audio Player.
Since I want to display also a good precise waveform in this player I came up to your wavesurfer, which is a real brillant player with visual waveform!
Here is a short sample with an audio file of 4s length - it plays just one time from start to end (with visualization of time running): https://codepen.io/luistardiph/pen/LYGvbEN
Unfortunately there is no function to set a true loop for the basic audio material as it is in a very raw web audio api player with audioContext (where I can set the source.loop = true; and it plays really seamless). I just could find the workaround by let the playing jump to beginning when it finishes. Here is the second example for this situation/solution: https://codepen.io/luistardiph/pen/GRoLNpM). But with clicking the cursor to different positions to start the playback from it looses the real clean seamless loop function and makes little glitches/clicks at the end of file jumping to the beginning.
The only possibility to reach a real seamless loop of this 4s example-file was to change the basic wavesurfer.js and to insert into the code a "this.source.loop = true;" (see the wavesurfer-mod.js here: https://www.aloisspaeth.com/script/wavesurfer-mod.js In a code editor the "this.source.loop = true;" is written in line 7574 ). But then the wavesurfer-player looses the updating function of the cursor's progress. You can have a look (and listen) to the example for this here: https://codepen.io/luistardiph/pen/zYrXoGO
So my questions are:
Is there a possibility to let the real seamless loop function (made possible through code-modification with "this.source.loop = true;") and just to update the cursor running? Or is there a way to give the wavesurfer this additional "source.loop=true"-function and yet to save the working update-function of the cursorbar progress?
For an answer to these questions I would be very thankful!

**Comment by LuisTardiph** [comment]
Hi there,

I'm using wavesurfer version 3.3.3, the following codepen-examples were written and tested on Chrome Browser (Version 84.0.4147.105).
My issue:
I'm trying to play a soundfile, which I prepared local with my audiosoftware as a true seamless audiowaveform, in a **real** seamless loop in an online Web Audio Player.
Since I want to display also a good precise waveform in this player I came up to your wavesurfer, which is a real brillant player with visual waveform!
Here is a short sample with an audio file of 4s length - it plays just one time from start to end (with visualization of time running): https://codepen.io/luistardiph/pen/LYGvbEN
Unfortunately there is no function to set a true loop for the basic audio material as it is in a very raw web audio api player with audioContext (where I can set the source.loop = true; and it plays really seamless). I just could find the workaround by let the playing jump to beginning when it finishes. Here is the second example for this situation/solution: https://codepen.io/luistardiph/pen/GRoLNpM). But with clicking the cursor to different positions to start the playback from it looses the real clean seamless loop function and makes little glitches/clicks at the end of file jumping to the beginning.
The only possibility to reach a real seamless loop of this 4s example-file was to change the basic wavesurfer.js and to insert into the code a "this.source.loop = true;" (see the wavesurfer-mod.js here: https://www.aloisspaeth.com/script/wavesurfer-mod.js In a code editor the "this.source.loop = true;" is written in line 7574 ). But then the wavesurfer-player looses the updating function of the cursor's progress. You can have a look (and listen) to the example for this here: https://codepen.io/luistardiph/pen/zYrXoGO
So my questions are:
Is there a possibility to let the real seamless loop function (made possible through code-modification with "this.source.loop = true;") and just to update the cursor running? Or is there a way to give the wavesurfer this additional "source.loop=true"-function and yet to save the working update-function of the cursorbar progress?
For an answer to these questions I would be very thankful!

**Comment by sundayz** [comment]
Your 2nd example works fine for me, the only problem is a little "click" sound.

We use wavesurfer for a web audio mixing tool and have the same issue with glitches happening with mp3 files, but they only happen the first time a track is played, not when clicking the cursor to different positions.

I did a bit of research, I think part of the problem could be the browser choosing the wrong settings for the audio. Sometimes the browser will choose 48000hz for a file, sometimes 44100hz. I don't know if this is the cause, but it might help... maybe creating an AudioContext with custom sample rate settings will help but I have not tested.

**Comment by LuisTardiph** [comment]
Hi,

nice to read this comment :) Thanks!
Yeah, this 2nd example works quite well, but it's not good enough even because of this little „click“ sound ;) I need the perfectly seamless loop ...!
Up til now I just can reach this goal by completely writing my own (simple?) code for this. You can have (mainly) a listen to it here: https://codepen.io/luistardiph/pen/rNeNzBN For this example I worked with the very basic way of creating an audio context and setting the source.loop property to „true“. The file is 24 seconds long (or let's say: In that case I made the .ogg-file of 24.008 seconds exactly 24 sec long ... later more...), you can even press „play/pause-toggle“ at any point of time (in different loop rounds) and the loop (e.g. at timestamps 24s, 48s, 72s and so on...) stays very safely seamless.
But it would be brillant to have all this with the wavesurfer visualization or with any visualization of progress bar and so on ...
Your bit of research sounds very interesting to me. I also came to this point with the 48 / 44.1 kHz thing. Maybe this also could be a solution. But one question: In the wavesurfer-doc actually I already read this: _„getAudioContext(): AudioContext; Get the audio context used by this backend or create one“._ But how do I create my own custom audio context (and then integrate it to the init wavesurfer object?)? Maybe you can give me a hint ...
And I also have a tipp for your use of wavesurfer for a audio mixing tool: This is a very common tipp for all working with audio-files (e.g. especially for seamless looping). For any compressed version ONLY USE .ogg-files (for Chrome and FF) and .m4a-files (for Safari)!!! It's hopeless to use mp3-files. I'm a sound professional and did a lot of tests. It has to do with the many different and special methods of compression. For example if you have a .wav or .aiff (uncompressed) file of exactly 4s (or any) length (and seamless loop cut again :D) and you convert it to mp3, there is added a minimal piece of sound-bits after the actual end of file (maybe only a few milliseconds, important: these bits have no sound anymore, it's silence or the 0-line, no waveforms). Then for example your new file is 4.00532 sec long and this leads to having gaps again, if you want to use this mp3 for seamless looping. With conversion to .ogg and .m4a very often (but unfortunately not always, so no guarantee for nothing ;) ...) there's nothing added. And all this is independent from 48 or 44.1 kHz.
As I experienced it's a very very tricky issue. But I'll keep hanging on!

**Comment by sundayz** [comment]
to use your own wavesurfer object you can give it to WaveSurfer when you call the `create` function:

```js
const myAudioContext = new AudioContext();
...
const wavesurfer = WaveSurfer.create({
    audioContext: myAudioContext,
});
```

you can see the options here: https://wavesurfer-js.org/docs/options.html

note that if you make your AudioContext object on page load, Chrome will prevent the audio from playing because of its "autoplay policy' and you will have to call the `resume()` method on AudioContext during a user action (For example when the user clicks the play button)

Thanks for your tip, youre probably right we should be using something other than mp3 :) 

Let me know if you solve the clicking issue, for me it always happens when audio starts playing, never when seeking or pausing audio.

**Comment by jie-chen** [comment]
Hi, is there any update on this?  Do we have to manually create AudioContext and pass it to wavesurfer? The region plugin just does not loop seamlessly.
> Hi,
> 
> nice to read this comment :) Thanks! Yeah, this 2nd example works quite well, but it's not good enough even because of this little „click“ sound ;) I need the perfectly seamless loop ...! Up til now I just can reach this goal by completely writing my own (simple?) code for this. You can have (mainly) a listen to it here: https://codepen.io/luistardiph/pen/rNeNzBN For this example I worked with the very basic way of creating an audio context and setting the source.loop property to „true“. The file is 24 seconds long (or let's say: In that case I made the .ogg-file of 24.008 seconds exactly 24 sec long ... later more...), you can even press „play/pause-toggle“ at any point of time (in different loop rounds) and the loop (e.g. at timestamps 24s, 48s, 72s and so on...) stays very safely seamless. But it would be brillant to have all this with the wavesurfer visualization or with any visualization of progress bar and so on ... Your bit of research sounds very interesting to me. I also came to this point with the 48 / 44.1 kHz thing. Maybe this also could be a solution. But one question: In the wavesurfer-doc actually I already read this: _„getAudioContext(): AudioContext; Get the audio context used by this backend or create one“._ But how do I create my own custom audio context (and then integrate it to the init wavesurfer object?)? Maybe you can give me a hint ... And I also have a tipp for your use of wavesurfer for a audio mixing tool: This is a very common tipp for all working with audio-files (e.g. especially for seamless looping). For any compressed version ONLY USE .ogg-files (for Chrome and FF) and .m4a-files (for Safari)!!! It's hopeless to use mp3-files. I'm a sound professional and did a lot of tests. It has to do with the many different and special methods of compression. For example if you have a .wav or .aiff (uncompressed) file of exactly 4s (or any) length (and seamless loop cut again :D) and you convert it to mp3, there is added a minimal piece of sound-bits after the actual end of file (maybe only a few milliseconds, important: these bits have no sound anymore, it's silence or the 0-line, no waveforms). Then for example your new file is 4.00532 sec long and this leads to having gaps again, if you want to use this mp3 for seamless looping. With conversion to .ogg and .m4a very often (but unfortunately not always, so no guarantee for nothing ;) ...) there's nothing added. And all this is independent from 48 or 44.1 kHz. As I experienced it's a very very tricky issue. But I'll keep hanging on!
