### ISSUE TITLE
Regions plugin: Microsoft Edge: resize cursor not always appearing

### ISSUE THREAD

**Issue by NiallTracey** [wavesurfer-js/wavesurfer.js#2053]
### Wavesurfer.js version(s):
Version as per demo at https://wavesurfer-js.org/example/annotation/index.html and currently 

### Browser and operating system version(s):
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

Windows 10 
v 1909
build 18363.1016

### Code needed to reproduce the issue:

Having experience this issue in my own code I verified that the same thing happens in the "annotations" example -- no additional code needed for verification.

### Use behaviour needed to reproduce the issue:

Resizing regions works as expected in Firefox and Chrome. (However, it is quite fiddly as it seems to be a single-pixel detection zone, which doesn't leave much margin for error.)

However, when I attempt to use it in Microsoft Edge, I find that the resize cursor doesn't appear for all regions. It behaves consistently in that if it works on one region, and I move off and back over the region boundary it will appear again; if it doesn't appear when I'm over the pixel and then I move off it won't appear when I move back over the same pixel.

In order to get it to work, I have to use the webpage zoom to zoom very close in.

I suspect that this is due to some kind of anti-aliasing in the rendering engine -- i.e. that Edge is allowing both the resize bar and the region block to share a pixel and is triggering the drag event for the area and suppressing the drag event for the boundary.

**Comment by thijstriemstra** [comment]
Is this the Chrome based edge or the old one?

**Comment by NiallTracey** [comment]
Old/legacy (single colour logo) -- hence EdgeHTML in the browser details.

I'm going to be sticking with it for a while, as Edge isn't my main browser anyway, and I only use it for checking compatibility. Seems to me that having yet another Chromium based browser installed won't help in that regard.

**Comment by sundayz** [comment]
You can set a region's handleStyle, or write a css selector for `.wavesurfer-handle` and do `width: 3px !important;` to make the handle wider and easier to grab! :) I agree that 1px is not a great default especially for mobile, but it's easy to change and style however you want.
