### ISSUE TITLE
create copy of player in footer from listing of Audio instance

### ISSUE THREAD

**Issue by ak84513** [wavesurfer-js/wavesurfer.js#2056]
Unable to create two intance of player one in listing and another in bottom like soundcloud. I have go through  #1496 but it is not working.

**Comment by sundayz** [comment]
the easiest solution is to create 2 instances of wavesurfer.

The other solutions involve things like using 1 fullscreen canvas to draw two waves, or using getImage and putImage to copy and paste from one canvas to another.

There's no easy way to share resources across 2 html5 canvases as far as I know
