### ISSUE TITLE
Need to insert image inside Wave Spectrum using wavesurfer.js

### ISSUE THREAD

**Issue by M-Sharjeel-Tariq** [wavesurfer-js/wavesurfer.js#2057]
First of all THANK YOU SO MUCH for such an awesome library.
It is helping me so much in a project.
Only thing left is to insert the image inside the wave spectrum.
(Image is attached)
Is it possible with wavesurfer.js? If not, can anyone suggest me a solution?

![WhatsApp Image 2020-08-31 at 5 44 45 PM](https://user-images.githubusercontent.com/22858080/91721395-1f4bf880-ebb2-11ea-9b4d-ae449c798b5a.jpeg)

**Comment by sundayz** [comment]
The waveform is drawn on a html5 canvas so you can extend `drawer.multicanvas.js` or `drawer.canvasentry.js` to create your own renderer. Then you can use the html5 canvas functions to draw the image and the waves however you like.

Not easy, but it is possible.
