### ISSUE TITLE
setSinkId result in no sound

### ISSUE THREAD

**Issue by mtdallaire** [wavesurfer-js/wavesurfer.js#2060]
When the setSinkId (audio output) is set I get no sound.

I tried all my ids. Same result.

I found no example on how to use it in your documentation or even projects using your api 

Kind Regards,

Michel

wavesurfer.js 4.0.1 (2020-06-24)
Google Chrome Version 85.0.4183.83 (Build officiel) (64 bits)
Windows 10 Pro

**### Code needed to reproduce the issue:**
```html
<script src="https://unpkg.com/wavesurfer.js/dist/wavesurfer.js"></script>
<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.timeline.js"></script>
<div id="waveform1"></div>
<div id="wave-timeline1"></div>
```

And

```javascript
var wavesurfer1 = WaveSurfer.create({
    container: '#waveform1',
    plugins: [
        WaveSurfer.timeline.create({
            container: '#wave-timeline1'
        })
    ]
});
wavesurfer1.setSinkId('dfccbba84300484c7ab1610620f1241b27c83dee5f87422d068996401a7039c7');
wavesurfer1.load('/a.mp3');

wavesurfer1.on('ready', function () {
    wavesurfer1.setVolume(1);
    wavesurfer1.play();
});

```

**I'm able to get all my devices with this:**

```javascript
	// List cameras and microphones.
(async () => {   
	  await navigator.mediaDevices.getUserMedia({audio: true, video: true});   
	  let devices = await navigator.mediaDevices.enumerateDevices();   
	 // console.log(devices); 
	})();

	navigator.mediaDevices.enumerateDevices()
	.then(function(devices) {
	//	console.log(devices);
	  devices.forEach(function(device) {
	      //if (device.kind=="audiooutput"){
	    console.log(device.kind + ": " + device.label +
	                " id = " + device.deviceId);
	     // }
	  });
	})
	.catch(function(err) {
	  console.log(err.name + ": " + err.message);
	});
```

**Comment by thijstriemstra** [comment]
> I'm able to get all my devices with this:

can you show console log output for that?

**Comment by mtdallaire** [comment]
I placed my code temporarely on a server.  You can see it all  :-)
https://www.turbo-online.com/test4.php


but here is the console:
audioinput: Par défaut - Console XENYX USB Input  (4- USB Audio CODEC ) (08bb:2902) id = default
test4.php:37 
audioinput: Communications - Console XENYX USB Input  (4- USB Audio CODEC ) (08bb:2902) id = communications
test4.php:37 
audioinput: Console XENYX USB Input  (4- USB Audio CODEC ) (08bb:2902) id = 1753ec1f139ac33647d62ee4cd74d17d9e13a93247d9ce30a982a07557ed4b95
test4.php:37 
videoinput: GENERAL WEBCAM (1b3f:2002) id = 832029ff96d4c8c2b541bda4f2bf0f5ac03315088eed0cfa4a7812b97b38be98
test4.php:37 
audiooutput: Par défaut - Haut-parleurs (Realtek High Definition Audio) id = default
test4.php:37 
audiooutput: Communications - Console XENYX (4- USB Audio CODEC ) (08bb:2902) id = communications
test4.php:37 
audiooutput: Haut-parleurs (Realtek High Definition Audio) id = f218d95fa42981b1e4a049637c2549323a7305ba703768b37010047dff232022
test4.php:37 
audiooutput: Écran Samsung HDMI (AMD High Definition Audio Device) id = dfccbba84300484c7ab1610620f1241b27c83dee5f87422d068996401a7039c7
test4.php:37 
audiooutput: Concentrateur USB (USB audio CODEC) (08bb:2912) id = 104fdb1827e4013ef29251362b62583e56812472f933ddb5ec88c72095083545
test4.php:37 
audiooutput: Console XENYX (4- USB Audio CODEC ) (08bb:2902) id = 2ceb5a9ba9f9cff66e108e5fa05bb4cee70058b5f4191c535114783a81bc7ddc

**Comment by thijstriemstra** [comment]
can you also try with firefox?

**Comment by mtdallaire** [comment]
I currently don't have FF installed. I will have to do that much later.

**Comment by mtdallaire** [comment]
It's worst in FF, because it's unsuported. 

Promise { <state>: "rejected" }
test4.php:66:9
Uncaught (in promise) Error: setSinkId is not supported in your browser
    setSinkId webaudio.js:304
    setSinkId wavesurfer.js:941
    <anonymous> test4.php:66
webaudio.js:304:20
Uncaught (in promise) Error: setSinkId is not supported in your browser
    setSinkId webaudio.js:304
    setSinkId wavesurfer.js:941
    <anonymous> test4.php:78
webaudio.js:304:20
videoinput: GENERAL WEBCAM id = ZV/4SrvLHLwYUMPTj/dAl0uKdEEo8Jviqd9Ka56sASA= test4.php:37:14
audioinput: Console XENYX USB Input  (4- USB Audio CODEC ) id = z756GZX3ICvHG7Abon3RPNMJk7dn4VOKadITHVDKNzA= test4.php:37:14
GEThttps://www.turbo-online.com/favicon.ico
[HTTP/2 404 Not Found 0ms]

**Comment by mtdallaire** [comment]
any suggestions ?  :)
