### ISSUE TITLE
Regions plugin params documentation problems

### ISSUE THREAD

**Issue by Lightn** [wavesurfer-js/wavesurfer.js#2076]
### Wavesurfer.js version(s):
4.1.1

https://github.com/katspaugh/wavesurfer.js/blob/97ec87605c08e2f29e5cec8c359518e2076fb24e/src/plugin/regions/index.js#L12-L14
The `RegionsPluginParams` documentation for `maxRegions` has the type as `number[]`, when it is really just a number, not an array of numbers.  It also says `initPlugin('regions')` in the description, which I believe belongs to the previous property `deferInit`.

https://github.com/katspaugh/wavesurfer.js/blob/97ec87605c08e2f29e5cec8c359518e2076fb24e/example/regions/index.html#L91-L93
The regions example is initializing the dragSelection parameter incorrectly, it should be like this:
```
    dragSelection: true,
    slop: 5
```

**Comment by thijstriemstra** [comment]
thanks for the report @Lightn. Can you make these changes in a pull request so it can be fixed?
