### ISSUE TITLE
Deleting / trimming selected regions in the wave form

### ISSUE THREAD

**Issue by woniesong92** [wavesurfer-js/wavesurfer.js#2084]
- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
4.1.1

### Browser and operating system version(s):
Chrome / MacOS

### Use behaviour needed to reproduce the issue:
![image](https://user-images.githubusercontent.com/2935309/94988427-f0fb6900-0521-11eb-80fc-1189fe46ea6c.png)

I want to "crop out" or delete a part of waveform. My current approach is this:
1. Create a region (the part you want to delete)
2. Hit delete key. This will create an array of deleted regions like so:
  ```js
  [{start_time: 1.00, end_time: 2.00}]
  ```
3. During playback, keep iterating the deleted regions and if the currentTime is in between any deleted region, skip to the next appropriate part

  ```js
  while (playing) {
    for (let i=0; i<deletedRegions.length; i++) {
      const {start_time, end_time} = deletedRegions[i];
      if (isInBetween(current_time, start_time, end_time)) {
        seekTo(end_time)
      }, 
    }
  }
  ```

This approach works pretty well except that I don't know how to hide the deleted regions from the waveform. Looked for some guidance in the docs and the source code but couldn't find it myself. I'd appreciate it if anyone could provide some insight here!

## Related issues
The suggestion in these related issues was manipulate the audio data in blob and load it to the wavesurfer again. I'm not sure if this approach will work with audios (or videos) whose length is more than a few minutes because of the time it takes to trim the audio and load it back into wavesurfer. Open to any suggestions though!

- https://github.com/katspaugh/wavesurfer.js/issues/419
- https://github.com/katspaugh/wavesurfer.js/issues/1627
- https://github.com/katspaugh/wavesurfer.js/issues/1952

**Comment by woniesong92** [comment]
For my specific use case, the audio source is from a HTML5 video element. I'm trying to see if it's possible to use `ffmpeg.js` to create a new video without the selected region, which would force the wavesurfer to reload the entire video. I am not sure how quickly this can be done especially when the video is large. I'd still appreciate any insights :)

**Comment by sundayz** [comment]
The bottleneck will be ffmpeg not wavesurfer. you will have to show a loading indicator to users anyway. This is typically something you want to do on the server because it will take a long time and ffmpeg is quite heavy since it's c++ code transpiled to javascript.

I think you could get the peaks array from javascript, splice the removed peaks data out of the array, then reload the peaks. Re-drawing the waveform should be fast enough with preloaded peaks. The question is if wavesurfer allows you to replace the peaks without reloading the mp3
