### ISSUE TITLE
Different waveform on mobile and desktop

### ISSUE THREAD

**Issue by iftkharhussain** [wavesurfer-js/wavesurfer.js#2087]
I have integrated wavesurfer in my project, but it renders different wave design on desktop and mobile
see attachment

![image](https://user-images.githubusercontent.com/26545819/95403065-9f404d80-092a-11eb-8d19-d91d68e4f970.png)

![image](https://user-images.githubusercontent.com/26545819/95402927-57b9c180-092a-11eb-85cd-aa9cb56b1627.png)

**Comment by thijstriemstra** [comment]
> desktop and mobile

Why not mention what platforms and versions?

**Comment by sundayz** [comment]
Maybe try changing pixelRatio?

**Comment by iftkharhussain** [comment]
> Why not mention what platforms and versions?

window 10, Chrome 85, wavesurfer.js 4.1.1

**Comment by thijstriemstra** [comment]
And your wavesurfer config? sigh, have you read the ticket instructions?

**Comment by iftkharhussain** [comment]
var waveOptions = {
  container: '#waveform',
  barWidth: 1,
  hideScrollbar: true,
  height: 90,
  cursorWidth: 0,
  minPxPerSec: 2,
  responsive: true,
  waveColor: '#717171',
  barGap: 2,
  normalize: true
}

**Comment by thijstriemstra** [comment]
what mobile platform/versions etc?

**Comment by sundayz** [comment]
I can reproduce this with barWidth: 1. Not a platform problem I think. The size of the canvas seems to affect it. 

Maybe related?
https://stackoverflow.com/questions/8696631/canvas-drawings-like-lines-are-blurry
