### ISSUE TITLE
Bind wavesurfer.play() function to the interaction event reporting [Maximum call stack size exceeded] error

### ISSUE THREAD

**Issue by TimVan1596** [wavesurfer-js/wavesurfer.js#2088]
### Code:
```
    wavesurfer.on('interaction', function () {
        wavesurfer.play()
    });

```

### Console error message : 
wavesurfer.min.js:4329 Uncaught RangeError: Maximum call stack size exceeded
    at WaveSurfer.play (wavesurfer.min.js:4329)

### Use behaviour :
I want to continue playing the audio directly when I click on the waveform
So I bind **wavesurfer.play()** function to the **interaction** event
But the console keeps reporting errors

### versions
wavesurfer.js 4.1.1,  Google Chrome 85,  Windows 10

**Comment by TimVan1596** [comment]
I found another way to avoid this problem
make wavesurfer.play() as the onclik function of a button
like this:
```
    wavesurfer.on('interaction', function () {
            document.getElementById("temp-pausebtn").click()
    });
```

**Comment by sundayz** [comment]
```js
    wavesurfer.on('interaction', function () {
        wavesurfer.setDisabledEventEmissions(['interaction']);
        wavesurfer.play()
        wavesurfer.setDisabledEventEmissions([]);
    });
```

You could do this as a workaround. The problem is that play() will fire an 'interaction' event I guess. Probably because play() calls seekTo()

**Comment by entonbiba** [comment]
@TimVan1596 adding `play()` to the interaction event will fire every time. Instead call the `play()` on the `seek` event.
