### ISSUE TITLE
Timeline plugin: the displayed time is less than the duration of the time

### ISSUE THREAD

**Issue by ICYMYM** [wavesurfer-js/wavesurfer.js#2090]
There is an mp4 file with duration: 00:59:27, but when I use timeline plugin, the displayed time is 00:40:00+, It seems that part of it is not displayed.

![image](https://user-images.githubusercontent.com/3919539/95706603-dd6ea180-0c89-11eb-8b8b-a288efd41ab1.png)

![image](https://user-images.githubusercontent.com/3919539/95706535-b4e6a780-0c89-11eb-9440-beb5cf218e7f.png)

wavesurfer.js: 3.3.1

**Comment by ICYMYM** [comment]
This is the mp4 file that has this issue, you could download from [here](https://drive.google.com/file/d/1X1o52yJuktvXQjat4x6fxxnDrQUNqE6p/view?usp=sharing)

**Comment by thijstriemstra** [comment]
@ICYMYM what if you open the mp4 in a browser, does it report the correct duration in the audio player?

**Comment by mayurshinde4590** [comment]
@thijstriemstra ,
how  we can add vertical (y -axis ) timeline to wavesurfer.js

**Comment by ICYMYM** [comment]
> @ICYMYM what if you open the mp4 in a browser, does it report the correct duration in the audio player?

Yes, the duration is correct when it was opened in the chrome, but I found that a part of this video is muted. Is this the reason?
