### ISSUE TITLE
Waveform not showing on ios 13

### ISSUE THREAD

**Issue by kenjoegolo** [wavesurfer-js/wavesurfer.js#2091]
Hi I tried to use this great library on my ionic-react + capacitor app, the build was successful and the audio is playing but the waveform is not showing. I already tried the pre-rendered peak and still same problem not showing up the waveform.

can someone point me an example? thanks!!

**Comment by sundayz** [comment]
Share your wavesurfer config, any errors in the console, and pictures if necessary (is the waveform blank? are any lines showing? etc)

**Comment by egaudrain** [comment]
I also couldn't get it to work in Safari 14.0.1 with the current version of wavesurfer.js (4.2.0) when using WebAudio as backend. However, it worked when using the MediaElement backend and passing the peaks and duration when calling `load()`. I haven't tried the hybrid backend MediaElementWebAudio.

**Comment by sundayz** [comment]
Seems like some combination of peaks / no peaks + backend causes a single line to be drawn with no error. This is on Windows/Firefox. But I am using an old version of wavesurfer (4.1.1), I will test with a newer version later.

**Comment by entonbiba** [comment]
@kenjoegolo can you try adding `barWidth: 1` and check if that draws anything with react?

**Comment by davidecampello** [comment]
Hello, I'm having the same issue using ionic/angular with capacitor app.
In my configuration i have barWidth: 1, but it's not working..
I tried with iphone 6/ios 12 and with iphone 12 ios 14 (both on emulator)
I can share my code if It can hep

Thanks
Davide

**Comment by davidecampello** [comment]
I created a little demo to reproduce the problem.
You can fint here:
https://github.com/davidecampello/ionic-capacitor-wavesurfer-test

Many thanks for this awesome package
