### ISSUE TITLE
waveform draw fails silently with short sounds at certain window widths, esp on hi dpi displays

### ISSUE THREAD

**Issue by marcelblum** [wavesurfer-js/wavesurfer.js#2095]
### Wavesurfer.js version(s):
4.1.1

### Browser and operating system version(s):
observed on at least Windows latest FF & Chrome, Mac latest Chrome, probably others

### Code needed to reproduce the issue:
https://codepen.io/keymapper/pen/XWKdwvz?editors=0010

### Use behaviour needed to reproduce the issue:
With very (very) short sounds, the waveform is blank on responsive wavesurfer elements if the window is set wide enough, regardless of `minPxPerSec` setting, and with no firing of the 'error' callback. The above codepen loads 3 short drum sound waveforms (all around 0.1 seconds or less) in responsive mode. On my 2k desktop monitor the topmost sound waveform is always rendered blank at just about any window width, and if I maximize (2048x1040 reported `innerWidth` but this is scaled with `window.devicePixelRatio` of 1.25) the top 2 are blank. On my 13" macbook pro retina display if I maximize all 3 turn blank. In all cases if I resize the window width small enough the waveform comes back into view. It seems like some threshold is reached where `minPxPerSec` has no effect, but ideally wavesurfer should catch this situation and adjust the `minPxPerSec` automatically even if it means a pixelated waveform (or at least partially fill the container or fire an error rather than be blank). It seems like differing system scaling settings and monitor hi-dpi-ness comes into play here as well.

**Comment by thijstriemstra** [comment]
can you add some comparison screenshots @marcelblum ?

**Comment by marcelblum** [comment]
Sure. Here is what that Codepen looks like on a retina Macbook Pro in latest Chrome with default display settings (`window.devicePixelRatio` is 2).

If I shrink the browser window to as narrow width as Chrome allows (`window.innerWidth` is 500), the topmost waveform render fails silently and appears blank:
<img width="612" alt="Screen Shot 2020-10-23 at 1 48 11 PM" src="https://user-images.githubusercontent.com/1031177/97038365-b2f9cf80-1538-11eb-9bf6-8d969c989610.png">

If I expand it a bit more (`window.innerWidth` is 1047), the top 2 waveforms are blank:
<img width="1159" alt="Screen Shot 2020-10-23 at 1 48 44 PM" src="https://user-images.githubusercontent.com/1031177/97038377-b7be8380-1538-11eb-9290-1317f176bf44.png">

And if I fullscreen the window (`window.innerWidth` is 1440), all 3 are blank:
<img width="1440" alt="Screen Shot 2020-10-23 at 1 55 02 PM" src="https://user-images.githubusercontent.com/1031177/97038397-c147eb80-1538-11eb-8253-bf61b1e7ae18.png">

On this retina machine I can't get the topmost waveform to display at any width in Chrome, Firefox, or Safari, but that's because all those browsers limit the user to shrinking the window width to around the same 500px (scaled). **However** just FYI, I am developing an Electron app that uses Wavesurfer, and that uses the Chromium engine but with no limits on window width, and when I test in an Electron window I can get even that topmost shortest soundfile waveform to display if I shrink it down to around `window.innerWidth` of 207.

**Comment by thijstriemstra** [comment]
I would not test this with codepen, who knows what extra resize code they add to make it work for their UI?

**Comment by marcelblum** [comment]
Sure, here's the same demo in a standalone page on my own server:
https://soundplant.org/wavesurfer/wavesurferresizebug.html

**Comment by entonbiba** [comment]
@marcelblum just add `barWidth: 1,` to fix it

![image](https://user-images.githubusercontent.com/5193884/105643481-1b20c000-5e5e-11eb-936f-7d69987b3384.png)

**Comment by marcelblum** [comment]
Thank you @entonbiba yes it does render successfully if bar drawing mode is enabled (though I prefer the non-bar wave mode so this is not quite a "fix"). Any idea how to detect this situation, when the sound is too short to draw on the user's width? Like what is the threshold ratio of sound length to container width (to devicePixelRatio?) that could cause this? Seems to me this happens with sounds < 0.15s consistently on the machines I've tested on but it would be nice to know the math behind it so I can catch it.

**Comment by marcelblum** [comment]
BTW even in bar mode calls to `zoom` fail silently on these very short sounds.

**Comment by entonbiba** [comment]
@marcelblum can you try with `barWidth: 0.05` ? lower it even more to see the difference

**Comment by marcelblum** [comment]
On my 2k display lowering `barWidth` does change the look a bit but not much - it results in the bars being a little less defined and to be honest it makes it look worse IMHO. But thanks for the tip about using `barWidth` with short sounds like this as at least it allows some waveform to be displayed in these cases. For now for my own use case I'm working around this by checking if the sound is <0.15s and if so switch to bar mode and disable zooming. There's not much reason to need to zoom on a sound so short anyway.

**Comment by entonbiba** [comment]
@marcelblum Yes, this is because of the amount of peak data in the audio data file itself. I made the following for you using the `ana-hat-closed.wav` file, feel free to use it if you want for sounds smaller than 1 second.
https://www.entonbiba.com/lab/wavesurfer/2095.html 

![image](https://user-images.githubusercontent.com/5193884/105932242-a0e96a80-601a-11eb-9551-8fdc30c0d322.png)

**Comment by marcelblum** [comment]
Thanks @entonbiba, I think you were able to get it to look a little better than I was getting myself by tweaking some of those options.

**Comment by entonbiba** [comment]
@marcelblum glad I could help, we will look into the issue with audio being less than a second long which doesn't render peaks without the barwidth being enabled.

**Comment by thijstriemstra** [comment]
> I think you were able to get it to look a little better than I was getting myself by tweaking some of those options.

Can someone summarize status of this ticket?

**Comment by marcelblum** [comment]
@thijstriemstra IMO it's still a bug at least because the `error` event is not emitted in this situation, but certainly a low priority one with an easy workaround now that I know how to handle it.

**Comment by wxfred** [comment]
Still has problem when add Spectrogram plugin.
Change the audio url to _https://soundplant.org/wavesurfer/ana-hat-closed.wav_ in [https://wavesurfer.xyz/examples/?spectrogram.js](https://wavesurfer.xyz/examples/?spectrogram.js), it shows a white screen without any error.
