### ISSUE TITLE
Exporting Filtered Audio Data As File

### ISSUE THREAD

**Issue by deju1980** [wavesurfer-js/wavesurfer.js#2100]
Hi,

I'm looking for a way to export filtered audio as a file. I currently have a web app with an eq, timestretch and pitch filters, and would like to create a file for download with these filters applied. I've managed to successfully create a wav file (using the following method: https://stackoverflow.com/questions/60079764/how-to-export-wavesurfer-js-as-audio-file), however the filters aren't applied to the output. Is there a way to do this with wavesurfer.js?

**Comment by marizuccara** [comment]
Hi, you can try to implement and use an AudioWorkletNode connected at the end of your audio graph (because at the end you have your filtered data). Then you can implement an AudioWorkletProcessor class. Processors have the advantage that run in an different worklet.

**Comment by entonbiba** [comment]
@deju1980 how are you applying the filters currently? The final node of the output you may get with the following which will return the `AudioDestinationNode`.

``` javascript
wavesurfer.backend.getAudioContext().destination
```

**Comment by enischa** [comment]
anyone find the solution? i need too :(
