### ISSUE TITLE
Waveform crashing when trying to load audio file from Amazon S3

### ISSUE THREAD

**Issue by techiexplorer** [wavesurfer-js/wavesurfer.js#2105]
### Wavesurfer.js version(s):
Waveform version: 4.2.0

### Browser and operating system version(s):
Brave Browser on Ubuntu 20.04 LTS

### Code needed to reproduce the issue:
same code as described in the documentation.
(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:
1. Uisng wavesurfer.load(audioFileS3Url)
2. working for 1st time when page reloads.
3. when reloading page again, it's not working this time. page is getting hung and crashing after around 10 seconds no idea why. 
4. I am not facing this issue when I am loading audio file from my current website path itself.
5. Tried with both the backend options => 'MediaElement' and 'WebAudio'
6. I had to add `fetchRequest.headers["Access-Control-Allow-Origin"] = "*"` to get away with origin cross origin issue.

What might be the issue? Lemme know if more clear details or any other details need to be provided for debugging. Thank you!

**Comment by marizuccara** [comment]
Hi, how long is your audio? Using MediaElement backend, you've passed peaks to the load method?

**Comment by techie-explorer** [comment]
> Hi, how long is your audio? Using MediaElement backend, you've passed peaks to the load method?

- No I didn't pass any peaks.
- Audio is about 5-10 seconds. Really small!

**Comment by marizuccara** [comment]
Mhmm, you took a look on network calls or if there are memory leaks?

**Comment by techie-explorer** [comment]
Yes, I didn't find any memory leaks. But I observed that when wavesurfer instance is initialised and load audio file method is called but the audio it not received, the browser is crashing!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by marizuccara** [comment]
Can you try to pass the audio peaks (also fake), to try to understand if the problem is in the audio resource of in drawing the waveform?

**Comment by techie-explorer** [comment]
Yeah sure, will try and update you on this, thanks!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by interactionsolutions** [comment]
I have retrieving and playing from S3 bucket working 100%.
I have many thousands of objects, which are recordings in a folder in an S3 bucket.
I display them in a table using Tabulator (another great js library).
The first column is an icon. when clicked it reads a mysql database for the name of the file I wish to play.
I make a call from my .js library  
....
      await fetch("../includes/getS3AudioFile.php?audiofile=" + audiofile)
        .then(function (response) {
          return response.blob()
        }).then(function (audiofile) {
          audioblob = audiofile
        })
   ....
  
Inside the getS3AudioFile.php ....
try {
    // Get the object.
    $result = $s3->getObject([
        'Bucket' => $bucket,  // My bucket name
        'Key'    => $audiofile,  // the name of the file i want to play
    ]);
    echo $result['Body'];
} catch (S3Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}
It returns a blob. which I then load into wavesurfer.
  wavesurfer.loadBlob(audioblob)
Then play it.     wavesurfer.play();

When I want to play another file i have a stop playing function which is called on the 'play'  and 'Stop' buttons. this function does a bunch of things. I think the line you might be looking for is wavesurfer.destroy().
This effectively removes wavesurfer.
Then it loads the new object from S3.

I hope this is useful. have a look at interactionsolutions.com.au and you will get an idea of what it does.

**Comment by thijstriemstra** [comment]
> when reloading page again, it's not working this time. page is getting hung and crashing after around 10 seconds no idea why.

Probably related to the browser you're using: Brave Browser on Ubuntu 20.04 LTS I consider it alpha quality software and I personally don't intend to provide support for it.

**Comment by entonbiba** [comment]
@techie-explorer `await fetch` any reason you are using this? Also have a look at this aws article regarding streaming and s3 files.
https://aws.amazon.com/blogs/developer/streaming-amazon-s3-objects-from-a-web-server-2/
