### ISSUE TITLE
Set wavesurfer visible waveform to a specific window 

### ISSUE THREAD

**Issue by larrywal** [wavesurfer-js/wavesurfer.js#2106]
I'm trying to use wavesurfer with another timeline that allows people to set items to an audio track.  I want to be able to specify the specific start of the waveform and the end of it.

I've figured out how to use MinPxPerSec combined with control width to get the zoom state synchronized.  But when I pan my other timeline I need to change what renders in the waveform (and vice versa).  Can anyone help?

I've tried using SeekTo and SeekToAndCenter but I don't want to change what's currently playing - just the view.

**Comment by marizuccara** [comment]
Hi, instead of using `seekAndCenter`, you can use drawer features, as ` drawer.recenter(progress)` to handle only the visualization
