### ISSUE TITLE
Asynchronous non blocking peaks generating plugin

### ISSUE THREAD

**Issue by robert8888** [wavesurfer-js/wavesurfer.js#2125]
For anybody who have this problem in his use case (like me). I create plugin witch change default behavior of WebAudio backend.

[NPM](https://www.npmjs.com/package/wavesurfer.js-async)

I posted this to mark author/collaborators that in some case this is a problem, and my solution (for shure not most elegant)  can be some 'inspiration' for further development.

---

I only add to README of plugin that in my opinion getPeaks function can work even faster if both channels will be processed parallel in this same time. Now getPeaks function runs a big loop for one channel and then next one for the second channel. But both channel are equal length, so this can be done in one loop.  To keep performance will be better to avoid nested loops in big one to make computes for each channel so i think this can be hardcoded for two channels.  But this create problem with rare case with more that 2 channels.  So to consider is make faster function for two channels and slower for general purpose. I think that 99% user use only stereo audio files.

**Comment by sundayz** [comment]
This sounds very useful. Nice to see people making wavesurfer plugins. Maybe there should be a page where we list popular plugins.

**Comment by thijstriemstra** [comment]
Why did you decide not to contribute this to wavesurfer.js project? I could also not find the code for the repository, I guess it's not open source?

**Comment by sundayz** [comment]
It took me a while to find it but you can download the zip here: https://registry.npmjs.org/wavesurfer.js-async/-/wavesurfer.js-async-1.0.7.tgz

I haven't benchmarked this but I'm not sure how much it improves performance. I imagine the biggest bottleneck by far is decodeAudioData which we can't really do anything about.

**Comment by robert8888** [comment]
sorry. i don't put link to repo in package.json
i will update it. 
https://github.com/robert8888/wavesurfer-async-processing-plugin
