### ISSUE TITLE
Option to include progress canvas in exportImage

### ISSUE THREAD

**Issue by MrSnoozles** [wavesurfer-js/wavesurfer.js#2130]
Hello everyone,

I currently have a use case where I need to `exportImage` **with the progress**. Is there a workaround to achieve that?

### Code needed to reproduce the issue:

~~~js
wavesurfer.load('audiofile.wav');

wavesurfer.on('ready', function() {
  wavesurfer.seekTo(0.5);

  setTimeout(function() {
    // this should return the image with the active progress (0.5), so the first half should have another color than the second
    document.getElementById('result').src = wavesurfer.exportImage();
  }, 50);
})
~~~

https://repl.it/@MrSnoozles/CautiousStarkFactor

### Components and versions

* Wavesurfer.js version: 4.2.0
* Windows 10 Pro, Firefox 83

**Comment by thijstriemstra** [comment]
Wave and progress are drawn on 2 separate canvas elements.

Currently only the wave is exported: https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.canvasentry.js#L375

You would have to take both canvas instances and merge them together. If you come up with an implementation it might be worth including it in wavesurfer, so please open a pull request in that case.
