### ISSUE TITLE
Ability to only display portion of track

### ISSUE THREAD

**Issue by fitness23** [wavesurfer-js/wavesurfer.js#2131]
There doesn't appear to be a way of loading just a portion of a bigger track.
If my track is 60 seconds long. How could I just load from 5 seconds in and just play 10 seconds of it?

**Comment by sundayz** [comment]
Unfortunately, Wavesurfer uses the Web Audio API, which needs to download the whole file before it can be decoded. This is a problem with all browsers.

But just playing the audio file in chunks (no visual) is something the browser already does. When you listen to an audio file it gets loaded in chunks.

You can specify the time range, you don't need wavesurfer for this:
https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery#Specifying_playback_range

**Comment by fitness23** [comment]
@sundayz thanks for your reply. I don’t mind loading the whole file, but after it’s all loaded, is there a way I can amend the waveform to only show the portion I want?

**Comment by sundayz** [comment]
https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L154

drawWave and drawPeaks both take a start and end parameter so I think you can.

**Comment by qingwufong** [comment]
I have same question that how to draw waveform with a time range.

**Comment by qingwufong** [comment]
> I have same question that how to draw waveform with a time range. @thijstriemstra

I found It works that slice audio buffer with start and end time. code like this:
``` javascript
    const sliceAudiobuffer = (audioBuffer, start, end) => {
    // channels and sample rate
    const channels = audioBuffer.numberOfChannels;
    const rate = audioBuffer.sampleRate;
    // slice from start to end second
    const startOffset = rate * start;
    const endOffset = rate * end;
    // slice total frame count
    const frameCount = endOffset - startOffset;

    // create audio buffer with same sampleRate and same number of channels，and same frame count 
    const newAudioBuffer = new AudioContext().createBuffer(channels, endOffset - startOffset, rate);
    // create temp array for saving copyed data
    const anotherArray = new Float32Array(frameCount);
    // copy write channel data
    const offset = 0;
    for (let channel = 0; channel < channels; channel++) {
        audioBuffer.copyFromChannel(anotherArray, channel, startOffset);
        newAudioBuffer.copyToChannel(anotherArray, channel, offset);
    }
    return newAudioBuffer
  }
```

**Comment by thijstriemstra** [comment]
nice @qingwufong If you have time to add an example that uses this technique, that would be great.

**Comment by huueio** [comment]
> nice @qingwufong If you have time to add an example that uses this technique, that would be great.

Here is how I've implemented this (typescript) using @qingwufong's code

`
const loadAudioClip = async (
  ws: WaveSurfer,
  src: string, //URL of audio/video source
  start: number, //in seconds
  end: number //in seconds
) => {
  // https://github.com/katspaugh/wavesurfer.js/issues/2131#issuecomment-1053953907
  const sliceAudiobuffer = (
    audioBuffer: AudioBuffer,
    start: number,
    end: number
  ) => {
    // channels and sample rate
    const channels = audioBuffer.numberOfChannels;
    const rate = audioBuffer.sampleRate;

    // slice from start to end second
    const startOffset = rate * start;
    const endOffset = rate * end;

    // slice total frame count
    const frameCount = endOffset - startOffset;

    // create audio buffer with same sampleRate and same number of channels，and same frame count
    const newAudioBuffer = new AudioContext().createBuffer(
      channels,
      endOffset - startOffset,
      rate
    );
    // create temp array for saving copied data
    const anotherArray = new Float32Array(frameCount);
    // copy write channel data
    const offset = 0;
    for (let channel = 0; channel < channels; channel++) {
      audioBuffer.copyFromChannel(anotherArray, channel, startOffset);
      newAudioBuffer.copyToChannel(anotherArray, channel, offset);
    }
    return newAudioBuffer;
  };

  //#region Create audio buffer
  // https://stackoverflow.com/a/65798650
  const response = await fetch(src);
  const arrayBuffer = await response.arrayBuffer();
  const audioCtx = new window.AudioContext();
  let audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);

  // Slice audio buffer based on clip
  audioBuffer = sliceAudiobuffer(audioBuffer, start, end);
  //#endregion

  // Load audio buffer to wavesurfer
  ws.loadDecodedBuffer(audioBuffer);
};
`

**Comment by huueio** [comment]
`const loadAudioClip = async (
  ws: WaveSurfer,
  src: string, //URL of audio/video source
  start: number, //in seconds
  end: number //in seconds
) => {
  // https://github.com/katspaugh/wavesurfer.js/issues/2131#issuecomment-1053953907
  const sliceAudiobuffer = (
    audioBuffer: AudioBuffer,
    start: number,
    end: number
  ) => {
    // channels and sample rate
    const channels = audioBuffer.numberOfChannels;
    const rate = audioBuffer.sampleRate;
    // slice from start to end second
    const startOffset = rate * start;
    const endOffset = rate * end;
    // slice total frame count
    const frameCount = endOffset - startOffset;

    // create audio buffer with same sampleRate and same number of channels，and same frame count
    const newAudioBuffer = new AudioContext().createBuffer(
      channels,
      endOffset - startOffset,
      rate
    );
    // create temp array for saving copied data
    const anotherArray = new Float32Array(frameCount);
    // copy write channel data
    const offset = 0;
    for (let channel = 0; channel < channels; channel++) {
      audioBuffer.copyFromChannel(anotherArray, channel, startOffset);
      newAudioBuffer.copyToChannel(anotherArray, channel, offset);
    }
    return newAudioBuffer;
  };

  //#region Create audio buffer
  // https://stackoverflow.com/a/65798650
  const response = await fetch(src);
  const arrayBuffer = await response.arrayBuffer();
  const audioCtx = new window.AudioContext();
  let audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);

  // Slice audio buffer based on clip
  audioBuffer = sliceAudiobuffer(audioBuffer, start, end);
  //#endregion

  // Alternatively, can just use this
  ws.loadDecodedBuffer(audioBuffer);
};`

**Comment by huueio** [comment]
Here's how we've implemented this in Typescript using @qingwufong's code

```
const loadAudioClip = async (
  ws: WaveSurfer,
  src: string, //URL of audio/video source
  start: number, //in seconds
  end: number //in seconds
) => {
  // https://github.com/katspaugh/wavesurfer.js/issues/2131#issuecomment-1053953907
  const sliceAudiobuffer = (
    audioBuffer: AudioBuffer,
    start: number,
    end: number
  ) => {
    // channels and sample rate
    const channels = audioBuffer.numberOfChannels;
    const rate = audioBuffer.sampleRate;
    // slice from start to end second
    const startOffset = rate * start;
    const endOffset = rate * end;
    // slice total frame count
    const frameCount = endOffset - startOffset;

    // create audio buffer with same sampleRate and same number of channels，and same frame count
    const newAudioBuffer = new AudioContext().createBuffer(
      channels,
      endOffset - startOffset,
      rate
    );
    // create temp array for saving copied data
    const anotherArray = new Float32Array(frameCount);
    // copy write channel data
    const offset = 0;
    for (let channel = 0; channel < channels; channel++) {
      audioBuffer.copyFromChannel(anotherArray, channel, startOffset);
      newAudioBuffer.copyToChannel(anotherArray, channel, offset);
    }
    return newAudioBuffer;
  };

  //#region Create audio buffer
  // https://stackoverflow.com/a/65798650
  const response = await fetch(src);
  const arrayBuffer = await response.arrayBuffer();
  const audioCtx = new window.AudioContext();
  let audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);

  // Slice audio buffer based on clip
  audioBuffer = sliceAudiobuffer(audioBuffer, start, end);
  //#endregion

  // Alternatively, can just use this
  ws.loadDecodedBuffer(audioBuffer);
};
```
