### ISSUE TITLE
Regions plugin: 'out' event incorrectly emitted

### ISSUE THREAD

**Issue by sundayz** [wavesurfer-js/wavesurfer.js#2140]
### Wavesurfer.js version(s):
4.1.1

### Browser and operating system version(s):
Firefox Windows 10

### Code needed to reproduce the issue:

https://codepen.io/sundays/pen/VwKzmmL

### Use behaviour needed to reproduce the issue:
See codepen.

1. Click inside region
2. Click play, then quickly pause when still inside the region.
3. Click outside the region to seek.
4. Click play. Region emits the 'out' event, but it should not do it in this case.

Maybe need to unbind the in/out event handlers when seeking outside the region.

**Comment by thijstriemstra** [comment]
can you also try with the latest?

**Comment by sundayz** [comment]
The code pen uses the latest version. Anyway I would say this issue is pretty low priority. But good to know about
