### ISSUE TITLE
Methods load is useless when partialRender is true

### ISSUE THREAD

**Issue by NidusP** [wavesurfer-js/wavesurfer.js#2154]
### Wavesurfer.js version(s):
4.4.0

### Browser and operating system version(s):
windows ,  Google Chrome 87.0.4280.141

### Code needed to reproduce the issue:
[https://codepen.io/nidusp/pen/eYdQqOY](url)

### Use behaviour needed to reproduce the issue:
click the 'next' button to load a url，the wave will be blank if partialRender: true

**Comment by entonbiba** [comment]
link is: [https://codepen.io/nidusp/pen/eYdQqOY](https://codepen.io/nidusp/pen/eYdQqOY)

https://github.com/katspaugh/wavesurfer.js/blob/658bd921be60a64192331ce8511bf1bce68cc4ec/src/wavesurfer.js#L1267 

![image](https://user-images.githubusercontent.com/5193884/105569496-f585a080-5d0f-11eb-8b13-5d4b2d881b92.png)

Do we really need a loop here? @thijstriemstra
