### ISSUE TITLE
setPlaybackRate does not work in Firefox with MediaElementWebAudio

### ISSUE THREAD

**Issue by sundayz** [wavesurfer-js/wavesurfer.js#2160]
### Wavesurfer.js version(s):
4.4.0

### Browser and operating system version(s):
Firefox 85, Windows 10

### Code needed to reproduce the issue:
Codepen here: https://codepen.io/sundays/pen/dypaqvO

### Use behaviour needed to reproduce the issue:
1. Open codepen
2. Click the button to play audio
3. Click the other button to toggle playback rate between 100% and 200%

Result in Firefox: Nothing happens
Result in Chrome 87: You can see and hear the audio playback rate get faster/slower when you change between 1 and 2.

This only happens with MediaElementWebAudio. It works with WebAudio.

**Comment by thijstriemstra** [comment]
can you show how to control the playbackrate on an `audio` element without wavesurfer.js? Does it even work in Firefox?

**Comment by sundayz** [comment]
```js
<audio id="my-audio" controls src="https://wavesurfer-js.org/example/media/demo.wav">

let media = document.getElementById("my-audio")
media.playbackRate = 1.5
```

Works fine for me. The thing is, MediaElementWebAudio seems to use WebAudio for the actual playback. It's using this:
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource

That creates a `MediaElementAudioSourceNode` which "is a node that has no inputs and one output" and that gets connected to the WebAudio backend so it plays. At least that's my understanding of it.

While typing out this answer I realised that MediaElementWebAudio extends MediaElement which overrides setPlaybackRate:
https://github.com/katspaugh/wavesurfer.js/blob/658bd921be60a64192331ce8511bf1bce68cc4ec/src/mediaelement.js#L269

So maybe the answer is not setting the playbackRate on the MediaElement but rather like how WebAudio backend does it:
https://github.com/katspaugh/wavesurfer.js/blob/658bd921be60a64192331ce8511bf1bce68cc4ec/src/webaudio.js#L737

That's my guess, I don't know exactly how this stuff works.

**Comment by marizuccara** [comment]
Hi, `WebAudio` uses as source the `AudioBufferSourceNode` which has as property `playbackRate`, `MediaElementWebAudio` uses as source node `MediaElementAudioSourceNode` which has not playbackRate property (so it is set via tag audio)

**Comment by sundayz** [comment]
Looks like it's a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1517199
Not sure if there's a workaround.

**Comment by entonbiba** [comment]
@sundayz found the following from the w3c docs, it's related to media capture streams and says 1.0 playback rate. It's possible firefox devs looked at the following considerations and limited playback rate to always 1.0 even for non live streams, Seems to be a pretty straight forward change if that's the case for firefox browser.

https://w3c.github.io/mediacapture-main/#mediastreams-in-media-elements

![image](https://user-images.githubusercontent.com/5193884/105642189-3687cd00-5e56-11eb-8391-cbe1837dfd46.png)

**Comment by CristianNoop** [comment]
@entonbiba Hi, could You elaborate on what you meant as the workaround? It seems to me that the only node that allows to control the playback rate is `AudioBufferSourceNode`. Only, that would mean having to load the whole file before playing. I'm new to Web Audio so all help would be welcome. 

I really would like to find a solution, as I can't use Chrome because the audio and waveform go out of sync if the bit rate of the mp3 file isn't uniform.
