### ISSUE TITLE
allow load() to render just peaks data with empty audio source

### ISSUE THREAD

**Issue by entonbiba** [wavesurfer-js/wavesurfer.js#2166]
@katspaugh @thijstriemstra @sundayz @marizuccara @osheroff 
What you guys think about simply expanding the `load()` method and providing an additional option or check which will allow to render only peak data without any audio source? The way I currently do it now is provide a base 64 empty audio file such as below when loading peaks data. 

`data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU2LjM2LjEwMAAAAAAAAAAAAAAA//OEAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAEAAABIADAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1dXV6urq6urq6urq6urq6urq6urq6urq6urq6v////////////////////////////////8AAAAATGF2YzU2LjQxAAAAAAAAAAAAAAAAJAAAAAAAAAAAASDs90hvAAAAAAAAAAAAAAAAAAAA//MUZAAAAAGkAAAAAAAAA0gAAAAATEFN//MUZAMAAAGkAAAAAAAAA0gAAAAARTMu//MUZAYAAAGkAAAAAAAAA0gAAAAAOTku//MUZAkAAAGkAAAAAAAAA0gAAAAANVVV`

Essentially we can do something as simple as allowing a string specified as "empty" or just checking if the string is empty. This would use the base64 audio data above on the backend and continue rendering the peaks as is.

``` javascript
    wavesurfer.load('', peaks);

    wavesurfer.load('empty', peaks);
```

This would solve the following tickets #2004 #2058 #1894 #2037

**Comment by sundayz** [comment]
What if there was a backend option called NoAudio which implemented all the backend methods as empty functions?

**Comment by thijstriemstra** [comment]
> What if there was a backend option called NoAudio

+1 (although name of backend needs some more thought)

**Comment by entonbiba** [comment]
the backend option can work its just more intuitive and automatic for it to check if there's no source. It would simply create the peaks as is with the empty audio file.

This way you can simply do another .load() with an actual audio file and everything would continue working as is without the need to recreate.

**Comment by daslicht** [comment]
is there meanwhile a workaround ?

**Comment by jgentes** [comment]
I find this to be a viable workaround:

```
wavesurfer.backend.setPeaks(peaks, duration)
wavesurver.drawBuffer()
```

The only downside is that it doesn't emit a `waveform-ready` event, but since it generates nearly in real-time, initialization of plugins can just happen right after the drawBuffer step.

**Comment by jgentes** [comment]
> The only downside is that it doesn't emit a `waveform-ready` event, but since it generates nearly in real-time, initialization of plugins can just happen right after the drawBuffer step.

I found the CursorPlugin didn't work without the ready, so I used this hack after drawBuffer:
```js
waveform.fireEvent('ready')
```

**Comment by daslicht** [comment]
yeh got it meanwhile either :) ![](https://ansolas.com/sound-design)

**Comment by greenreptile** [comment]
> ```js
> backend
> ```

Seems "backend" not exists anymore

**Comment by greenreptile** [comment]
> I find this to be a viable workaround:
> 
> ```js
> wavesurfer.backend.setPeaks(peaks, duration)
> wavesurver.drawBuffer()
> ```
> 
> The only downside is that it doesn't emit a `waveform-ready` event, but since it generates nearly in real-time, initialization of plugins can just happen right after the drawBuffer step.


Seems "backend" not exists anymore
