### ISSUE TITLE
Render phonocardiogram

### ISSUE THREAD

**Issue by imndaiga** [wavesurfer-js/wavesurfer.js#2178]
I created a react app and using an attached microphone and feeding its stream to the wavesurfer.js microphone plugin with it's deviceId.
I'm trying to get a an actual wave instead of bars rendered out but all my attempts so far have failed. My end goal is to implement a phonocardiogram as referenced here [#364](https://github.com/katspaugh/wavesurfer.js/issues/364). There aren't examples of using a microphone feed to render a wave vs bars, would gladly contribute my work as an example.

I've created a custom MultiCanvas renderer as suggested, re-implementing the drawBars and drawWave methods but they're currently duplicates of the code from wavesurfer.js.

### Wavesurfer.js version(s):
wavesurfer.js: 4.4.0

### Browser and operating system version(s):
- Chrome
- MacOS Big Sur

### Code needed to reproduce the issue:
```javascript
this.wavesurfer = WaveSurfer.create({
	container: '#waveform',
	waveColor: '#000000',
	interact: false,
	cursorWidth: 0,
	barGap: 0,
	plugins: [
		WaveSurferMicrophone.create({
			bufferSize: 4096,
			numberOfInputChannels: 1,
			numberOfOutputChannels: 1,
			constraints: {
				audio: {deviceId}
			}
		}),
	],
});
```

### Use behaviour needed to reproduce the issue:

In running the above code snippet with barWidth set to `1`, I get the following which is expected
![Untitled](https://user-images.githubusercontent.com/7655125/106194530-e20e8580-61a6-11eb-8f68-0717b63e2ac1.png)

But with barWidth unset all I get is a horizontal line as shown below
<img width="1382" alt="Screenshot 2021-01-28 at 20 28 34" src="https://user-images.githubusercontent.com/7655125/106194960-6c56e980-61a7-11eb-889d-aed2e07f6449.png">

The above is also half-expected as drawWave renders a flat line if drawWave was called within ws.empty. I figure this is what's going on in my case but I'm not clear on what the empty object is meant to represent?

**Comment by entonbiba** [comment]
@wndaiga is the audio file less than a second or so ? If so that's a bug with short audio files not rendering peaks. #2095

**Comment by thijstriemstra** [comment]
> the audio file less than a second or so ?

Uh, it's a microphone stream.

**Comment by thijstriemstra** [comment]
I tested the microphone example with the following bar settings and it rendered fine:

```javascript
barWidth: 2,
barHeight: 1,
barGap: null
```

**Comment by wndaiga** [comment]
Hi @entonbiba, it's a microphone stream and not an audio file as mentioned so that shouldn't play no?

**Comment by wndaiga** [comment]
@thijstriemstra, thanks for looking into this - https://github.com/katspaugh/wavesurfer.js/blob/8cc4bbd4b64e98a939cae18d5cb072ef86c8fb38/src/drawer.js#L159 shows that drawWave vs drawBars is invoked depending on barWidth - but setting it to null doesn't seem to render out a wave as I'd assumed? My only two guess atm are that getPeaks isn't pulling in peak data for some reason in this config or drawer.empty() gets erroneously invoked at some point? Will give these a deeper look, any pointers would be appreciated
