### ISSUE TITLE
change color of wave by start and end time

### ISSUE THREAD

**Issue by zahraHaghi** [wavesurfer-js/wavesurfer.js#2180]
I want to use wavesurfer .and I have ywo issues

1. show selected part with region in another wave. 
2. change color of part of wave by start and end time.for example from 2 to 6 seconds color could be blue from 7 to 10 seconds could be red

how can I do these?

**Comment by zahraHaghi** [comment]
@thijstriemstra  is there a way?

**Comment by liankuai** [comment]
I want to know  how to set different color for wave segment, for example from 2 to 6 seconds color could be blue from 7 to 10 seconds could be red

**Comment by liankuai** [comment]
> @thijstriemstra is there a way?

Hi, Do to know  how to set different color for wave segment, for example from 2 to 6 seconds color could be blue from 7 to 10 seconds could be red?

**Comment by harshitkaran** [comment]
Hi, do you find out how to color waveplot this way?

**Comment by harshitkaran** [comment]
Hi, did you find any solution on how to color waveplot this way?

**Comment by gdamou** [comment]
Hello, if someone is still searching a way to achieve this sort of effect, I used a little trick to make it work quite properly.

I create three regions : left, middle and right.

Both left and right region are no draggable or resizable. I set to them a color low opacity but darker than the middle region and on event "updated" of the middle region, I update the options start/end of the left and right region to stick with the middle one that is currently moving.

I know, it's tricky but in my case it works fine enough to make the illusion that I only have one region in highlight.

**Comment by adam-godfrey** [comment]
> Hello, if someone is still searching a way to achieve this sort of effect, I used a little trick to make it work quite properly.
> 
> I create three regions : left, middle and right.
> 
> Both left and right region are no draggable or resizable. I set to them a color low opacity but darker than the middle region and on event "updated" of the middle region, I update the options start/end of the left and right region to stick with the middle one that is currently moving.
> 
> I know, it's tricky but in my case it works fine enough to make the illusion that I only have one region in highlight.

Have you still got the code to how you achieved this? Your solution works in my head but it's the colouring I'm not sure about
