### ISSUE TITLE
The duration of audio is different with Wavesurfer and Audio Element

### ISSUE THREAD

**Issue by tarsusi** [wavesurfer-js/wavesurfer.js#2181]
Hi everyone,

I was trying to sync WaveSurfer element with a audio player(I'm using videojs). Then I figured out that there is a strange difference on durations between wavesurfer and videojs. Then I have tried with a native audio element then the problem is the same.

I have created a [codesandbox](https://codesandbox.io/s/videojs-wavesurfer-sync-problem-qrfid?file=/src/index.js) to reproduce the issue. When you open the project, you will see the durations computed by audio element and wavesurfer are not the same. I have used two different sources. You can change and see the problem with different audio file types.

What is wrong with the durations? Am I missing something?

Thanks

Wavesurfer version: 4.4.0

**Comment by entonbiba** [comment]
It's primarily how web audio analyzes the audio length, when using web audio it is more accurate in the actual precision of the duration in web audio processing.

You can always set the `backend: "MediaElement"` option which will use media element and have the same duration as an audio element already on your page.
