### ISSUE TITLE
Audio and waveform go out of sync when seeking

### ISSUE THREAD

**Issue by noopc** [wavesurfer-js/wavesurfer.js#2185]
### Wavesurfer.js version(s):
 4.3.0.

### Browser and operating system version(s):
Chrome (latest), Windows 10

### Code needed to reproduce the issue:

Wavesurfer settings:
```
this.waveSurfer = WaveSurfer.create({
      container: '#waveform',
      splitChannels: true,
      scrollParent: true,
      backend: 'MediaElementWebAudio',
      plugins: [
        WaveSurferTimeline.create({
          container: "#timeline"
        })
      ]
    });
```
  
Usage:
```
this.http.get('url to asset').toPromise().then(res => {
  this.waveSurfer.load('url to asset', res.data)
});
this.waveSurfer.load('url to asset', '.url to asset')
```

**The waveform .json file is created by following [Wavesurfer.js FAQ](https://wavesurfer-js.org/faq/).**

### Description
* With MediaElementWebAudio backend, when using long audio files, the waveform and audio goes out of sync when seeking either forward or backward. The longer the file, the more the audio will go out of sync. For example, on a 40 minutes long file, the difference between audio and waveform is up to 5 seconds.  
* The waveform seeks to the correct position, but the audio location will be incorrect.
* If not seeking, the audio and waveform will stay in sync.  
* The issue exists in Chrome, in Firefox everything works fine.

**Comment by entonbiba** [comment]
@CristianNoop may you try to replicate this issue using the latest stable version 4.4.0 ?

**Comment by CristianNoop** [comment]
@entonbiba Yes, the issue still persists in 4.4.0.

**Comment by entonbiba** [comment]
can you provide a link to your audio file for testing?

**Comment by CristianNoop** [comment]
@entonbiba  Here is an [example](https://ufile.io/f/j8pj8) of a long file. All of the test files I use have gone out of sync, whereas the longer files go  more out of sync.  If You have a longer stereo mp3 file for testing, which doesn't go out of sync, maybe You could share a link as well, so I could test it in my application.

Also, thanks for looking into it. :)

**Comment by CristianNoop** [comment]
@entonbiba The issue seems to be with Chrome and the bit rate of the mp3 file. After processing the mp3 to have a uniform bit rate, it works as expected in both Chrome and Firefox.

**Comment by lxtasamir** [comment]
@CristianNoop Could you please tell us what did you use for "processing the mp3 to have a uniform bit rate"?
