### ISSUE TITLE
Fire event when zoom render is complete

### ISSUE THREAD

**Issue by marcelblum** [wavesurfer-js/wavesurfer.js#2190]
This is either a question or feature request :)

When zooming in deep with longer tracks, for example >500 `pxPerSec` on a 4 minute stereo track, it can take a relatively long time to render the waveform (like a few seconds or more). This can result in less than ideal UX such as the playhead cursor temporarily frozen over a blank canvas. Is there any way to catch when rendering has completed so that I can show a friendlier UI like an hourglass until the zoom is done? I noticed wavesurfer has listenable `zoom` and `redraw` events but these seem to only fire when beginning the `zoom()` process, before the canvas renders, so not useful here.

**Comment by entonbiba** [comment]
#2239 we will look into the performance issue on that ticket and see if the event can be sent after the zoom has finished as well

**Comment by marcelblum** [comment]
Cool. @robert8888 made a plugin that partially addresses this https://github.com/robert8888/wavesurfer-async-processing-plugin but it has some issues and I've not had a chance to investigate further.
