### ISSUE TITLE
Playback rate weird when used with backend `WebAudio`

### ISSUE THREAD

**Issue by sahi1422** [wavesurfer-js/wavesurfer.js#2197]
### Wavesurfer.js version(s):
4.5.0

### Browser and operating system version(s):
Chrome as well as firefox

The playback rate behaves weirdly when used with backend `Webaudio`. Changing playback rate changes current cursor time also and jumps to some random position. The behavior is fine when used with backend `MediaElement`.

**Comment by thijstriemstra** [comment]
> Chrome as well as firefox

What operating system(s)?

**Comment by sahi1422** [comment]
https://github.com/katspaugh/wavesurfer.js/issues/2349
