### ISSUE TITLE
no apparent way to listen for web-audio readiness

### ISSUE THREAD

**Issue by osheroff** [wavesurfer-js/wavesurfer.js#2203]
hey all, apologies if I'm re-treading familiar ground.

I'm trying to delay initialization in my new markers plugin so that I don't draw markers until the waveform is loaded and the duration is calculated... they simply all draw on top of each other.

I'm seeing 'ready' and 'waveform-ready' events in the codebase.  neither appears to fire in the simplest form of using wavesurfer, which is to not specify a backend (and get webaudio), and call `wavesurfer.load(url)`.  I believe if I give wavesurfer peaks that the webaudio backend will fire a 'waveform-ready' event.

am I dumb?  Or is this just an oversight?

**Comment by kgullion** [comment]
I just started looking at wavesurfer myself as well so I may also be overlooking something but looking at the code, it appears the wavesurfer instance itself [fires the event](https://github.com/katspaugh/wavesurfer.js/blob/142a8221cae1e96aa6b43dfffc37602f33dfc9bc/src/wavesurfer.js#L1445) and [calls the handler](https://github.com/katspaugh/wavesurfer.js/blob/142a8221cae1e96aa6b43dfffc37602f33dfc9bc/src/util/observer.js#L31), not the webaudio backend. something like

```
var surfer = new WaveSurfer(opts);
surfer.on('waveform-ready', callback)
```

**Comment by sundayz** [comment]
From my code base:

```js
if (backend === 'WebAudio') {
    wavesurfer.fireEvent('interaction');
}
```

you may want to try this. The 'ready' event is pretty inconsistent across backends. For `WebAudio` it seems like the intention was to delay loading until a user clicks, to prevent autoaplay issues. But it doesnt really seem to do anything other than prevent ready from firing.
