### ISSUE TITLE
MediaElementWebAudio Choppy Playback in iOS Safari

### ISSUE THREAD

**Issue by sundayz** [wavesurfer-js/wavesurfer.js#2210]
### Wavesurfer.js version(s):
4.6.0

### Browser and operating system version(s):
Safari on iOS >= 13.6 and iOS 14.4

Only affects the **MediaElementWebAudio** backend.

I'm posting this so we can brainstorm some ideas and maybe find a fix. I will note several useful information sources here too. This is a known issue (#2116 mentions it) but it hasn't been reported yet.

**Useful Links**
Browser Implementation Spec: https://www.w3.org/TR/webaudio/#mediaelementaudiosourcenode

Webkit bug reported: https://bugs.webkit.org/show_bug.cgi?id=211394
See older replies from late 2020: after iOS 13 bug fix related to `createMediaElementSource`, there are reports of choppy and glitchy audio in Safari.

Godot Game Engine choppy audio in Javascript export: https://github.com/godotengine/godot/issues/35937

**My Scenario**
Streaming a _mp3_ file through the MediaElementWebAudio backend.
The app allows users to modify the playback rate of the track. At normal playback speed it sounds OK but slightly choppy. At higher playback rate, it sounds fine. At lower playback rate, the lower you go the worse it sounds, eventually it stops playing audio completely.

**What I have tried**
- In the Godot issue linked above, someone says audio sounds choppy when the script node buffer size is too small. I saw that WaveSurfer uses a small buffer of 256 bytes, so I thought that I found the fix. But I tried 256, 2048, 4096 and 16k buffer sizes and they all had the same choppy audio.
- No success with different AudioContext latency hints. Tried 0ms, 15ms, 100ms.

**What I have not tried so far**
- Different audio format. Only tried mp3, someone once told me M4A is good for Safari, might be promising for my use case but wouldn't solve the bug (is it solveable in userland or requires browser fix?)

I hope people will find this information useful, took a while to gather it. Maybe this will inspire someone. 

**New info**

https://bugs.webkit.org/show_bug.cgi?id=221334

Looks like Safari Technology Preview implements unprefixed webaudio and AudioWorklet?

**Comment by thijstriemstra** [comment]
> Browser and operating system version(s):
>
> iOS Safari

What version(s)?

**Comment by sundayz** [comment]
Added version info

**Comment by sundayz** [comment]
Updating with more details.

Have also tried:

- Using .aac file instead of .mp3
- Using .aac file with AudioContext latencyHint: `playback`
- Using .aac file with latencyHint: `playback` and `createScriptProcessor(4096)` (4096 bytes instead of WS default 256)

None of the above combinations fixed the choppy audio playback.

Another webkit issue maybe somehow related, though it's about audio through WebRTC, marked as resolved for 14.3 (but choppy audio still remains for me on 14.4): https://bugs.webkit.org/show_bug.cgi?id=218762

**Comment by thijstriemstra** [comment]
dis you try a custom audicontext with a samplerate of 48000 hz?

**Comment by sundayz** [comment]
Tried both 44100 and 48000 and they were the same. 

One thing that I just tried that seems to make a difference is this:

- Using MediaElementWebAudio
- First I prevent wavesurfer from touching the playbackRate property on the source element, audio lags whenever setPlaybackRate is called.

```js
// Don't actually change playbackRate on the HTMLMediaElement, Safari hates when you do it for some reason.
wavesurfer.backend.setPlaybackRate = (value) => {
    // Should just be noop?
    wavesurfer.backend.playbackRate = value || 1;
};

- Then I initialize wavesurfer with a script node processor like this:

```js
audioScriptProcessor: window.WaveSurferAudioContext.createScriptProcessor(16384),
```

16k (the highest possible I think) seemed to be the only one that didn't have audio glitches.

Now it works great for about 30 seconds, smooth audio, but then it abruptly stops, and if you try to play again, it works for 3-4 seconds before becoming silent. It looks like it's filling up some kind of internal buffer...

I'm hoping that if I tweak the parameters enough I find some magic combination that works :S but it's not easy.

**Comment by sundayz** [comment]
I was wrong it’s not totally smooth but I’m pretty sure it’s better overall with 16k buffer.

**Comment by thijstriemstra** [comment]
What type of file are you testing with it anyway? (use ffprobe to analyze?)

There's also a large amount of info on https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs

**Comment by sundayz** [comment]
Using 44100hz mp3, I don't see anything wrong with it in ffprobe.

Here's something from the webkit changelogs btw:

```
2020-09-23  Chris Dumez  <cdumez@apple.com>

        Turn off the legacy prefixed WebAudio API
        https://bugs.webkit.org/show_bug.cgi?id=216886

        Reviewed by Sam Weinig.

        Turn off the legacy prefixed WebAudio API, now that the modern unprefixed API has been enabled
        in r267488.
```

I guess this means in the near future we'll be able to remove the prefixed webaudio stuff.

Source:
https://raw.githubusercontent.com/WebKit/WebKit/main/Source/WebCore/ChangeLog-2021-03-18
