### ISSUE TITLE
Using wavesurfer.js on a Woocommerce Wordpress site.

### ISSUE THREAD

**Issue by candilora28** [wavesurfer-js/wavesurfer.js#2223]
Hello I am trying to use wavesurfer on my woocommerce product page description area. However I can not get it to work. I tried using the Wavesurfer WP plugin but it seems support has been discontinued and it will not function correctly.

Here is an example of what I am trying to achieve:https://producergrind.com/collections/new-releases/products/laynoprod-cruise-westcoast-melodies

if you scroll down on that page you see that they have the audio files and waveforms.

**Comment by thijstriemstra** [comment]
what have you tried so far?

**Comment by candilora28** [comment]
I have tried adding the <script src="https://unpkg.com/wavesurfer.js"></script> To my functions.php of my child theme, to the header.php file. I have tried saving it and renaming it wavesurfer.js and adding it to my theme files in the js folderZ

I then put the 

<div id="waveform"></div>
<script>
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'violet',
    progressColor: 'purple'
});
wavesurfer.load('liendu.wav');
</script>

In the html area of the product description, and replace the liendu.wav with the audio file I have uploaded to my Wordpress Media files.

After doing these steps the area where the player should generate is completely blank.

I am not very experienced in JavaScript so I’m sure I am missing a step or doing something incorrect.

**Comment by candilora28** [comment]
Actually I got it to work, but I am having trouble getting a play button to work. Here is my code

`<div id="waveform"><script>var wavesurfer = WaveSurfer.create({ container: '#waveform',normalize: 'true',fillParent: 'true',waveColor: '#d8044b',progressColor: 'white',height: '65',hideScrollbar: 'true',});wavesurfer.load('/wp-content/uploads/2021/03/808-Gunna.wav');</script>`

Which is rendering the waveform correctly, But I am confused on how I would add a play/pause button to this? The documentation is confusing on this.

**Comment by sundayz** [comment]
`wavesurfer.play()` will start playing audio, `wavesurfer.pause()` pauses audio. It's up to you to tie this functionality to a HTML `<button>` element using `onclick`.

Here's an example:

example: https://wavesurfer-js.org/example/mute/index.html
code: https://github.com/katspaugh/wavesurfer.js/blob/master/example/mute/app.js

**Comment by candilora28** [comment]
> `wavesurfer.play()` will start playing audio, `wavesurfer.pause()` pauses audio. It's up to you to tie this functionality to a HTML `<button>` element using `onclick`.
> 
> Here's an example:
> 
> example: https://wavesurfer-js.org/example/mute/index.html
> code: https://github.com/katspaugh/wavesurfer.js/blob/master/example/mute/app.js

Okay that makes sense, I copied the code from the example you sent, but it is not working.

![image](https://user-images.githubusercontent.com/80646833/111691736-38399580-87f4-11eb-9ef0-79b4d9affdb4.png)

To clarify I have <script src="https://unpkg.com/wavesurfer.js"></script> inserted into the Header of my site, and then the rest I am trying to put into the description area as pictured above, on the front end it is just blank... even when adding <script> tags

**Comment by sundayz** [comment]
You also need to create the buttons. The HTML for the example I linked is here: https://github.com/katspaugh/wavesurfer.js/blob/master/example/mute/index.html

The relevant part is:

```html
<div id="demo">
    <div id="waveform"></div>

    <div class="controls">
        <button id="playBtn" class="btn btn-primary">Play / Pause</button>
        <button id="toggleMuteBtn" class="btn btn-primary">Toggle Mute</button>
        <button id="setMuteOnBtn" class="btn btn-primary">
            Mute <i class="glyphicon glyphicon-volume-off"></i>
        </button>

        <button id="setMuteOffBtn" class="btn btn-primary">
            Unmute <i class="glyphicon glyphicon-volume-up"></i>
        </button>
    </div>
</div>
```

`<div id="waveform"></div>` This is where the waveform will appear (matches `container: "#waveform"` in the code)

Also the buttons won't have styling unless you add CSS to them. But that part is up to you.

**Comment by candilora28** [comment]
Got it. Play button is appearing but not actually functioning. 

So to recap I have this code in my Header
![image](https://user-images.githubusercontent.com/80646833/111696267-bcdae280-87f9-11eb-9dc3-9bfb21812fde.png)

Then on the product description I have this (I am using a div grid element which will have a separate instance of wavesurfer in each column)
![image](https://user-images.githubusercontent.com/80646833/111696419-e7c53680-87f9-11eb-9b96-441947e49962.png)

then finally on the front end I am getting this:
![image](https://user-images.githubusercontent.com/80646833/111696470-f6135280-87f9-11eb-8583-cbfbb4f65047.png)

The waveforms are rendering properly, but the play button is not functioning. Also each instance of wavesufer should have its own play/pause button, but I was going to add it to them once I get the code nailed.

Sorry if these are amateurish questions, I do not have a ton of experience in coding

**Comment by sundayz** [comment]
Start with 1 wavesurfer, make that work, then do the others. There's a lot to explain here that will probably be hard for someone not experienced with web development.

Here's some tips:

- The part highlighted in red here does nothing and you can move it in the same place as the rest of your code:
![image](https://user-images.githubusercontent.com/11685806/111697395-6ab3b480-882d-11eb-87d8-de6773a99017.png)

- Use the browser console (CTRL+SHIFT+I and click Console) to check for any errors.

- When you create a wavesurfer like `var wavesurfer = Wavesurfer.create( ... )` you should give each new variable a different name, or you will overwrite the previous one. `wavesurfer1`, `wavesurfer2` will be fine. 

- Use `let` instead of `var` because it will save you a lot of headaches down the line.

- Each wavesurfer should have its own container, like `<div id="waveform"></div>` but give it a unique id.

- Add something like this:
```js
wavesurfer.on('ready', function () {
    console.log("loaded wavesurfer"); // appears in console if wavesurfer successfully loads your file (CTRL+SHIFT+I)
});

wavesurfer.on('error', function(err) {
    console.error(err); // red text appears in your browser console if theres an error
});
```

- Learn what `document.querySelector`, `document.getElementById` and `butotn.onclick = function () {}` do. Documentation on mozilla.org is great. w3schools.com is good for beginners learning the basics.

If you learn all this yourself it's going to take less time than if I try to tell you what to do through a github ticket, and you'll understand a lot more. Good luck ;)

**Comment by candilora28** [comment]
> * When you create a wavesurfer like `var wavesurfer = Wavesurfer.create( ... )` you should give each new variable a different name, or you will overwrite the previous one. `wavesurfer1`, `wavesurfer2` will be fine.
The problem with this is, I have 400+ products on my website, and each product will need a unique set of audio waveforms. I am hoping to get this set up so I can copy and paste the code to a new product as I add them, and change the variables (url of audio) as needed. 

So lets say a product has 6 audio previews which is 6 instances of wavesurfer... If I name them each accordingly wavesurfer1, wavesurfer2 etc.. and then I want to copy this template to a new product with 6 new audio files, would I be able to copy that code and use the same 6 names? or would I have to make the new product have wavesurfer7, wavesurfer8  etc.... I want to avoid having to make 400+ instances of wavesurfer.

> * Learn what `document.querySelector`, `document.getElementById` and `butotn.onclick = function () {}` do. Documentation on mozilla.org is great. w3schools.com is good for beginners learning the basics.
> 
> If you learn all this yourself it's going to take less time than if I try to tell you what to do through a github ticket, and you'll understand a lot more. Good luck ;)

I appreciate that but my job and career is not web development. Basically I have built my business website through wordpress, its good to go.. Just want to add this touch to my products and need help getting this code nailed. And hopefully won't have to do much more coding in my life lol.

**Comment by sundayz** [comment]
I don’t know enough about Wordpress development to tell you how to structure the code. You should have a function that takes a URL, creates the WaveSurfer container and the buttons, hooks up the events and loads the audio. Then you loop an array of URLs and call that function on each one. Cant tell you how to do it specifically within Wordpress, there’s a reason why most developers don’t like working with it, it predates modern frameworks that give you an easy way of doing all this. You should find a Wordpress developer who can do all this for you.

**Comment by candilora28** [comment]
I am willing to pay you to do it for me... I just need this figured out right away and I am at wits end.

<div id="waveform"><script>var wavesurfer = WaveSurfer.create({ container: '#waveform',normalize: 'true',waveColor: '#d8044b',progressColor: 'white',height: '65',hideScrollbar: 'true'});wavesurfer.load('/wp-content/uploads/2021/03/808-Unarmed-.wav');</script></div>

this line of code literally works to generate the waveform, I do not understand why I cannot just add one more simple line to create the button. I am going crazy!
