### ISSUE TITLE
Minimap timeline

### ISSUE THREAD

**Issue by caugner** [wavesurfer-js/wavesurfer.js#2234]
We're using Wavesurfer.js in an internal script editor with the following four plugins:

* cursor
* minimap
* regions
* timeline

While the timeline refers to the currently shown extract of the wave form, we got the feedback from users that it would be helpful to have an *additional* "mini-timeline" for the minimap.

Is that already possible with the current version?

### Wavesurfer.js version(s):

4.5.0

### Browser and operating system version(s):

Windows 10 / Firefox

### Code needed to reproduce the issue:

(n/a)

### Use behaviour needed to reproduce the issue:

(n/a)

**Comment by thijstriemstra** [comment]
> Is that already possible with the current version?

No, pull requests are welcome.

> 4.5.0

4.6.0 is the latest.

**Comment by caugner** [comment]
> 4.6.0 is the latest.

That's a bit odd, `4.5.0` was supposedly released "15 hours ago", but `4.6.0` was already pushed "27 days ago":

![grafik](https://user-images.githubusercontent.com/495429/113707677-88639380-96e0-11eb-8045-050cab008240.png)

See: https://github.com/katspaugh/wavesurfer.js/releases
