### ISSUE TITLE
Connection keeps on pending after several plays

### ISSUE THREAD

**Issue by diegoiglesias** [wavesurfer-js/wavesurfer.js#2249]
Having multiple wavesurfer instances, after played several songs connection eventually get stuck on "pending" status.

Here is a pen with the test:
https://codepen.io/diegoigle/pen/OJWrZvO

I'm using Chrome lastest build.

Can someone help?

**Comment by entonbiba** [comment]
Make sure all the instances are paused or stopped before on the play event.

add 
```javascript
for (var i = 0; i < waveforms.length; i++) {
    waveforms[i].pause();
}
```

to the `playerPlay`

``` javascript
var playerPlay = function(buttonIdAttr){
    currentPlaying['status'] = 'PLAYING';
    currentPlaying['id'] = buttonIdAttr;
  
    for (var i = 0; i < waveforms.length; i++) {
	waveforms[i].pause();
    }
  
    waveforms[currentPlaying['id']].play();  
}
```

**Comment by diegoiglesias** [comment]
Thank for your help. Unfortunately it keeps happening, though now it takes a little more retries to get it pending.

I updated the pen with your code:
https://codepen.io/diegoigle/pen/OJWrZvO

**Comment by leeqkrtkxp** [comment]
https://stackoverflow.com/questions/23679968/chrome-hangs-after-certain-amount-of-data-transfered-waiting-for-available-soc
