### ISSUE TITLE
make region by mouse drag & drop 

### ISSUE THREAD

**Issue by JungJaeLee-JJ** [wavesurfer-js/wavesurfer.js#2250]
### Wavesurfer.js version(s):
4.6.0

### Browser and operating system version(s):
MacOS, Chrome, React

Q1. I want to make region by mouse manipulation. where mouse clicked will be region's start time , and where released will be an end time of region.  is there any solution to do this?

Q2. can i use **microsecond** or **millisecond** for region period's start and end time. is that possioble(**not second**)?

**Comment by thijstriemstra** [comment]
@JungJaeLee-JJ can you open a new ticket for Q2?
