### ISSUE TITLE
Add changelog to github release

### ISSUE THREAD

**Issue by thijstriemstra** [wavesurfer-js/wavesurfer.js#2262]
Would be nice if the changelog for a particular release is added automatically with github actions.

Any ideas @katspaugh?

ps. just released a 5.0.1 hotfix release, really liking the publish action so far.

**Comment by katspaugh** [comment]
We could change the title format a bit. Instead of
```
## 5.0.0 (02.05.2021)
```

Write this:
```
## 5.0.0
**02.05.2021**
```

And then we could just link to the changeling section from the release notes like so:

https://github.com/katspaugh/wavesurfer.js/blob/master/CHANGES.md#500

Basically, just insert the version w/o dots.

**Comment by thijstriemstra** [comment]
I think the github api allows you to add a piece of text as changelog. Copying the specific section of the changelog would be the nicest but your solution works as well.
