### ISSUE TITLE
Cursor plugin support for vertical layout

### ISSUE THREAD

**Issue by hamayreh** [wavesurfer-js/wavesurfer.js#2263]
Hi
I am using version 5.0.1, and I can't figure out how to correctly display the cursor in a waveform that is displayed in vertical layout.
Would that be possible? Thanks.

**Comment by valrus** [comment]
Hi,

Unfortunately the cursor plugin doesn't support vertical waveforms yet; I haven't had time to work on it and it uses SVG so it's a little different than the rest of the codebase.
