### ISSUE TITLE
How to have multiple waverforms on the same page

### ISSUE THREAD

**Issue by massimilianocom** [wavesurfer-js/wavesurfer.js#2281]
I have a list of songs and for each song I would like to have a waveform up to here I have succeeded by putting the creation of the waveform in a function but being in a function then outside this function I can no longer use the object.
If I try to declare the variable outside the function like this:

`var wavesurfer= WaveSurfer;

function preloadAudi () {
wavesurfer.create ({
...
)};`

that's how it creates nothing for me
How can I do to globalize the waveform object and then place it where I am serving?

**Comment by Frioo** [comment]
You need to create a separate instance of wavesurfer for each song item, and each of those items should have its own waveform container. If you're using any framework to create your site it's probably easy to create a song item component and instantiate wavesurfer there after the page is rendered (so in onMount, or componentDidMount, etc). 
That way whenever you create, say, a list of songs, each of those will have its own instance, with their own audio file, rendered in their own container.
Keep in mind you need to preserve that instance (save it in some component-wide var) in your component if you want to also use it as an audio player.

**Comment by massimilianocom** [comment]
so for every prano I have to do this:

var wavesurfer = WaveSurfer.create ({
             container: '#waveform'
});

and at each instance I have to change the "wavesurfer" variable?

**Comment by Raspberry42** [comment]
Hello, Is it possible to have an example please?
