### ISSUE TITLE
Can I edit start-end time of a region using button.

### ISSUE THREAD

**Issue by lxtadhamnawito** [wavesurfer-js/wavesurfer.js#2283]
I've been trying to make some button that allows the user to edit the already created region through input fields.

![Edit region](https://user-images.githubusercontent.com/66368677/120089336-7fe47380-c0f9-11eb-9573-6dbcdf9bb675.png)

Something looks like the image above.

So what I want to do, whenever the user creates a region, he can set a new end/start time and press edit, so the region get edited to the new values.

Note: 
1- if there are multiple regions, the user should be able to select anyone of them and edit it's start/end time.
2- I tried to think of removing/deleting the selected region, and re-create the a new one with the new inputs, but I couldn't remove a selected region using the button. (I tried clearRegions(), but it removes all the regions not a specific one)

I'm using ReactJS.

This is the code I'm using:

```
wavesurferConfigure = {
        ...wavesurferConfigure,
        plugins: [
          RegionsPlugin.create({
            dragSelection: {
              slop: 5, // slop
            },
          }),
          TimelinePlugin.create({
            container: "#timeline", // the element in which to place the timeline, or a CSS selector to find it
            primaryColor: "blue", // the color of the modulo-ten notch lines (e.g. 10sec, 20sec). The default is '#000'.
            secondaryColor: "blue", // the color of the non-modulo-ten notch lines. The default is '#c0c0c0'.
            primaryFontColor: "#000", // the color of the non-modulo-ten time labels (e.g. 10sec, 20sec). The default is '#000'.
            secondaryFontColor: "#000",
          }),
          CursorPlugin.create({
            wrapper: this.$waveform,
            showTime: true,
            opacity: 1,
          }),
        ],
      };
    }

    this.wavesurfer = WaveSurfer.create(wavesurferConfigure);
```

And this is the button I have where I don't know what should be the input of onClick fn

```
                <Button style={{ marginLeft: '15px' }}
                  onClick={() => {
                  }}
                > Edit Region</Button>
```

**Comment by Winchester37** [comment]
Could you? I will do a similar work.

**Comment by lxtadhamnawito** [comment]
@Winchester37 , up till now, I couldn't find a solution :(
Do you have any ideas?

**Comment by Winchester37** [comment]
I'm thinking :) But I have to get it done today and tomorrow. I will definitely share it here.

**Comment by lxtadhamnawito** [comment]
As I've mentioned above, I tried to think of deleting and recreating, 
but this.wavesuerfer.on('event-name') is not helping .. cuz the events are not helpful with removing the region.
[wavesuerfer regions events](https://wavesurfer-js.org/plugins/regions.html)

**Comment by Winchester37** [comment]
@lxtadhamnawito https://wavesurfer-js.org/example/annotation/index.html

This example solves its job, and it will be useful for you.

**Comment by lxtadhamnawito** [comment]
@Winchester37 , I've been looking into this since yesterday, but I couldn't manage to use update if this is the right one.
Would you guide me please.

**Comment by lxtadhamnawito** [comment]
@Winchester37  Thanks, I managed to make it today.

**Comment by lxtadhamnawito** [comment]
for further, if anyone tried to do so .. I used ```
wavesurfer.regions.list[regionID].update({
start:start_value,
end:end_value})
```

**Comment by OwOHamper** [comment]
If anyone is looking for solution of this in 2024, you have to use [`.setOptions()`](https://github.com/katspaugh/wavesurfer.js/blob/3f10c5a0b745068ef8e2317cabc90a9263d117a9/src/plugins/regions.ts#L3460) instead of `.update()`
So for example:
```js
wsRegion.setOptions({
   end: region.start
})

```

**Comment by otnansirk** [comment]
I have solved with 
```
wsRegion.setOptions({
   end: region.start
})
```

Thanks @OwOHamper 😁
