### ISSUE TITLE
2 waveforms

### ISSUE THREAD

**Issue by massimilianocom** [wavesurfer-js/wavesurfer.js#2288]
How can I display 2 waveforms with the same audio track on the same page?

**Comment by thijstriemstra** [comment]
use 2 wavesurfer instances. What have you tried so far?

**Comment by massimilianocom** [comment]
> usa 2 istanze wavesurfer. Cosa hai provato fino ad ora?

If I use 2 wavesurfer instances each one goes on its own instead I would like that interacting with one waveform also the other corresponds to this iteration

**Comment by massimilianocom** [comment]
Nobody can help me?

**Comment by thijstriemstra** [comment]
>  I would like that interacting with one waveform also the other corresponds to this iteration

You would have to setup listeners for events like `interaction`(see https://wavesurfer-js.org/docs/events.html for list of events) and trigger those on the 2nd player.
