### ISSUE TITLE
Region events "region-in" and "region-out" fired in wrong order

### ISSUE THREAD

**Issue by icecoveredjune** [wavesurfer-js/wavesurfer.js#2307]
## Description
Incorrect event firing order.
When clicking on region in reverse order, evens fired in wrong order "region-in" => "region-out".
When clicking in direct order, evens fired in correct order "region-out" => "region-in".

## Steps to reproduce
1)Have at least two regions (i.e. №1 and №2).
2) Start to play audio\video.
3) When audio\video entering in region №2, click in region №1.

## Results
Events fired in "backward" order: "region-in" => "region-out".
### Expected
Events fired in order: "region-out" => "region-in".

## Versions
Video.js 7.12.3
slighly modified parse-headers 2.0.2 <https://github.com/kesla/parse-headers/>
videojs-wavesurfer @version 3.8.0
wavesurfer.js regions plugin 4.0.1 (2020-06-24) https://github.com/katspaugh/wavesurfer.js
wavesurfer.js timeline plugin 4.0.1 (2020-06-24) https://github.com/katspaugh/wavesurfer.js
wavesurfer.js cursor plugin 4.0.1 (2020-06-24) https://github.com/katspaugh/wavesurfer.js
Reproduced also on latest version.
### Browsers
Presumably all. Tested on Chrome 91.0.4472.106
### OSes
Presumably all. Tested on Windows 10 
![6](https://user-images.githubusercontent.com/26566632/122596647-626d4e80-d094-11eb-978b-81b693300f48.gif)

Region events "region-in" and "region-out" fired in wrong order

**Comment by sundayz** [comment]
Related: #2140
