### ISSUE TITLE
SetProgressColor does not redraw the waveform with new color unless resizing window

### ISSUE THREAD

**Issue by alirahman-eng** [wavesurfer-js/wavesurfer.js#2313]
SetProgressColor changes the param color, but I noticed the waveform does not redraw with the new color so the visual change does not occur unless the waveform is redrawn like when it resizes when the window changes size

### Code needed to reproduce the issue:

    refs.current.on("seek", function (e) {
      refs.current.setProgressColor("green");
    });

### Use behaviour needed to reproduce the issue:

You can see that if you try to seek, the color does not change unless you pause and resize the window and the wave is redrawn. Thank you for your help!

**Comment by sundayz** [comment]
Try `this.fireEvent('redraw');` as a workaround, should force the canvas to redraw with the new color

**Comment by alirahman-eng** [comment]
Thank you for the comment! I tried this but unfortunately I still run into the same issue. Could it be possible the new waveform is being painted but it is underneath the existing waveform?

**Comment by entonbiba** [comment]
@sundayz maybe we should add this as a method `wavesurfer.redraw()` to redraw the wave

**Comment by MateuszLamczyk** [comment]
The issue with `setProgressColor` still persists (wavsurfer version: 6.0.3). The suggested solution with `fireEvent` does not work.

Any idea how to change the waveform color on button click?
@alirahman-eng did you find a working solution for your problem?
