### ISSUE TITLE
"Back" wave moves up a few pixels when scroll bar is displayed as part of waveform 

### ISSUE THREAD

**Issue by hielienie** [wavesurfer-js/wavesurfer.js#2315]
I have a page with one instance of Wavesurfer. Whenever I load an audio file with a duration long enough to warrant a scroll bar, the original (back) wave moves up a few pixels which means that it creates a shadow for the front wave showing the progress of playback. This might be caused by the fact that overflow for the back wave is set to **auto hidden** instead of **overlay**? 

![image](https://user-images.githubusercontent.com/22660861/123649084-c8db3500-d829-11eb-8d71-73d43ae51e6f.png)

Wavesurfer.js version(s): 4.6.0
Browser and operating system version(s): Chrome on Windows 10

**Comment by thijstriemstra** [comment]
> This might be caused by the fact that overflow for the back wave is set to auto hidden instead of overlay?

Pull requests are welcome!
