### ISSUE TITLE
Marker label position

### ISSUE THREAD

**Issue by Nickyg001** [wavesurfer-js/wavesurfer.js#2317]
I made the visible labels dsfsaall'hover through css, the problem occurs for the last markers those closest to the end of the track.
The text does not expand horizontally but vertically filling the box.

it is possible, as already happens with the time slider, to make sure that at 90% of the track the labels are inverted expanding to the left (flip) ???

marker div {
   position: relative;
   top: 0px;
   width: 15px;
}

marker div: hover {
   width: 100%;
}

marker span {
   background: # 8a2be2;
   padding: 4px;
   z-index: 6;
   color: #fff;
   font-weight: 600;
}

**Comment by Nickyg001** [comment]
I represent the problem with the screenshot.
As you can see the leftmost markers expand the text horizontally, as you get to the stroke limit the text is compressed vertically.
Couldn't we make it so that from a certain point to the right the text expands horizontally but to the left?

![image](https://user-images.githubusercontent.com/33684734/125203487-d73d3e00-e278-11eb-89be-7e3c99a46b57.png)

**Comment by thijstriemstra** [comment]
@Nickyg001 this looks like the same problem that was solved in the cursor plugin with pull request #1776

Can you use that pr for inspiration to fix it in the markers plugin as well?

**Comment by Nickyg001** [comment]
> @Nickyg001 this looks like the same problem that was solved in the cursor plugin with pull request #1776
> Can you use that pr for inspiration to fix it in the markers plugin as well?

yes that's right, I would need the marker to behave identically as in the cursor plugin. Same problem.

1. If they really have to make some changes, I would make sure that only the svg icons of the markers on the track are displayed and hover or click make the text appear. If in a 1 hour track I have 15 songs mixed, showing 15 labels with the writing becomes a mess.

2. having the data:
markers: [
           {
             time: 120,
             label: "start",
             color: '# ff00ff',
             position: 'bottom',
             height: '10px',
           },
           {
             time: 360,
             label: "Louie Vega - Another Day In My Life (Louie Vega Re-Touch)",
             color: '# ff00ff',
             position: 'bottom',
           },
....

entered in the JS file, how could I let him pass the various marker data in the html side to make him read the php data sent from the wordpress backend?
