### ISSUE TITLE
Hearing aid

### ISSUE THREAD

**Issue by k3341095** [wavesurfer-js/wavesurfer.js#2331]
I recently came across wavesurfer and I'm still amazed by its cool features.
I write because I have a question.

What I want to do is amplify the voice of the microphone and output it to the speaker like a hearing aid. Is it possible with only wavesurfer?

I think you can use microphone.plugin + equalizer
If you use the microphone plugin, only the waveform is not output from the speaker.
I saw it..

How can I equalize the mic input and output it?

Actually, I'm deaf... Let's implement the function of a hearing aid instead.
I would like to. Is it possible?

**Comment by thijstriemstra** [comment]
> If you use the microphone plugin, only the waveform is not output from the speaker.
I saw it..

what browser/operating system/wavesurfer.js version?

**Comment by k3341095** [comment]
google.chrome 92 / windows 10 / wavesurfer.js 5.1.0

**Comment by entonbiba** [comment]
we can look to add this as part of the accessibility enhancements with this pr: #2369
