### ISSUE TITLE
Crash on large file

### ISSUE THREAD

**Issue by mvondoyannick** [wavesurfer-js/wavesurfer.js#2352]
i'am trying to open 1 hour of podcast on my phone, event if i puting this code
```javascript
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    backend: 'MediaElementWebAudio',
    scrollParent: true,
    waveColor: '#D9DCFF',
    progressColor: '#4353FF',
    cursorColor: '#4353FF',
    barWidth: 2,
    barRadius: 3,
    barHeight: 1,
    barGap: 2
  });
  wavesurfer.load('<%= rails_blob_path(@podcast.audio_file) %>');
  wavesurfer.on('ready', function () {
    wavesurfer.play();
  });
```
my phone crash and i have this information/issue on my dev console
```javascript
Uncaught TypeError: this.Backend is not a constructor
    value wavesurfer.js:586
    value wavesurfer.js:387
    value wavesurfer.js:230
    <anonymous> hey:692
````
when is a tiny file, everythink is ok, reading audio file work perfectly, but able to read large file.
need help, thanks

PS: using .opus file as audio format

**Comment by sundayz** [comment]
Which browser?

**Comment by mvondoyannick** [comment]
- [x] Chrome Android Browser (Android 7.1, LG V20, crash browser app)
- [x] Opera Touch Browser on Android (Android 7.1, LG V20, crash browser app)
- [x] Firefox, Opera and EDGE on Windows 10
- [x] Same desktop browsers on Linux OS

**Comment by sundayz** [comment]
The phone probably runs out of memory while loading the entire file to draw the waveform.

Sadly the easiest solution here for you is to calculate the waveforms for all your audio ahead of time. So you store the waveform data as .json files on your server, and when you load an audio file you also request the waveform .json and give it to wavesurfer. Then you can use the MediaElement backend which can play big files without any problems.

**Comment by entonbiba** [comment]
@mvondoyannick set the option `renderer` to `MultiCanvas`

**Comment by mvondoyannick** [comment]
> Which browser?

Android browser, chrome desktop - Linux and windows (Google Chrome, opera browser)
