### ISSUE TITLE
Advice on something wavesurfer related

### ISSUE THREAD

**Issue by Gigamick** [wavesurfer-js/wavesurfer.js#2375]
I use wavesurfer (which is amazing btw - thank you!) on an app where I measure "plays". 

The only way I can do this right now is firing an event every time the user clicks "play".

However this means if they click "play" then 2 seconds later stop, and then "play" again, it looks like 2 plays.

I'd really like to only count a "play" if like, 30 seconds of audio have been played.

Kinda don't know where to start. Any ideas?

**Comment by entonbiba** [comment]
@GigaMick we check all issues posted and reply as soon as possible, expert wise for wavesurfer any of the following contributors including:

@sundayz @thijstriemstra @katspaugh @entonbiba
