### ISSUE TITLE
need to prevent from seeking when using click or dblclick events

### ISSUE THREAD

**Issue by hamidm313** [wavesurfer-js/wavesurfer.js#2397]
Hey guys,

I need to have click or dblclick events on wavesurfer preventing from seeking to clicked position.
I've searched a lot, find this way:
step 1- using dblclick not worked, only worked for regions, but using wavesurfer.drawer.on('click', (e) => { }) or wavesurfer.on('seek', (e) => { }) seem fine, but those will cause seeking to clicked position, so:
step 2- set interact parameter to false, but this will disabled all of the above events for me.

Is there any solution for my case?
Is there a more native click or dblclick events on wavesurfer, except "seek"?

PS: I essentially need this capability for creating regions with defined minimum width by clicking the wave, without seeking to clicked position.

Thanks in advance.

**Comment by thijstriemstra** [comment]
Try the `interaction` event. All events are listed here: https://wavesurfer-js.org/docs/events.html
