### ISSUE TITLE
Question regarding existing methods to change speed or pitch

### ISSUE THREAD

**Issue by jesusMdza** [wavesurfer-js/wavesurfer.js#2399]
Are there any available methods that can change the speed or pitch of a file individually? I know there's a `setPlaybackRate()` method but that seems to change both at the same time.

**Comment by entonbiba** [comment]
individually you would set the `setPlaybackRate()` on the instance of wavesurfer, or you can create an array with audio id and playback rate so when that gets loaded it pulls that playback rate and updates only that id in the array when changed.

something along these lines
```javascript
// audio array
var playbackRates = [
 {
   "id": "audioid",
   "rate": 0.5,
   "url": "..."
  },
  {
   "id": "audioid2",
   "rate": 0.8, 
   "url": "..."
  }
];

// change playback rates in array
function changeRate(id,rate){
  for (var i = playbackRates.length - 1; i >= 0; i--) {
	if(playbackRates[i].id == id){
            playbackRates[i].rate = rate;
        }
  }
}

// load audio id from array
function loadAudio(id){
  for (var i = playbackRates.length - 1; i >= 0; i--) {
	if(playbackRates[i].id == id){
            wavesurfer.load(playbackRates[i].url);
            wavesurfer.setPlaybackRate(playbackRates[i].rate);
        }
  }
}

```

**Comment by jesusMdza** [comment]
Can wavesurfer change the pitch of a file alone? As in if I wanted to just change the pitch but not the rate, is this possible?

**Comment by thijstriemstra** [comment]
You can use the `detune` property with a custom AudioContext you can pass to wavesurfer. See https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/detune
