### ISSUE TITLE
Audio Trimmer not loading in safari version ( 15.0 )

### ISSUE THREAD

**Issue by meetgoyani007** [wavesurfer-js/wavesurfer.js#2408]
Wavesurfer.js version(s):
- 3.2.0

**The browser and operating system version(s):**
- **OS:** macOS

- **Browser:** Safari (15.0)

In safari when I try to load audio in wavesurfer at that time it gives an error.
 
![image](https://user-images.githubusercontent.com/72554157/142714751-17ff791b-42b4-426b-81ce-c985a39f0566.png)

This error occurs only in the mentioned browser. please let me know how can I resolve this error.

**Comment by entonbiba** [comment]
@meetgoyani007 may you try with the latest wavesurfer version and try again?

**Comment by meetgoyani007** [comment]
@entonbiba I tried with latest  version but still getting same error.
Thanks

**Comment by entonbiba** [comment]
@meetgoyani007 ok, can you provide some sample code I'll test it on safari

**Comment by meetgoyani007** [comment]
@entonbiba Here is sample code please review it and let me know where I wrong.

HTML:

```
<div id="kingAudioTrimmer" style="border: 1px solid #a3a3a3;"></div>
<audio id="song" style="display: none" preload="false" src="{{audioTrimmer.audioURL}}"></audio>
```

TS:

```
wavesurfer: any;

let wavesurferOptions: any = {
      container: '#kingAudioTrimmer',
      minPxPerSec: 2,
      barGap: 0,
      partialRenter: true,
      autoCenter: true,
      waveColor: '#374168',
      progressColor: '#374168',
      cursorColor: '#1980FF',
      responsive: !0,
      loopSelection: !0,
      mediaType: 'audio',
      backend: 'MediaElement',
      hideScrollbar: !0,
      height: 256,
      cursorWidth: 2,
      pixelRatio: 1,
      normalize: true,
      barWidth: 3,
      // barRadius:5,
      // mediaControls: !0,
      plugins: [
        TimelinePlugin.create({
          container: "#wave-timeline"
        }),
        RegionPlugin.create({})
      ]
    };

this.wavesurfer = WaveSurfer.create(wavesurferOptions);

this.wavesurfer.load(document.querySelector('#song'), []);
```

**Comment by sluice153** [comment]
Solution for me and with all audio issues in Safari since 15.x is: Go to Safari menu->developer->experimental->deactivate GPU Process: Media (if you don't see Developer, you have to activate it in Safari preferences first.
Hope this helps you, too
