### ISSUE TITLE
large wavaforms lead to browser crashed when using Spectogram plugin

### ISSUE THREAD

**Issue by xindoucha** [wavesurfer-js/wavesurfer.js#2412]
Hey everyone,

Large wavaforms lead to browser crashed when using Spectogram plugin.

In wavesurfer, there is a property named "maxCanvasWidth" we can set to create differernt canvas. But there is no same property in Spectogram plugin. So when the wavaforms is too long ,it will lead to  browser crashed 

### Wavesurfer.js version(s):
3.3.2

### Browser and operating system version(s):
chrome

**Comment by thijstriemstra** [comment]
this is a known issue. Btw, always test with latest version (5.2.0 at the moment).
