### ISSUE TITLE
Work request

### ISSUE THREAD

**Issue by Gigamick** [wavesurfer-js/wavesurfer.js#2414]
@katspaugh - Sorry I couldn't find a way to contact you on any site so here I am.

Are you open to an offer of work to help me refine my wave surfer instance?

Thanks

**Comment by katspaugh** [comment]
I'm personally not available but other devs might be.

**Comment by GigaMick** [comment]
> I'm personally not available but other devs might be.

Thanks for the reply. Any way to get to experienced wave surfer devs?

**Comment by katspaugh** [comment]
This issue should be enough.

**Comment by GigaMick** [comment]
> This issue should be enough.

Thanks. Any Wavesurfer experts looking for a couple days work please hit me up. I have a - somewhat - unique implementation and whereas it all works, I am pretty sure my work is on the cowboy spectrum and I'd like an actual expert to refine it.

**Comment by thijstriemstra** [comment]
my email address can be found in the git logs
