### ISSUE TITLE
Wave are not draws only bars

### ISSUE THREAD

**Issue by gwendalF** [wavesurfer-js/wavesurfer.js#2429]
### Wavesurfer.js version(s):
5.2.2

### Browser and operating system version(s):
Chrome 96.0.4664.110
and windows 10

### Use behaviour needed to reproduce the issue:

If I have a very short song, like a click or something very short, I have only a empty line dawned. But the sound is working.
I have try to force to redraw using drawBuffer but that does not change? Is there a minimal duration or minimal number of points to be drawn?

Thanks in advance

EDIT: After looking at some option it happens only if I do not use the barWidth. I don't know why the drawWave is not drawn but it migth be because it's too short
The issue with using bar is that I have also the negative values that are the reflec of positive value. My signal being so small it is not the case and I would like to see that

**Comment by thijstriemstra** [comment]
@gwendalF please include your wavesurfer.js config

**Comment by gwendalF** [comment]
Hello sorry,
this is a copen. 
Under 3840 pts I have no drawing using wave but I have when using bar

https://codepen.io/GwendalFernet/pen/Exwdprr
