### ISSUE TITLE
Stream audio with wave surfer? Possible contract work available.

### ISSUE THREAD

**Issue by Gigamick** [wavesurfer-js/wavesurfer.js#2434]
Is it possible to stream audio through wavesurver as opposed to loading the file in the browser?

If someone is willing and able there is work going here to make this happen.

Thanks

**Comment by achraf-tajani** [comment]
+1

**Comment by finaldzn** [comment]
Its not really possible unfortunaly, we have tried many things but couldn't bring it to work
