### ISSUE TITLE
Regions and splitChannels: Regions only for each channel?

### ISSUE THREAD

**Issue by SvenFranz** [wavesurfer-js/wavesurfer.js#2440]
Thanks for the wavesurfer.js 6.0.0 release! I use wavesurfer with splitChannels view and now regions are for each channels seperated. In  v5 the regions were drawn over both channels which is the behaviour I prefere in my project. Is there a option for that I haven't found until now?

Best regards

**Comment by SvenFranz** [comment]
Well... I solved this by adding in "region-created" Callback
```
        if (region.regionHeight != "100%") {
            region.regionHeight="100%"
            region.marginTop = '0px';
            region.style(region.element, {
                height: region.regionHeight,
                top: region.marginTop
              });
        }
```

**Comment by timnlupo** [comment]
+1 if there is a better way to do this
