### ISSUE TITLE
Markers plugin: support vertical orientation

### ISSUE THREAD

**Issue by igormaraujo-nuveto** [wavesurfer-js/wavesurfer.js#2444]
Hi, i'm testing the wavesurfer library with a vertical display. However when a add markers using the makers plugin, they appears at the wrong place, like that, it was at horizontal display. I look at the documentation and didn't find a support for markers at vertical display.

The Makers plugin has support for vertical display?

**Comment by thijstriemstra** [comment]
> The Makers plugin has support for vertical display?

No, not yet.

**Comment by skysnolimit08** [comment]
I am also interested (and somewhat dependent) on this feature.
