### ISSUE TITLE
Feature request, or: How to fade-in / fade-out on play/pause?

### ISSUE THREAD

**Issue by suterma** [wavesurfer-js/wavesurfer.js#2450]
## This is a feature request, or a request to update the docs, if this feature is already existing.

I would like to have a quite simple fade-in and fade-out operation that I can apply when toggling play/pause. wavesurfer.js seems a quite advanced and complete audio solution, but I fail to find an example or documentation of such a fading operation in e.g. https://wavesurfer-js.org/docs/methods.html

None of the https://wavesurfer-js.org/plugins/ seem to support this already.

I see that I could write a filter as per https://wavesurfer-js.org/docs/methods.html#connecting-filters and do this myself, but this seems a bit far-fetched for such a simple requirement.

**Is a fading operation really missing, or how could I do that?** Preferably the fade operations should have a lenght parameter and return a promise which resolves when terminated.

**Comment by suterma** [comment]
I have written a promise-based fader operation for the howler.js audio API (https://rat.dev/suterma/replayer-pwa/blob/main/src/code/audio/HowlerFader.ts) and I hoped to be able to find something already available for wavesurver.js

**Comment by thijstriemstra** [comment]
> Is a fading operation really missing,

Afaik it is. Good enhancement request.
