### ISSUE TITLE
regions overlapping

### ISSUE THREAD

**Issue by HassanAslam** [wavesurfer-js/wavesurfer.js#2453]
i have solved region overlapping issue in regions plugin but then it gives new errors that region created after some other region is not giving proper values of start time and end time.
wavesurfer.on('region-updated', region => {
    
here is how i solving regions overlapping

      
        Object.values(wavesurfer.regions.list).forEach((regions, index) => {
    
        if( Object.values(wavesurfer.regions.list)[index+1]) {
            Object.values(wavesurfer.regions.list)[index].attributes.nextRegion =  Object.values(wavesurfer.regions.list)[index+1]
        }
        if( Object.values(wavesurfer.regions.list)[index-1]) {
            Object.values(wavesurfer.regions.list)[index].attributes.backRegion = Object.values(wavesurfer.regions.list)[index-1]
        }
      });

        if(region.attributes.nextRegion && region.end > region.attributes.nextRegion.start ) {
          region.end = region.attributes.nextRegion.start ;

        }
        if(region.attributes.backRegion && region.start < region.attributes.backRegion.end ) {
          region.start = region.attributes.backRegion.end ;
        }

      });

**Comment by thijstriemstra** [comment]
> then it gives new errors

What errors? What version of wavesurfer?

**Comment by HassanAslam** [comment]
@thijstriemstra  when i creat new region between two regions which already created before,then new region is not giving its proper values because of this code which i used to solve region overlapping.

if( Object.values(wavesurfer.regions.list)[index+1]) {
        Object.values(wavesurfer.regions.list)[index].attributes.nextRegion =  Object.values(wavesurfer.regions.list)[index+1]
    }
    if( Object.values(wavesurfer.regions.list)[index-1]) {
        Object.values(wavesurfer.regions.list)[index].attributes.backRegion = Object.values(wavesurfer.regions.list)[index-1]
    }
  });

can anyone give me another way to solve regions overlapping with complete code if anyone have....?
or can anyone tell how to get   nextRegion.start value properly with code.

**Comment by HassanAslam** [comment]
@thijstriemstra  i"m using cdn   <script src="https://unpkg.com/wavesurfer.js"></script>
