### ISSUE TITLE
Regions plugin lag when playing video

### ISSUE THREAD

**Issue by adolfov** [wavesurfer-js/wavesurfer.js#2478]
Starting at version 6.0.0 there's a lot of lag when playing a long video with the regions plugin enabled

https://user-images.githubusercontent.com/10564362/157484423-1f60a8a4-893a-4985-8875-9c2f1068b47f.mp4

### Wavesurfer.js version(s):
6.0.0 +

### Browser and operating system version(s):
Chrome based

### Use behaviour needed to reproduce the issue:
- Use wavesurfer.js version 6.0.0 or later
- Load wavesurfer.js with a video element and peaks data
- Use a long video (30 mins or longer)
- Use the regions plugin and add at least 200 regions
- Play the video

**Comment by thijstriemstra** [comment]
hmm, can you do a diff of the changes to the regions plugin between v6.0 and 5.x?

**Comment by adolfov** [comment]
> hmm, can you do a diff of the changes to the regions plugin between v6.0 and 5.x?

Sure

1. Click here: [diff](https://github.com/katspaugh/wavesurfer.js/compare/5.2.0...6.0.4?diff=unified#diff-e7155624d86da0e6e00723224e8d2069806b92c756b6b1ae11af3168e866e82c)
2. Go to "Files Changed"
3. Scroll down to `src/plugin/regions/region.js`

**Comment by thijstriemstra** [comment]
Maybe that helps to figure out the issue.
