### ISSUE TITLE
DOMException: The play() request was interrupted by a call to pause()

### ISSUE THREAD

**Issue by vvillalo** [wavesurfer-js/wavesurfer.js#2484]
Hi,

We have made tests to stream public link unfortunately with not succesfull results:
![image (2)](https://user-images.githubusercontent.com/9408803/159064536-b810a3a7-6bc9-4a43-bd55-4304d7746bd5.png)

It starts reproducing but at some point pauses similar to this below:

https://github.com/katspaugh/wavesurfer.js/issues/771
Regards,

### Wavesurfer.js version(s):
![wavesurferversion_PV](https://user-images.githubusercontent.com/9408803/159064559-89b1a4f9-d8b9-45e8-bd25-7bc079d00590.png)
![wavesurferversion](https://user-images.githubusercontent.com/9408803/159064585-94c7902d-ed05-46f7-b390-ed0797ae3667.png)

### Browser and operating system version(s):
Ubuntu 20.04.4 LTS
Version 98.0.4758.102 (Official Build) (64-bit) Chrome

### Code needed to reproduce the issue:
```js
function openAudio(data, windowWidth, windowHeight) {
        /*
            data looks like:
            {base64: <string>, mimetype: <string>} or {url: <string>}
        */
        $("#close-player").click();
        $("#audio-div").empty();
        $("#audioPlayerTemplate").tmpl({}).appendTo("#audio-div");
        $("#audio-div").show();

        var playPauseIcon = document.getElementById(
            window.btoa(data.url) + "-play-pause-icon"
        );

        var playPauseButton = document.getElementById(
            window.btoa(data.url) + "-play-pause-button"
        );

        document.querySelectorAll(
            'button[button-name="attachment-button"]'
        ).forEach(function(b) {b.disabled = true;})

        playPauseIcon.src = js_static_url + "loading.gif";

        var waveconfig = {
            backend: "MediaElement",
            container: '#waveform',
            progressColor: 'hsla(200, 100%, 30%, 0.5)',
            cursorColor: '#fff',
            progressColor: "#e67e22",
            waveColor: "#fff",
            normalize: true,
            barWidth: 2,
            height: 30,
            maxCanvasWidth: 100,
        }

        var domains_without_cors = ['dialpad.com', 'dialpadbeta.com'];

        if(data.url && new RegExp(domains_without_cors.join('|')).test(data.url)){
            waveconfig.xhr = { cache: 'default', mode: 'no-cors', method: 'GET', credentials: 'same-origin', redirect: 'follow', referrer: 'client', headers: [{}]};
        }

        var wavesurfer = WaveSurfer.create(waveconfig);

        if (data.base64 && data.mimetype) {
            var blob = b64toBlob(data.base64, data.mimetype);
            wavesurfer.loadBlob(blob);
        } else if (data.url){
            wavesurfer.load(data.url);
        } else {
            util.notify({'text': LANG.error_ocurred,  'type': "error"});
            return null;
        }

        $('#close-player').on('click', function(){
            if(wavesurfer.backend){
                wavesurfer.empty();
                wavesurfer.destroy();
            }
            $("#audio-duration").html("");
            $('#audio-progress').show();
            $('#audio-progress').val(0);
            $("#audio-process").html("");
            $("#audio-div").hide();
            playPauseIcon.src = js_static_url + "play.png";
            playPauseButton.removeAttribute("state-in-reproduction");
            document.querySelectorAll(
                'button[button-name="attachment-button"]'
            ).forEach(function(b) {
                b.disabled = false;
            });
        });

        function getDuration(totalSeconds){
            var hours = Math.floor(totalSeconds / 3600);
            totalSeconds %= 3600;
            var minutes = Math.floor(totalSeconds / 60);
            var seconds = parseInt(totalSeconds % 60);
            return (
                ((hours > 0) ? hours + ":" : "")
                + minutes + ":"
                + ((seconds < 10) ? "0"+seconds : seconds)
            );
        }

        wavesurfer.on('loading', function (percents) {
            $('#audio-progress').val(percents);
        });

        wavesurfer.on('ready', function (percents) {
            wavesurfer.play();
            currentAudioLenght = getDuration(wavesurfer.getDuration());
            playPauseIcon.src = js_static_url + "pause.png";
            $("#audio-duration").html(currentAudioLenght);
            $('#audio-progress').hide();
            playPauseButton.setAttribute("state-in-reproduction", "true");
            document.querySelectorAll(
                'button[button-name="attachment-button"]'
            ).forEach(function(b) {b.disabled = false;});
        });

        wavesurfer.on('error', function (e) {
            util.notify({
                'text': e == "XHR error: " ? "Not found" : e,
                'type': "error"
            });
            wavesurfer.empty();
            wavesurfer.destroy();
            $("#audio-duration").html("");
            $('#audio-progress').show();
            $('#audio-progress').val(0);
            $("#audio-process").html("");
            playPauseIcon.src = js_static_url + "try_again.png";
            $("#audio-div").hide();
            playPauseButton.removeAttribute("state-in-reproduction");
            document.querySelectorAll(
                'button[button-name="attachment-button"]'
            ).forEach(function(b) {
                b.disabled = false;
            });
        });

        wavesurfer.on('play', function (e) {
            playPauseIcon.src = js_static_url + "pause.png";
        });

        wavesurfer.on('pause', function (e) {
            playPauseIcon.src = js_static_url + "play.png";
        });

        wavesurfer.on('seek', function () {
            wavesurfer.play();
        });

        wavesurfer.on('audioprocess', function (seconds) {
            $("#audio-process").html(getDuration(seconds));
        });

        $("#audio-div .play-pause").on("click", function(){
            wavesurfer.playPause();
        });

        playPauseButton.addEventListener('click', function(){
            if(wavesurfer.backend){
                wavesurfer.playPause();
            }
        });
    }
```

**Comment by vvillalo** [comment]
Anybody has a similar issue?

**Comment by thijstriemstra** [comment]
> Anybody has a similar issue?


Have you tried searching the tickets for similar issues? Isn't first time I've seen this DOMException.

**Comment by vvillalo** [comment]
@thijstriemstra  Yes I have like this one https://github.com/katspaugh/wavesurfer.js/issues/771 , recommended using a new version of wavesurfer and we are using the last one.

**Comment by thijstriemstra** [comment]
Can ou eliminate the use of jquery, just js and wavesurfer. Also paste the output of `ffprobe` for our audio file.

**Comment by vvillalo** [comment]
Sure meanwhile I try without use of jquery here is the` ffprobe`:
`ffprobe https://dialpadbeta.com/recording/callrecording/l2dFkGiqMjdH030lkszTG1kYB5dYXNtBovEhsomh1ju3
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mp3 @ 0x555a1e096f00] invalid concatenated file detected - using bitrate for duration
Input #0, mp3, from 'https://dialpadbeta.com/recording/callrecording/l2dFkGiqMjdH030lkszTG1kYB5dYXNtBovEhsomh1ju3':
  Metadata:
    encoder         : LAME 64bits version 3.100 (http://lame.sf.net)
    title           : Conference 5014b8d732bd0cfb608b3206d28337b9_a_bridge
    artist          : FreeSWITCH mod_conference Software Conference Module
  Duration: N/A, start: 0.023021, bitrate: 96 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, mono, fltp, 96 kb/s
    Metadata:
      encoder         : LAME3.100
`

**Comment by thijstriemstra** [comment]
try converting it to wav and see if it makes a difference.

**Comment by vvillalo** [comment]
Converting with a wavesurfer method? Or how do you suggest?

**Comment by thijstriemstra** [comment]
mp3 in browsers is not alwyas stable; wav is (i guess)

**Comment by vvillalo** [comment]
But in our case we need to stream from a url that comes a mp3 from dialpad not wav conversion offline or manual is viable

**Comment by vvillalo** [comment]
It happens with other urls mp3 audios such as https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3 start streaming few seconds and then stops.

**Comment by vvillalo** [comment]
If it helps we had to add this code lines to prevent cors restrictions:


`backend: "MediaElement",`
           

```
waveconfig.xhr = { cache: 'default', mode: 'no-cors', method: 'GET', credentials: 'same-origin', redirect: 'follow', referrer: 'client', headers: [{}]};
        }
```
