### ISSUE TITLE
Audio do not loop in region on browser tab change

### ISSUE THREAD

**Issue by marcinpenkul** [wavesurfer-js/wavesurfer.js#2487]
As in topic, audio do not loop in region on browser tab change. To reproduce the problem you can use the example from https://wavesurfer-js.org/example/regions/index.html. Loop second region and change browser tab. Audio cursor goes beyond the region's border and audio is played to the end. After that if you go back manually to the region and you stay in audio tab, loop state is not lost and audio will be normally looped as expected. In my opinion it should be looped even on browser tab change when audio tab is inactive.

Wavesurfer version: 5.2.0

**Comment by thijstriemstra** [comment]
Would be really essential to mention **what browser** you're talking about, and what operating system. Also, please always use latest wavesurfer.js versionwhen reporting an issue (6.x atm).

**Comment by pixellet14** [comment]
I have the same issue working in cordova app. and the wavesurfer version is 7
