### ISSUE TITLE
Marker "draggable:true" doesn't work in wavesurfer.addMarker();

### ISSUE THREAD

**Issue by Conycorouny** [wavesurfer-js/wavesurfer.js#2491]
Hi,

I'm trying to get to work a Marker via the Markers Plugin. The Marker must be user draggable.

I therefore, at first, implemented the following in wavesurfer.create(). This works like a charm!:

```
wavesurfer = WaveSurfer.create({
    container: "#wave",
    plugins: [
    WaveSurfer.markers.create({ 
markers: [
{
id: "marker",                        
time: 0,
label: "Schwerpunkt",
color: '#51565c',
draggable: true
}
]
})
]
});
```
However, when trying to implement a marker **only** via the below, I can't drag the marker.

```
wavesurfer.addMarker({
id: "marker2",                        
time: 0.5,
label: "Schwerpunkt",
draggable: true,
color: '#000000',
});

```

Draggability does however work, as soon as I create a (first) marker in the WaveSurfer.create method.

This seems to be an issue in wavesurfer.addMarker, not properly setting the "draggable" parameter if not already set by another marker.

Any help in this issue would be very welcome!!

Thanks a lot in advance; and also thanks again for providing the immensly helpful wavesurfer.js program!!! :)

**Comment by thijstriemstra** [comment]
>  thanks again for providing the immensly helpful wavesurfer.js program!!! :)

😺
