### ISSUE TITLE
Problem with Fetch on wave file.  No waveform created.

### ISSUE THREAD

**Issue by doctor30306** [wavesurfer-js/wavesurfer.js#2508]
I have a problem with loading a wave file.  I am using wavesurfer.js 6.1.0 (2022-03-31).  I am running latest version of Chrome on MacOS.

I am able to stream an audio file using a url ("http://somedomain.com/assets/somesong.wav").  The problem is that I get an error on the fetch and it won't create the waveform.

Here is my javascript to create the object:
```
wavesurfer = WaveSurfer.create({
        container: somediv,
        backend: "MediaElement",
        preload: "auto",
        mediaType: 'audio',
        responsive: true,
        waveColor: '#FFF',
        progressColor: '#443e3c',
        mediaControls: false,
        hideScrollbar: true,
        scrollParent: false,
        autoCenter: true,
        fillParent: true,
        minPxPerSec: 10,
        pixelRatio: window.devicePixelRatio || screen.deviceXDPI / screen.logicalXDPI,
        normalize: true,
        barWidth: 1,
        barRadius: 3,
        xhr: { cache: 'default', mode: 'no-cors', method: 'GET', credentials: 'omit', redirect: 'follow', referrer: 'client', requestHeaders: [ { key: "cache-control", value: "no-cache" }, { key: "pragma", value: "no-cache" } ] },
        plugins: [
            WaveSurfer.playhead.create({ returnOnPause: true, moveOnSeek: true, draw: true }),
            WaveSurfer.cursor.create({ showTime: true, opacity: 1, customShowTimeStyle: { 'background-color': '#000', color: '#fff', padding: '2px', 'font-size': '10px' } })
        ]
    });

```
When the URL is a wave file hosted on my webserver, everything works great and the waveform is created:
```
var url="http://136.55.8.180/ASOMediaPlayer/ASOConcerts/ASO 1974-09-21 Shaw 1 of 2 MEDIA FILES/08 ASO 1974-09-21 Applause.wav";
wavesurfer.load(url);
```

When the wave file is hosted on an external webserver, the fetch at line 2791 in wavesurfer.js generates an error:
```
var url = "http://73.54.142.141/ASOMediaPlayerTest/ASOConcerts/ASO 1974-09-21 Shaw 1 of 2 MEDIA FILES/08 ASO 1974-09-21 Applause.wav";
wavesurfer.load(url);

```
What am I doing wrong??

**Comment by Herob527** [comment]
Can you specify an error?

**Comment by thijstriemstra** [comment]
>  I get an error on the fetch and it won't create the waveform.

What error?

**Comment by doctor30306** [comment]
Thanks Herob527 and thijstriemstra for responding.  Sorry for the delay in my response.

Here is the exact message:
`Access to fetch at 'http://73.54.142.141/asomediaplayer/ASOConcerts/ASO%201984-09-29%20Scott%202%20of%202%20MEDIA%20FILES/06%20ASO%201984-09-29%20Applause.wav' from origin 'http://localhost:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

When I comment out the xhr option in my initialization code, everything works great.  I had to turn off HTTPS however..

What am I doing wrong?

**Comment by thijstriemstra** [comment]
> What am I doing wrong?

Search the error message first:

```
 CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by doctor30306** [comment]
I am confused.  I have read the message.  If you look at the xhr option, I am using 'no-cors'.

I assume they have to do something in their webserver to address to 'Access-Control-Allow-Origin' for the request??  I am not sure how to tell them to "fix" this issue...

**Comment by thijstriemstra** [comment]
> I assume they have to do something in their webserver 

Sounds likely. An issue if you don't have control over the webserver.
