### ISSUE TITLE
`<region contentEditable="true">` in Regions plugin

### ISSUE THREAD

**Issue by ApayRus** [wavesurfer-js/wavesurfer.js#2513]
Hi. Is there a way to use `contentEditable="true"` for `<region>` in Regions plugin? 
This feature will make Wavesurfer  instantly the best subtitles editor. 
I tried it in browser now, and excited about it. Tomorrow I will try to realize it in my app. 
Please share your thoughts. 

![Peek 2022-05-15 02-03](https://user-images.githubusercontent.com/1222611/168451046-e3fc8f62-a382-4744-9b3b-4e639b65bf0f.gif)

**Comment by thijstriemstra** [comment]
@ApayRus sounds like a great enhancement, pull requests are welcome!

**Comment by ApayRus** [comment]
@thijstriemstra I am using youtube as a backend :) with `ytdl-core` (node.js `youtube-dl` alternative) and I faced a couple of problems:
1) Cors (xhr options didn't help me, and as I know I should move peaks reading to server), 
2) 1-hour length video (150 mb) kills my browser tab. But 50 mb audio from the same video works fine (renders waveform in 1-2 seconds, which surprised me). 

Now I am reading issues related to server side peaks generations :) 

Then I will try to make Pull Request.

**Comment by vitalii-bulyzhyn** [comment]
Is there any updates on this issue?

**Comment by ApayRus** [comment]
> 

Yesterday I started to work on it :)
`<region><div contentEditable="true"></div> </region>`. 
I have event listener `on('region-click', (region)=> region.play())` 
and haven't understood yet, how to prevent playing region after click on `<div>`. 

My idea is to add new param on initializing region plugin: `contentEditable: true`. It will add editable div inside each region (with  text of phrases - `{start, end, text}`). After editing text, it will be fired event 'region-changed' with new region (new text inside).

**Comment by ApayRus** [comment]
@vitalii-bulyzhyn I opened PR with this features (editableContent + removeButton) :smile_cat:
