### ISSUE TITLE
Remove and update region (Regions plugin)

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [wavesurfer-js/wavesurfer.js#2517]
I've been working with Regions plugin and there is a need to delete region by it's id and update by id, but there is nothing about this in the [docs](https://wavesurfer-js.org/plugins/regions.html) (only add and clear all). Just wondering if there is this functionality implemented or should I do a PR for this?

**Comment by thijstriemstra** [comment]
>  should I do a PR for this?

Prs are always welcome.

**Comment by vitalii-bulyzhyn** [comment]
Perfect, I did find a way to update/remove regions, however I will work on the PR

**Comment by thijstriemstra** [comment]
Also see #2521
