### ISSUE TITLE
How to add play and delete buttons directly on each new region?

### ISSUE THREAD

**Issue by rbracco** [wavesurfer-js/wavesurfer.js#2531]
Hi, first off thank you for this amazing library. I've been able to build some really cool stuff on top of it and I appreciate all the time and hard work that went into it. 

I would like to add a play and delete button directly to each new region that is created but I haven't been able to figure out how. I'm using React + StyledComponents if that's relevant. 

Instead of looking like this:
![image](https://user-images.githubusercontent.com/47190785/172381772-c88063aa-bdb2-4e64-b46b-f0a843a9a293.png)

I want it to look like this:
![image](https://user-images.githubusercontent.com/47190785/172381964-ac61b04a-1a05-4afa-ab8c-aff8e8d78d72.png)

I've searched issues, documentation, and FAQ and the closest I found was this issue:
https://github.com/katspaugh/wavesurfer.js/issues/859 but it doesn't really do what I want (I want to add a handle below and a button above). 

I've tried hooking in to `.wavesurfer-region` in css and adding ::before and ::after states but they aren't clickable and this is a bad idea for accessibility I think. Any help or direction would be appreciated. Thank you.

**Comment by thijstriemstra** [comment]
this sounds a lot like PR #2521 (delete button), can you give that a try and report findings on that pull request @rbracco?
