### ISSUE TITLE
How can I change the spectrogram renderer to multicanvas?

### ISSUE THREAD

**Issue by munenari** [wavesurfer-js/wavesurfer.js#2538]
When the canvas width becomes a large size such as 70000 when using the spectrogram plugin, the canvas drawing fails.
I'm thinking about drawing with multicanvas to solve this,
How can I change the drawer to multicanvas?

**Comment by puneety95** [comment]
I am also facing issue but at very low minPxPerSec . The waveform is getting removed when I am zooming in it. Please help.
