### ISSUE TITLE
API doc for plugins gives incorrect import/require path

### ISSUE THREAD

**Issue by dhdaines** [wavesurfer-js/wavesurfer.js#2541]
This example code, as seen in https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/spectrogram/index.js#L42, but also in all the other plugins, does not work:

```javascript
 * // es6
 * import SpectrogramPlugin from 'wavesurfer.spectrogram.js';
 *
 * // commonjs
 * var SpectrogramPlugin = require('wavesurfer.spectrogram.js');
```

Instead, you need to do this:

```javascript
 * // es6
 * import SpectrogramPlugin from 'wavesurfer.js/dist/plugin/wavesurfer.spectrogram.js';
 *
 * // commonjs
 * var SpectrogramPlugin = require('wavesurfer.js/dist/plugin/wavesurfer.spectrogram.js');
```

I can submit a PR to change the import paths in all the API docs, but I am wondering if instead the build system should be changed so that it *does* work, as importing from a subdirectory is kind of ugly.  Thoughts?

**Comment by thijstriemstra** [comment]
> but I am wondering if instead the build system should be changed so that it does work, as importing from a subdirectory is kind of ugly.

I'm not sure how to instruct webpack to make such an import possible. Any idea?

**Comment by katspaugh** [comment]
Sorry, @thijstriemstra, missed your first message.

We could probably assign aliases like so: https://webpack.js.org/configuration/resolve/

Alternatively, or perhaps additionally, there's a `files` field in package.json where we could list plugin entry files.
