### ISSUE TITLE
Import of Wavesurfer with npm/Rollup module bundler

### ISSUE THREAD

**Issue by stevexm** [wavesurfer-js/wavesurfer.js#2544]
#### Issue is that in npm readme.md the documentation says to:
```
npm install wavesurfer.js --save
```
#### and then in the code:
```
// import
import WaveSurfer from 'wavesurfer.js';
```
#### Issue is that the 'wavesurefer.js' default module is not found. Suggested fix for the documentation is:
```
// import
import WaveSurfer from 'wavesurfer/dist/wavesurfer.min.js';
```

**Comment by thijstriemstra** [comment]
Also: you're using an ANCIENT version of wavesurfer, please use version 6.x

**Comment by thijstriemstra** [comment]
> Suggested fix for the documentation is:

Please open a pull request with such a fix, thanks!
