### ISSUE TITLE
API documentation confusing

### ISSUE THREAD

**Issue by jellohouse** [wavesurfer-js/wavesurfer.js#2547]
In the official API documentation https://wavesurfer-js.org/api/

What do the letters C, T, E, F beside each section in the left sidebar mean? 

--

Also I know not any single person is responsible for the documentation, but in general I find it very messy and hard to find what you are looking for.

We should consider re-designing and re-organizing it.

**Comment by srijanmukherjee** [comment]
I found their meaning by inspecting the elements.
C = class
T = typedef
E = external
F = function
+1 their meaning should be made more specific.

**Comment by thijstriemstra** [comment]
> We should consider re-designing and re-organizing it.

Sounds good, open for suggestions.
