### ISSUE TITLE
Waveform with different bpm sections

### ISSUE THREAD

**Issue by jellohouse** [wavesurfer-js/wavesurfer.js#2548]
I have a wavesurfer where the song loaded has sections with different bpms.
I would like to stretch out the different sections to different widths so that the beats are always on the same "grid lines". 

I added grid lines on every beat (they are all at equal width apart), but where the bpm changes the first time, the audio does not fall on the grid anymore. So I would want to change the width of that section of the audio so it can fall on the grid.

I hope I make myself clear, if anyone has experience with producing music in a DAW you might know exactly what I'm trying to achieve.

Any advice would be greatly appreciated. I'm not sure if this is even possible?

**Comment by thijstriemstra** [comment]
> I added grid lines on every beat

How?

**Comment by jellohouse** [comment]
Hey @thijstriemstra !
So the grid lines I added are actually not part of wavesurfer. They are generated on a canvas behind the wavesurfer. Based on the width of my wavesurfer and the bpm of the song I am able to create a vertical line on every beat.
-----
But now I have a song which contains sections with different bpms - so I would like for these different bpm sections to be stretched out to different widths in the wavesurfer.
So that I will be able to always have the wavesurfer song beat on my vertical grid lines. 
-----
I know it's a bit hard to explain - but I hope you understand what I am trying to achieve

**Comment by thijstriemstra** [comment]
> I know it's a bit hard to explain - but I hope you understand what I am trying to achieve

Can you add a screenshot? I'm curious how it looks like.

**Comment by jellohouse** [comment]
<img width="361" alt="Screen Shot 2022-07-29 at 9 56 31 PM" src="https://user-images.githubusercontent.com/35238978/181865930-ffe37d7b-dc5b-4180-8971-349ca12044ea.png">

**Comment by jellohouse** [comment]
Hey @thijstriemstra any updates or ideas on how I could achieve this?
