### ISSUE TITLE
Failed to load remote url: Error: HTTP error status: 0

### ISSUE THREAD

**Issue by RaphaelBuffl** [wavesurfer-js/wavesurfer.js#2552]
Hey y'all,

im trying to get wavesurfer.js to run and I keep having issues with remote Audio Files. 

I use these xhr options: 

`const xhr = { cache: 'default', mode: 'no-cors', method: 'GET'};`

And among the audio files I tried is: 

- https://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3

The issue is that the waveform does not load and I get this error from the console. 

`Error: HTTP error status: 0
    at fetch.js:210:1`

I would appreciate any help on this, because Im starting to feel desperate :(

Thank you in advance

**Comment by thijstriemstra** [comment]
Take a look at related cors tickets: https://github.com/katspaugh/wavesurfer.js/search?q=cors&type=issues
