### ISSUE TITLE
Regions Plugin: Large files have animation lag

### ISSUE THREAD

**Issue by mindofbp** [wavesurfer-js/wavesurfer.js#2584]
When resizing regions on long audio files (30+ mins) with many regions (50+) the animation is dropping below 60FPS and causing significant lag in the resizing animation. 

I've tried using the pre-recoded peaks feature and limiting the max width of individual canvases to improve load performance but the animation issue still exists. Are there any performance improvements that I can be making here?

**Comment by thijstriemstra** [comment]
>  Are there any performance improvements that I can be making here?

#1281
