### ISSUE TITLE
Looking to get the FROM and TO times when seeking

### ISSUE THREAD

**Issue by Gigamick** [wavesurfer-js/wavesurfer.js#2588]
Using version 6.2.0

This is my code

```
    wavesurfer{{$p}}.on('seek', function () {
        var t = wavesurfer{{$p}}.getCurrentTime();

        $.ajax({
            type: 'POST',
            url: '/updateseek',
            data: {
                trackID: {{$item->track_id}},
                token: "{{$songbox->token}}",
                songbox: "{{$songbox->songbox}}",
                time: t
            }
        });
```

Here I can only get the TO time using the getCurrentTime().

Any ideas?

**Comment by thijstriemstra** [comment]
> Any ideas?

Always remember the starting position in some var. I assume it's always 0 at the beginning and from there on you store the current time.

**Comment by Gigamick** [comment]
I am storing the current time in that code I showed you but that stores the time it skips TO.
