### ISSUE TITLE
'The buffer passed to decodeAudioData contains an unknown content type' Wavesurfer error in firefox

### ISSUE THREAD

**Issue by darshitr19** [wavesurfer-js/wavesurfer.js#2600]
The file with mp3 format not loaded with wave surfer on mozilla firefox. It gives the error in console "'The buffer passed to decodeAudioData contains an unknown content type'". 

But the file gets loaded in browser other than mozilla firefox.

### Wavesurfer.js version(s):
4.3.0

### Browser and operating system version(s):
Mozilla Firefox and Windows 10

**Comment by thijstriemstra** [comment]
> Wavesurfer.js version(s):
> 4.3.0

Always try the latest version first.

**Comment by darshitr19** [comment]
Try after update but the error in console goes away, but it does not load the waveform from file.

**Comment by darshitr19** [comment]
Below are the links from our partner vendor:

https://www.texttovoice.online/audios/v_Z_th-TH_6363563859f78.mp3 --- Not Working

https://www.texttovoice.online/audios/v_A_en-GB_6363565869c79.mp3 --- Working
