### ISSUE TITLE
backend buffer is null when using prerendered peaks

### ISSUE THREAD

**Issue by skysnolimit08** [wavesurfer-js/wavesurfer.js#2617]
Hello.  Thank you all for this project, and in advance for any help you can provide.  I would like to split one audio file into two files, and I take it that for that I need access to the audio buffer that wavesurfer is using.  But when I try to access the buffer after loading prerendered peaks, the buffer is null.

### Code needed to reproduce the issue (I am using Vue 3):
```
mounted() {
this.wavesurfer = WaveSurfer.create({
	container: this.$refs.waveform,
	backend: "MediaElement",
	vertical: true,
});

this.wavesurfer.load(this.audioURL, JSON.parse(data["peaks"]));

let that = this;

this.wavesurfer.on("waveform-ready", function () {
	that.readyVerification += 1;
});

this.wavesurfer.on("ready", function () {
	that.readyVerification += 1;
});

},

watch: {
	readyVerification: function () {
		if (this.readyVerification == 2) {console.log(this.wavesurfer.backend.buffer} // evaluates to null
         }
},

```

### Use behaviour needed to reproduce the issue:

When the page is loaded, this.wavesurfer.backend.buffer is printed as null in the console.  If I print this.wavesurfer.backend instead, I can see that many other values (but not all) within the this.wavesurfer.backend dictionary are also null or undefined.

Thank you all for any help you can provide.

**Comment by skysnolimit08** [comment]
I forgot to mention that removing the JSON.parse(data["peaks"]) param from this.wavesurfer.load bypasses the issue, but is not an acceptable solution for my use case (my large audio files mean that I need prerendered peaks).

Thank you again.

**Comment by kenfehling** [comment]
I've noticed this too. It also causes a thrown error on [wavesurfer.js:1748](https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L1748)
