### ISSUE TITLE
microphone plugin conflict with recorder.js only on iphone 7

### ISSUE THREAD

**Issue by giugit** [wavesurfer-js/wavesurfer.js#2618]
# Hey, thank you for testing and contributing to wavesurfer.js!

I'm using the last version of wavesurfer.js.

I use the microphone plugin with the recorderjs

https://github.com/mattdiamond/Recorderjs

It work fine also on ipad but with iphone when the microphone plugin start

the recording became mute.

If  I start the microphone plugin before, when start recording the plugin stop to work,

this as said only on iphone!

I made some test on app-live.browserstack.com and seem that the problem 
is also on more recent iphone model!

Some has had my problem, i'm passing hours but i'm not able to find

a solution or a workaround for this problem!

Any Idea?

Very Thanks

Giulio

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [ ] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [ ] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [ ] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [ ] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

**Comment by thijstriemstra** [comment]
https://github.com/mattdiamond/Recorderjs hasn't been updated in 6 years, it's obsolete.

**Comment by giugit** [comment]
Thanks [thijstriemstra] could you suggest an alternative? Thank You!
