### ISSUE TITLE
Unhandled Promise Rejection: AbortError

### ISSUE THREAD

**Issue by pmgrace** [wavesurfer-js/wavesurfer.js#2626]
Error in Safari Console - "Unhandled Promise Rejection: AbortError: The operation was aborted." "(anonymous function)" "rejectPromise"

When this error appears, the player stops working and attempting to play another track just shows the same error again. This also prevents any other websites (tested with Soundcloud specifically) with web audio from working until the browser is restarted.

**Wavesurfer.js version(s):** 6.4.0 (via unpkg.com) (backend: MediaElement)

**Browser and operating system version(s):** Mac OS Monterey 12.6.1 and Safari 16.1

**Code needed to reproduce the issue:** Not known if our code is causing the issue or where in the code it would be.

**Use behaviour needed to reproduce the issue:** Music tracks are listed on a page, error can be reproduced by playing each MP3 in turn one after another until the error appears, often this is after 100 or so tracks but can typically happen any where after playing 50 tracks in succession. We know we can replicate this by quickly playing each track in turn, as soon as the pre-rendered peaks are drawn in the player, play the next track. Rinse and repeat until error shows again.

Unable to replicate this same behaviour in Chrome 108 on Windows 10 though, so we assume a Safari/Mac related issue at this time?

**Comment by daslicht** [comment]
Same here sometimes

**Comment by pmgrace** [comment]
@thijstriemstra @katspaugh I'd like this looking in to please, it's possible we'll pay for the work to get it resolved.

**Comment by daslicht** [comment]
Do you load the sind source of multiple tracks on the same page?
I no longer get theses errors after just loading audio opn demand and not all on page load.
Check it out [here](ansolas.com/sound-design)

**Comment by thijstriemstra** [comment]
> I'd like this looking in to please, it's possible we'll pay for the work to get it resolved.

Please send me an email (check git log for address) @pmgrace, cheers.

**Comment by katspaugh** [comment]
I replied per email.
