### ISSUE TITLE
How to create muntilp WaveSurfer Error code: SBOX_FATAL_MEMORY_EXCEEDED

### ISSUE THREAD

**Issue by quynhanhsang** [wavesurfer-js/wavesurfer.js#2628]
limit 50 Item,
I want create muntilp WaveSurfer but Error code: SBOX_FATAL_MEMORY_EXCEEDED: 

![Screenshot_96](https://user-images.githubusercontent.com/31198859/205820041-1299d215-1377-4a7a-a4f9-bae103bd6237.png)
![Screenshot_97](https://user-images.githubusercontent.com/31198859/205820310-eea3a969-41c5-45e8-935e-f0e4075dddff.png)

help me!

**Comment by thijstriemstra** [comment]
What is muntilp?

**Comment by katspaugh** [comment]
Loading and decoding audio files is memory intensive, so loading too many may result in this error.
Consider lazy loading just enough files to show on one screen.
