### ISSUE TITLE
Waveform not displaying in Angular.

### ISSUE THREAD

**Issue by IsaacTimothyLyne** [wavesurfer-js/wavesurfer.js#2630]
Wavesurfer.js version(s): 6.4.0

Angular version 15

Browser and operating system version(s): Chrome (108.0.5359.98)

Code needed to reproduce the issue:

Using script in the header:
`<script src="https://unpkg.com/wavesurfer.js"></script>`

and these in the component:
```
`declare var WaveSurfer: any;
export class DashboardComponent implements OnInit, AfterViewInit {
  wavesurfer: any;
ngAfterViewInit(): void {
    let xhr = {
      cache: 'default',
      mode: 'no-cors',
      method: 'GET',
      credentials: 'same-origin',
      redirect: 'follow',
      referrer: 'client',
      headers: [{ key: 'Authorization', value: 'my-token' }],
    };
```

```
    this.wavesurfer = WaveSurfer.create({
      container: '#waveform',
      waveColor: 'violet',
      progressColor: 'purple',
      fillParent: false,
      minPxPerSec: 10,
      xhr: xhr,
      normalize: true,
    });
  }
 async clickedRow(url: string, composer: string, title: string) {
    this.playingComposer = composer;
    this.playingTitle = title;
    this.wavesurfer.load(url);
    this.wavesurfer.play();
}
}`
```

When opening up the page and looking at the spot where the canvas/waveform should appear, 

<img width="1439" alt="Screen Shot 2022-12-12 at 1 19 04 PM" src="https://user-images.githubusercontent.com/36114164/206937871-30bc7b15-18cf-4e09-ac28-0b97b2b2be30.png">

Empty container with no canvas/display, i have also set zindex to like 1000000 just to make sure it wasn't behind stuff somehow.

Could be caused by this: 
Deprecated - 
<img width="487" alt="Screen Shot 2022-12-12 at 1 22 27 PM" src="https://user-images.githubusercontent.com/36114164/206938069-3b65a46c-7b79-45a9-b7eb-e0c4d75f6943.png">

**Comment by thijstriemstra** [comment]
> Could be caused by this: Deprecated -

Probably not (see #1281).
