### ISSUE TITLE
IndexSizeError: The index is not in the allowed range.

### ISSUE THREAD

**Issue by daslicht** [wavesurfer-js/wavesurfer.js#2637]
Under some circumstances eg when I call teh webpage from a facebook link in safari I get 
```IndexSizeError: The index is not in the allowed range.```
Any idea when this error happens and why ?
here is the page:
["here"](https://ansolas.com/sound-design/avenger/arpeggio)

Once this happend I get :
```
Unhandled Promise Rejection: InvalidStateError: Failed to start the audio device
```

**Comment by daslicht** [comment]
This only happens under macOS Safari

**Comment by daslicht** [comment]
related:
https://github.com/katspaugh/wavesurfer.js/issues/2626

**Comment by thijstriemstra** [comment]
> This only happens under macOS Safari

What version of Safari and macOS?

**Comment by daslicht** [comment]
> > This only happens under macOS Safari
> 
> What version of Safari and macOS?

Ventura latest Safari

I assume it had to do that I instantiated a lot multiple players after each other.
They just loaded the mp3 on page show.
Meanwhile I change teh code that the players load precalculated peak files and only load the mp3 on demand.

Since then I no longer get thos errors. still testing tho

Be welcome to check it out here[]( https://ansolas.com/sound-design)

**Comment by thijstriemstra** [comment]
>  latest Safari

This doesn't mean anything in months from now, please be specific.

**Comment by daslicht** [comment]
> @daslicht this using the latest wavesurfer version too?

yes, but It doent seamed to be related to teh fast initiation of multi0ple wavesurfer instances
