### ISSUE TITLE
Fallback to simple player without wave information

### ISSUE THREAD

**Issue by ivanjaros** [wavesurfer-js/wavesurfer.js#2645]
In case I have large file and no waveforms available, how can i render the player as "simple" player without the waveform? I'd like to use the player and add waveforms later but so far i end up with empty waveform, for large files, so the UI is unusable and I have to use simple html audio instead. Which makes this plugin inherently obsolete.

**Comment by entonbiba** [comment]
@ivanjaros you can simply use html5 player if you don't want to use wavesurfer.js library. If the audio is too large simply generate the audio peaks and apply them that way if you do not want to wait until the drawing is completed. 

```html
<audio controls src="audio.mp3"></audio><button >
<button onclick="wavesurfer.play()">Play</button>
<button onclick="wavesurfer.pause()">Pause</button>
```
