### ISSUE TITLE
How can I get start & end times while zooming?

### ISSUE THREAD

**Issue by irakan** [wavesurfer-js/wavesurfer.js#2653]
For example: if I have this timeline while zooming-in
![Screenshot 2023-01-30 174134](https://user-images.githubusercontent.com/61325228/215511400-d9c1b035-ee85-448a-879c-001075747bd1.png)

Is there a way to get start:  2.25 and end: 3.60?

Note: I am using the timeline plugin.

**Comment by entonbiba** [comment]
@irakan you should be able to get the current time and duration of the track with the following:

```js
wavesurfer.on('zoom', function () {
    wavesurfer.getCurrentTime() // current time
    wavesurfer.getDuration(); // total time
});
```
