### ISSUE TITLE
Export regions to WebVTT?

### ISSUE THREAD

**Issue by amundo** [wavesurfer-js/wavesurfer.js#268]
One challenge with working with audio in a browser is the question of persistence: how should annotation work be saved in a useful form? Obviously sending data (such as region timestamps or annotations) to a server is one option, but for “local” usage, another option might be to add export to [WebVTT](https://developer.mozilla.org/en-US/docs/Web/API/Web_Video_Text_Tracks_Format). It’s a simple, standard text format for subtitling which contains the same kind of info needed for annotation as used in the annotation plugin.

End users could use such an exported file in various ways: YouTube allows uploads in WebVTT, for instance.

More info:
- [HTML5 Doctor](http://html5doctor.com/video-subtitling-and-webvtt/)
- [HTML Rocks](http://www.html5rocks.com/en/tutorials/track/basics/)

**Comment by thijstriemstra** [comment]
@amundo any updates?
