### ISSUE TITLE
Wave Surfer seems to not be working

### ISSUE THREAD

**Issue by AYNSounds** [wavesurfer-js/wavesurfer.js#2726]
First off, thank you so much for the library! Been using it for about a year now and it's just perfect!

However, I think that the library isn't working on all the websites I see using it including mine. I've also seen that there may be a newer version in the works and maybe I can move over to that version.

Thanks in advance!

**Comment by GreenDiscord** [comment]
UNPKG is down due to a issue with their host, [Twitter Status](https://twitter.com/unpkg/status/1636149026830843904) from UNPKG

**Comment by AYNSounds** [comment]
Thanks for letting me know, I thought it was WaveSurfer thing since it wasn't working on other website using WaveSurfer.
