### ISSUE TITLE
Request to submit a tool to your Commercial project listing page

### ISSUE THREAD

**Issue by EasySubtitle** [wavesurfer-js/wavesurfer.js#2732]
Hello!
We are EasySub automatic subtitle generator.
We recently used your wavesurfer.js for our audio track section.
Here is our URL: [https://easyssub.com]()
Hope you can add us to your project list page ([https://wavesurfer-js.org/projects/]()).
Thank you so much.

**Comment by katspaugh** [comment]
The site looks great!

Can you submit a pull request for that? The code of the website is in this repo on the GH-pages branch.

**Comment by EasySubtitle** [comment]
Hello, we are not open source. Hope to add it to the "Commercial" category
of your project list page (https://wavesurfer-js.org/projects/).

katspaugh ***@***.***> 于2023年3月17日周五 13:54写道：

**Comment by katspaugh** [comment]
I understand.

Fork this repository and add it to this table: https://github.com/wavesurfer-js/wavesurfer.js/blob/gh-pages/projects/index.html#L74-L87

**Comment by katspaugh** [comment]
Resolved by https://github.com/wavesurfer-js/wavesurfer.js/pull/2733, thanks!
