### ISSUE TITLE
[Issue] Playhead out-of-sync with Waveform on long audio files

### ISSUE THREAD

**Issue by katspaugh** [wavesurfer-js/wavesurfer.js#2738]
### Discussed in https://github.com/wavesurfer-js/wavesurfer.js/discussions/2737

<div type='discussions-op-text'>

<sup>Originally posted by **kai-shimada** March 21, 2023</sup>
Hello Community!

As I'm developing an Electron transcription app on Mac (WhisperScript), I am facing an issue when navigating the playhead via mouse click in long audio files (>15min).

I noticed that the playhead is not getting placed correctly where I position the cursor. The gap between the cursor position and the placed playhead gets bigger the more you seek into the audio file (see the video). If I set the seek point programmatically using SeekTo, the playhead gets placed correctly. I also noticed that the width of the < wave > or the container is getting calculated incorrectly as it's wider than the actual length of the audio (see the gap after it reaches the end of the audio).

Has anyone experienced the same issue?

https://user-images.githubusercontent.com/79719366/226669156-9b0ebd0d-3b72-41a8-b7f5-7720edfcc41b.mov

I am seeing this issue on WAV 48khz 24 bit as well as on MP3 44,1khz audio files... (it worked with none of the files I tested)

WaveSurfer Version: `6.6.1`
WaveSurfer Option:
```javascript
{
    ...
    backend: 'MediaElement',
    autoCenterImmediately: true,
    responsive: 80,
    normalize: true,
    minPxPerSec: 20,
    splitChannels: false,
    plugins: [
        RegionsPlugin.create({
            edgeScrollWidth: 3,
            dragSelection: true,
            minLength: 0.1,
            showTooltip: false,
            contentEditable: true,
            removeButton: true,
        })
    ]
}
```
I'd appreciate any help! thank you 🙏

</div>

**Comment by entonbiba** [comment]
One thing to look at would be this `responsive: 80` option.

**Comment by kai-shimada** [comment]
@entonbiba I tried w/o that option, but unfortunately It didn't help :(

**Comment by thijstriemstra** [comment]
@kai-shimada can you also try with an older version of wavesurfer, e.g. 6.4.0?

**Comment by kai-shimada** [comment]
@thijstriemstra I tried v6.4.0 and it seems like it is working in this version!

**Comment by katspaugh** [comment]
Thanks for bisecting it, @kai-shimada!

The only big merge in 6.6.0 was #2646, and it indeed touched a lot of things related to rendering, width calculation etc. The other commits were related to CI and regions.
So I suggest we roll #2646 back.

**Comment by katspaugh** [comment]
Please check https://github.com/wavesurfer-js/wavesurfer.js/pull/2741

**Comment by ZaifSenpai** [comment]
I was having same issue in v7.10.1 which got fixed by add `backend: "WebAudio"` to options as suggested in https://github.com/katspaugh/wavesurfer.js/issues/2890#issuecomment-1913432242
