### ISSUE TITLE
getDuration() causes infinite loop when using MediaElement backend + MediaRecorder API (webm format) 

### ISSUE THREAD

**Issue by rbracco** [wavesurfer-js/wavesurfer.js#2763]
### Bug Description:

I have a simple recorder that records audio using the MediaRecorder API and loads it into Wavesurfer. Originally I was using a web worker to encode my audios to MP3 client side, and I used the MediaElement backend to preserve pitch when using a variable playback rate as suggested in #149. This worked, but when I switched to using the much simpler and more common MediaRecorder API, I experienced a very hard to trace infinite loop that led the waveform to not appear followed by chrome to freezing/crashing after about 10 seconds. Switching the backend to WebAudio fixed this, but resulted in extremely warped pitch for my playback feature. Happy to provide any additional info. Thank you. 

### wavesurfer.js version(s): 
6.1.0

### Browser and operating system version(s):
Chrome latest + Ubuntu 20.04

### Tracing the bug:

**Call Stack in console debugger** 
![image](https://user-images.githubusercontent.com/47190785/234089219-63388e41-6e0c-4b00-a3f4-c555641f9239.png)

**`UpdateSize` function** - `requiredCanvases` is infinity causing the infinite loop
![image](https://user-images.githubusercontent.com/47190785/234088858-0af6d91b-7223-4871-bd3e-b53a80cff299.png)

**`DrawBuffers` function** - The root cause is here, where getDuration() is infinity (minPxPerSecond = 20, pixelRatio =1), but I have no idea why. 
![image](https://user-images.githubusercontent.com/47190785/234089139-b75a4018-c991-4899-9cfa-46a1b15d8fcf.png)

Strangely, setting `partialRender: false` causes the code to temporarily work (waveform renders and audio plays) but then it crashes after about 45 seconds. 

### Recorder code:

```
    useEffect(() => {
      if (!audioURL) {
        return;
      }
        fetch(audioURL)
          .then(resp => resp.blob())
          .then(data => {
              onRecordingComplete(data)
          })
    }, [audioURL])


    const toggleRecording = () => {
        isRecording ? stopRecording() : startRecording()
    }

    const startRecording = async () => {

        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
        const recorder = new MediaRecorder(stream);
        const chunks = [];
        recorder.ondataavailable = (e) => chunks.push(e.data);
        recorder.onstop = () => {
          const blob = new Blob(chunks, { type: 'audio/webm' });
          const url = URL.createObjectURL(blob);
          setAudioURL(url);
        };

        recorder.start();
        setIsRecording(true);
        setMediaRecorder(recorder);
      };

      const stopRecording = () => {
        if (mediaRecorder) {
          mediaRecorder.stop();
          setIsRecording(false);
        }
      };
```

**Comment by katspaugh** [comment]
I've noticed this too with audio recorded from a mic. Somehow the duration is Infinity.
I had to add this workaround in the new wavesurfer version: https://github.com/katspaugh/wavesurfer.ts/blob/main/src/wavesurfer.ts#L297

Apparently, it's [never going to be fixed in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=642012). But there are complex [workarounds](https://recordrtc.org/RecordRTC.js.html#line1903).

I'm going to close as wontfix, but please feel free to try the new wavesurfer version with a fix.
