### ISSUE TITLE
Loading compressed files will shorten the progress to 60%

### ISSUE THREAD

**Issue by huangshihao123** [wavesurfer-js/wavesurfer.js#2785]
# Hey, thank you for using and contributing to wavesurfer.js!

## Need help with wavesurfer.js in your app?

Please start a Q&A dicussion in our forum: https://github.com/wavesurfer-js/wavesurfer.js/discussions/new?category=q-a

## Have an idea for a feature?

Consider sharing it in the forum: https://github.com/wavesurfer-js/wavesurfer.js/discussions/new?category=ideas

### Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [ ] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [ ] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [ ] I have searched for [already open issues](https://github.com/wavesurfer-js/wavesurfer.js/issues) which desribe my problem.

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

**Comment by katspaugh** [comment]
It's unclear what you mean. Please take the time to write a proper description. If it's a bug report, provide the steps to reproduce the bug.
