### ISSUE TITLE
Creating a region with addRegion() doesn't save until 'region-updated' is fired

### ISSUE THREAD

**Issue by maxehnert** [wavesurfer-js/wavesurfer.js#432]
I have a button that fires addRegion(). The new region will not save unless I make 'region-update' fire (like dragging the region). 
I could not get it to save without moving it so I added this line: `this.wavesurfer.fireEvent('marker-updated', this);`  in the wavesurefer.regions.js file to the function:

```
WaveSurfer.Regions = {
  //stuff,
  add: function (params) {
    //stuff
    this.wavesurfer.fireEvent('region-updated', this);
  },
```

Is there a different way to add something directly to the `addRegion` call to have it save as it's created?
Thanks.

**Comment by katspaugh** [comment]
What do you mean by save?

**Comment by maxehnert** [comment]
Well right now it's just saving to localstorage. What I mean by save is, when I hit refresh the newly created region would not be there. I've actually copied the regions plugin and modified it slightly to work as a separate marker plugin. Because they are just markers there will be no functionality to them other than just dragging around. 
Maybe I could add a promise to the `addRegion`? but for now this works.
