### ISSUE TITLE
Plugin idea: Silence finder

### ISSUE THREAD

**Issue by amundo** [wavesurfer-js/wavesurfer.js#45]
Hi katspaugh,

This may be offtopic for you at the current stage of the project, in any case I might see if I can pull this idea off myself, but I thought I’d throw the idea out there.

What about a Silence Detection plugin? This would be very useful in transcription applications, where you could play a phrase, transcribe, play another phrase, transcribe, etc. 

There are analogies in other pieces of software; I believe ELAN can do it and I know there’s a plugin in Audacity that adds labels at silences:

http://manual.audacityteam.org/man/Silence_Finder_and_Sound_Finder#silence

I once wrote a simple way to do this in the old Mozilla Audio Data API, which I documented here:

http://stackoverflow.com/questions/11057429/something-like-mozaudioavailable-with-webkits-audio-api

And there is a response from Boris Smus (who wrote a book on the Web Audio API) on how it might be approached in the new standard. 

One question is how one would go about handling the issue of buffering a large audio file, but I suppose you must have figured that out since you’re drawing the waveform of large files already.

Thanks, 
Pat

**Comment by CWSites** [comment]
+1 for the Silence Finder

**Comment by ATouhou** [comment]
+1 for the Silence Finder

Anyone made an extension for silence finding?

**Comment by Frank3K** [comment]
> Anyone made an extension for silence finding?

Doesn't the demo annotation plugin do this? [Demo](http://wavesurfer-js.org/example/annotation/). 
Relevant source: http://wavesurfer-js.org/example/annotation/app.js

**Comment by tinmanse** [comment]
The Annotations Tool is an example of how to use Regions not a plugin.   The data is all preloaded  from [annotations.json](https://wavesurfer-js.org/example/annotation/annotations.json) and [rashomon.json](https://wavesurfer-js.org/example/annotation/rashomon.json).
