### ISSUE TITLE
Individual channel gain control

### ISSUE THREAD

**Issue by Kage1989** [wavesurfer-js/wavesurfer.js#461]
The panner function that is currently present allows control for the "proportion" for each channel into the output. From the audio graph being wired currently, there doesn't seem to have an option to control the volume gain for each individual channel, independent of the volume gain of the other channel.

It seems that I've to add in a ChannelSplitterNode and a ChannelMergerNode and sandwich a GainNode in between for that to happen right? This could be an enhanced feature of the panner method.

**Comment by katspaugh** [comment]
You can have several gain nodes in the graph, I think. So you could have a gain node for each channel and then another gain node for the merged channel.

It seems what you want is achievable using only `setFilter` without changing anything in `webaudio.js`.

**Comment by Kage1989** [comment]
Yup, there can be many gain nodes in the graph. Just to clarify a little bit on `setFilter`, does it connects the audio nodes in series from left to right? For gain control of individual channels, I've to connect the individual channels' gain node in parallel to the channelMergerNode, just like in https://developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode.

**Comment by katspaugh** [comment]
Yes, in series. I get it now. There's no way to insert a parallel sub-graph into the series. I guess we could add a method that takes start node and end node. I had it like that in the beginning, but later we refactored it to a serial list.

**Comment by Kage1989** [comment]
Ok. I'll try to work on a method for this purpose then.
