### ISSUE TITLE
Aurora.js support

### ISSUE THREAD

**Issue by thijstriemstra** [wavesurfer-js/wavesurfer.js#531]
Would be cool to support [aurora.js](https://github.com/audiocogs/aurora.js), making it possible to visualize [other audio formats](https://github.com/audiocogs/aurora.js/wiki/Known-Uses#codecs) (aac, mp3, opus etc) in any browser. Will try to come up with something.

"Aurora.js is a framework that makes writing audio decoders in JavaScript easier. It handles common tasks for you such as dealing with binary data, and the decoding pipeline from source to demuxer to decoder, and finally to the audio hardware itself by abstracting browser audio APIs. Aurora contains two high level APIs for inspecting and playing back decoded audio, and it is easily extendible to support more sources, demuxers, decoders, and audio devices."

**Comment by thijstriemstra** [comment]
@katspaugh or maybe it's a new backend instead of a plugin? Should I introduce a new backend parameter for each supported audio format (e.g. `mp3`, `opus` etc)? Or just `aurora` and just assume the user included e.g. `aac.js` and the url request points to a .aac file?

**Comment by thijstriemstra** [comment]
here's a player class reference for the backend: https://github.com/audiocogs/aurora.js/wiki/Player-Class-Reference

**Comment by katspaugh** [comment]
It would be a cool feature indeed. It should be definitely a backend. Having a single `Aurora` backend sounds nicer than one for each format, but `AuorarMP3`, `AuroraOpus` etc would be also OK. See for yourself what is easier and more convenient.

**Comment by thijstriemstra** [comment]
It's not completely clear to me how to write a new backend but after searching for `backend.` in `wavesurfer.js` it seems a backend needs to implement at least the following methods as they're being called:

```
backend.getPlayedPercents
backend.destroy
backend.init
backend.on
backend.once
backend.getDuration
backend.getCurrentTime
backend.play(start, end)
backend.pause
backend.isPaused
backend.seekTo(progress * this.getDuration())
backend.setVolume(newVolume)
backend.getVolume
backend.setPlaybackRate(rate)
backend.getPeaks(width)
backend.load(url, this.mediaContainer, peaks)
backend.supportsWebAudio
backend.decodeArrayBuffer
backend.disconnectSource
backend.destroy
```

Maybe this should be documented somewhere (wiki?).

**Comment by wilsonlmh** [comment]
I think it should be a fallback mechanism coz Aurora.js currently doesn't provide all codecs in modern browsers. But Aurora.js can act as a complementary component. Maybe one day Aurora.js will replace  all codec in WebAudioAPI because it's controllable in JS.
