### ISSUE TITLE
Feature request: Normalize while not counting small spikes

### ISSUE THREAD

**Issue by Joshfindit** [wavesurfer-js/wavesurfer.js#539]
Say for example a podcast;

99% of the audio is kept within an an expected range, but during the recording someone taps on the mic, causing a peak.

Normalization would then cause the talking to be very quiet.

How about a "don't consider spikes less than (user-defined threshold) ms when normalizing".
Spikes could then be chopped off at the top, truncating to 1.

**Comment by katspaugh** [comment]
Good idea!
