### ISSUE TITLE
Allow visual properties to be set in css

### ISSUE THREAD

**Issue by omerts** [wavesurfer-js/wavesurfer.js#641]
Hello,

I don't know if it is possible, but allowing to set visual options using css would be great for theming. 
For example:
- height
- cursorColor
- cursorWidth
  etc.

**Comment by katspaugh** [comment]
As discussed in #645, I totally agree CSS should be the primary way to customize the look of the waveform.

What we can do to facilitate this, is:

 * Make sure every customizable element has a class (the main waveform, progress waveform etc).
 * Cursor should be a separate element with a class.
 * Document all classes.
 * Take the height of the container as the height of the waveform if no height specified in the options (currently the fallback is 128 px).

Marking this is an enhancement.
