### ISSUE TITLE
pls. finish the docs for regions plug-in

### ISSUE THREAD

**Issue by LBPSlava** [wavesurfer-js/wavesurfer.js#764]
Looking at the source of Annotator at http://wavesurfer-js.org/example/annotation/app.js sugests that the documentation for the regions plug-in on the home site is unfinished... no? What do these do? How are they used?

region-play()
region.playLoop()
region-click

Where does it say that the event "in" is actually used as in:

wavesurfer.on('region-in', function (region, e),{});

Working examples would be very welcome... as is, the docs are incomplete. This awesome project would be much more useful with proper docs. Thanks!

**Comment by thijstriemstra** [comment]
@LBPSlava a pull request is always welcome!

**Comment by harrietsCreativeDabblets** [comment]
I second this request - documentation on the regions would be extremely helpful!
