### ISSUE TITLE
wavesurfer.zoom causes region element - wavesurfer-region to also zoom

### ISSUE THREAD

**Issue by swampthang** [wavesurfer-js/wavesurfer.js#906]
Love this library!

Here's a codepen...
http://codepen.io/swampthang/pen/KaPKxV?editors=1010

If you drag to create a region and then play with the zoom, you'll see that as you zoom out, the region element zoom's out as well but not accurately. Not sure what's happening but wanted to be sure and bring it up.

**Comment by katspaugh** [comment]
I'll check the accuracy, thanks.

**Comment by swampthang** [comment]
In case you're interested I'm experimenting with combining Greensock's GSAP library to trigger play of multiple instances of regions. http://codepen.io/swampthang/pen/RKbKzv
